export const millConstants = {
    GET_ALL_MANUFACTURING_MILLS_REQUEST: 'GET_ALL_MANUFACTURING_MILLS_REQUEST',
    GET_ALL_MANUFACTURING_MILLS_SUCCESS: 'GET_ALL_MANUFACTURING_MILLS_SUCCESS',
    GET_ALL_MANUFACTURING_MILLS_FAILURE: 'GET_ALL_MANUFACTURING_MILLS_FAILURE'
}