export const exprimentalAnalysisConstants = {
    EXPRIMENTAL_ANALYSIS_REQUEST: 'EXPRIMENTAL_ANALYSIS_REQUEST',
    EXPRIMENTAL_ANALYSIS_SUCCESS: 'EXPRIMENTAL_ANALYSIS_SUCCESS',
    EXPRIMENTAL_ANALYSIS_FAILURE: 'EXPRIMENTAL_ANALYSIS_FAILURE',

    CREATE_RISK_DATASET_REQUEST: 'CREATE_RISK_DATASET_REQUEST',
    CREATE_RISK_DATASET_SUCCESS: 'CREATE_RISK_DATASET_SUCCESS',
    CREATE_RISK_DATASET_FAILURE: 'CREATE_RISK_DATASET_FAILURE',
    
    CREATE_RISK_INFORMATION_REQUEST: 'CREATE_RISK_INFORMATION_REQUEST',
    CREATE_RISK_INFORMATION_SUCCESS: 'CREATE_RISK_INFORMATION_SUCCESS',
    CREATE_RISK_INFORMATION_FAILURE: 'CREATE_RISK_INFORMATION_FAILURE',
    
    CREATE_TASK_INFORMATION_REQUEST: 'CREATE_TASK_INFORMATION_REQUEST',
    CREATE_TASK_INFORMATION_SUCCESS: 'CREATE_TASK_INFORMATION_SUCCESS',
    CREATE_TASK_INFORMATION_FAILURE: 'CREATE_TASK_INFORMATION_FAILURE',
    
    CREATE_TASK_DATASET_REQUEST: 'CREATE_TASK_DATASET_REQUEST',
    CREATE_TASK_DATASET_SUCCESS: 'CREATE_TASK_DATASET_SUCCESS',
    CREATE_TASK_DATASET_FAILURE: 'CREATE_TASK_DATASET_FAILURE',

    CREATE_PERT_DATA_REQUEST: 'CREATE_PERT_DATA_REQUEST',
    CREATE_PERT_DATA_SUCCESS: 'CREATE_PERT_DATA_SUCCESS',
    CREATE_PERT_DATA_FAILURE: 'CREATE_PERT_DATA_FAILURE',

    GET_PROBABILITY_DISTRIBUTION_REQUEST: 'GET_PROBABILITY_DISTRIBUTION_REQUEST',
    GET_PROBABILITY_DISTRIBUTION_SUCCESS: 'GET_PROBABILITY_DISTRIBUTION_SUCCESS',
    GET_PROBABILITY_DISTRIBUTION_FAILURE: 'GET_PROBABILITY_DISTRIBUTION_FAILURE',
}