services:
  client:
    image: node:16-alpine
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: sh -c "cd /app && npm install -legacy-peer-deps && npm start"
