export const performTaskConstants = {
    GET_TIMESHEETLOGS_REQUEST: 'GET_TIMESHEETLOGS_REQUEST',
    GET_TIMESHEETLOGS_SUCCESS: 'GET_TIMESHEETLOGS_SUCCESS',
    GET_TIMESHEETLOGS_FAILURE: 'GET_TIMESHEETLOGS_FAILURE',

    GET_TIMERSTATUS_REQUEST: 'GET_TIMERSTATUS_REQUEST',
    GET_TIMERSTATUS_SUCCESS: 'GET_TIMERSTATUS_SUCCESS',
    GET_TIMERSTATUS_FAILURE: 'GET_TIMERSTATUS_FAILURE',

    START_TIMER_REQUEST: 'START_TIMER_REQUEST',
    START_TIMER_SUCCESS: 'START_TIMER_SUCCESS',
    START_TIMER_FAILURE: 'START_TIMER_FAILURE',

    PAUSE_TIMER_REQUEST: 'PAUSE_TIMER_REQUEST',
    PAUSE_TIMER_SUCCESS: 'PAUSE_TIMER_SUCCESS',
    PAUSE_TIMER_FAILURE: 'PAUSE_TIMER_FAILURE',

    CONTINUE_TIMER_REQUEST: 'CONTINUE_TIMER_REQUEST',
    CONTINUE_TIMER_SUCCESS: 'CONTINUE_TIMER_SUCCESS',
    CONTINUE_TIMER_FAILURE: 'CONTINUE_TIMER_FAILURE',

    STOP_TIMER_REQUEST: 'STOP_TIMER_REQUEST',
    STOP_TIMER_SUCCESS: 'STOP_TIMER_SUCCESS',
    STOP_TIMER_FAILURE: 'STOP_TIMER_FAILURE',
  
    ADDNEW_ACTIONCOMMENT_REQUEST: 'ADDNEW_ACTIONCOMMENT_REQUEST',
    ADDNEW_ACTIONCOMMENT_SUCCESS: 'ADDNEW_ACTIONCOMMENT_SUCCESS',
    ADDNEW_ACTIONCOMMENT_FAILURE: 'ADDNEW_ACTIONCOMMENT_FAILURE',
    
    EDIT_ACTIONCOMMENT_REQUEST: 'EDIT_ACTIONCOMMENT_REQUEST',
    EDIT_ACTIONCOMMENT_SUCCESS: 'EDIT_ACTIONCOMMENT_SUCCESS',
    EDIT_ACTIONCOMMENT_FAILURE: 'EDIT_ACTIONCOMMENT_FAILURE',

    EDIT_TASKACTION_REQUEST: 'EDIT_TASKACTION_REQUEST',
    EDIT_TASKACTION_SUCCESS: 'EDIT_TASKACTION_SUCCESS',
    EDIT_TASKACTION_FAILURE: 'EDIT_TASKACTION_FAILURE',
    
    DELETE_ACTIONCOMMENT_REQUEST: 'DELETE_ACTIONCOMMENT_REQUEST',
    DELETE_ACTIONCOMMENT_SUCCESS: 'DELETE_ACTIONCOMMENT_SUCCESS',
    DELETE_ACTIONCOMMENT_FAILURE: 'DELETE_ACTIONCOMMENT_FAILURE',

    CREATE_RESULT_TASK_REQUEST: 'CREATE_RESULT_TASK_REQUEST',
    CREATE_RESULT_TASK_SUCCESS: 'CREATE_RESULT_TASK_SUCCESS',
    CREATE_RESULT_TASK_FAILURE: 'CREATE_RESULT_TASK_FAILURE',

    EDIT_RESULT_TASK_REQUEST: 'EDIT_RESULT_TASK_REQUEST',
    EDIT_RESULT_TASK_SUCCESS: 'EDIT_RESULT_TASK_SUCCESS',
    EDIT_RESULT_TASK_FAILURE: 'EDIT_RESULT_TASK_FAILURE',
    DELETE_TASKACTION_REQUEST: 'DELETE_TASKACTION_REQUEST',
    DELETE_TASKACTION_SUCCESS: 'DELETE_TASKACTION_SUCCESS',
    DELETE_TASKACTION_FAILURE: 'DELETE_TASKACTION_FAILURE',

    ADDNEW_TASKACTION_REQUEST: 'ADDNEW_TASKACTION_REQUEST',
    ADDNEW_TASKACTION_SUCCESS: 'ADDNEW_TASKACTION_SUCCESS',
    ADDNEW_TASKACTION_FAILURE: 'ADDNEW_TASKACTION_FAILURE',
    
    GET_TASKACTION_REQUEST: 'GET_TASKACTION_REQUEST',
    GET_TASKACTION_SUCCESS: 'GET_TASKACTION_SUCCESS',
    GET_TASKACTION_FAILURE: 'GET_TASKACTION_FAILURE',

    CREATE_TASKCOMMENT_REQUEST: 'CREATE_TASKCOMMENT_REQUEST',
    CREATE_TASKCOMMENT_SUCCESS: 'CREATE_TASKCOMMENT_SUCCESS',
    CREATE_TASKCOMMENT_FAILURE: 'CREATE_TASKCOMMENT_FAILURE',

    GET_TASKCOMMENTS_REQUEST: 'GET_TASKCOMMENTS_REQUEST',
    GET_TASKCOMMENTS_SUCCESS: 'GET_TASKCOMMENTS_SUCCESS',
    GET_TASKCOMMENTS_FAILURE: 'GET_TASKCOMMENTS_FAILURE',

    EDIT_TASKCOMMENT_REQUEST: 'EDIT_TASKCOMMENT_REQUEST',
    EDIT_TASKCOMMENT_SUCCESS: 'EDIT_TASKCOMMENT_SUCCESS',
    EDIT_TASKCOMMENT_FAILURE: 'EDIT_TASKCOMMENT_FAILURE',

    DELETE_TASKCOMMENT_REQUEST: 'DELETE_TASKCOMMENT_REQUEST',
    DELETE_TASKCOMMENT_SUCCESS: 'DELETE_TASKCOMMENT_SUCCESS',
    DELETE_TASKCOMMENT_FAILURE: 'DELETE_TASKCOMMENT_FAILURE',

    CREATE_COMMENT_OF_TASKCOMMENT_REQUEST: 'CREATE_COMMENT_OF_TASKCOMMENT_REQUEST',
    CREATE_COMMENT_OF_TASKCOMMENT_SUCCESS: 'CREATE_COMMENT_OF_TASKCOMMENT_SUCCESS',
    CREATE_COMMENT_OF_TASKCOMMENT_FAILURE: 'CREATE_COMMENT_OF_TASKCOMMENT_FAILURE',

    EDIT_COMMENT_OF_TASKCOMMENT_REQUEST: 'EDIT_COMMENT_OF_TASKCOMMENT_REQUEST',
    EDIT_COMMENT_OF_TASKCOMMENT_SUCCESS: 'EDIT_COMMENT_OF_TASKCOMMENT_SUCCESS',
    EDIT_COMMENT_OF_TASKCOMMENT_FAILURE: 'EDIT_COMMENT_OF_TASKCOMMENT_FAILURE',

    DELETE_COMMENT_OF_TASKCOMMENT_REQUEST: 'DELETE_COMMENT_OF_TASKCOMMENT_REQUEST',
    DELETE_COMMENT_OF_TASKCOMMENT_SUCCESS: 'DELETE_COMMENT_OF_TASKCOMMENT_SUCCESS',
    DELETE_COMMENT_OF_TASKCOMMENT_FAILURE: 'DELETE_COMMENT_OF_TASKCOMMENT_FAILURE',

    EVALUATION_ACTION_REQUEST:'EVALUATION_ACTION_REQUEST',
    EVALUATION_ACTION_SUCCESS: 'EVALUATION_ACTION_SUCCESS',
    EVALUATION_ACTION_FAILURE: 'EVALUATION_ACTION_FAILURE',

    CONFIRM_ACTION_REQUEST: 'CONFIRM_ACTION_REQUEST',
    CONFIRM_ACTION_SUCCESS: 'CONFIRM_ACTION_SUCCESS',
    CONFIRM_ACTION_FAILURE: 'CONFIRM_ACTION_FAILURE',

    DOWNLOAD_FILE_REQUEST: 'DOWNLOAD_FILE_REQUEST',
    DOWNLOAD_FILE_SUCCESS: 'DOWNLOAD_FILE_SUCCESS',
    DOWNLOAD_FILE_FAILURE: 'DOWNLOAD_FILE_FAILURE',

    UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
    UPLOAD_FILE_SUCCESS:'UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_FAILURE:'UPLOAD_FILE_FAILURE',
};