export const performTaskConstants = {
    GET_TIMESHEET_LOGS_REQUEST: 'GET_TIMESHEET_LOGS_REQUEST',
    GET_TIMESHEET_LOGS_SUCCESS: 'GET_TIMESHEET_LOGS_SUCCESS',
    GET_TIMESHEET_LOGS_FAILURE: 'GET_TIMESHEET_LOGS_FAILURE',

    GET_TIMERSTATUS_REQUEST: 'GET_TIMERSTATUS_REQUEST',
    GET_TIMERSTATUS_SUCCESS: 'GET_TIMERSTATUS_SUCCESS',
    GET_TIMERSTATUS_FAILURE: 'GET_TIMERSTATUS_FAILURE',

    START_TIMER_REQUEST: 'START_TIMER_REQUEST',
    START_TIMER_SUCCESS: 'START_TIMER_SUCCESS',
    START_TIMER_FAILURE: 'START_TIMER_FAILURE',

    PAUSE_TIMER_REQUEST: 'PAUSE_TIMER_REQUEST',
    PAUSE_TIMER_SUCCESS: 'PAUSE_TIMER_SUCCESS',
    PAUSE_TIMER_FAILURE: 'PAUSE_TIMER_FAILURE',

    CONTINUE_TIMER_REQUEST: 'CONTINUE_TIMER_REQUEST',
    CONTINUE_TIMER_SUCCESS: 'CONTINUE_TIMER_SUCCESS',
    CONTINUE_TIMER_FAILURE: 'CONTINUE_TIMER_FAILURE',

    STOP_TIMER_REQUEST: 'STOP_TIMER_REQUEST',
    STOP_TIMER_SUCCESS: 'STOP_TIMER_SUCCESS',
    STOP_TIMER_FAILURE: 'STOP_TIMER_FAILURE',

    CREATE_ACTION_COMMENT_REQUEST: 'CREATE_ACTION_COMMENT_REQUEST',
    CREATE_ACTION_COMMENT_SUCCESS: 'CREATE_ACTION_COMMENT_SUCCESS',
    CREATE_ACTION_COMMENT_FAILURE: 'CREATE_ACTION_COMMENT_FAILURE',

    EDIT_ACTION_COMMENT_REQUEST: 'EDIT_ACTION_COMMENT_REQUEST',
    EDIT_ACTION_COMMENT_SUCCESS: 'EDIT_ACTION_COMMENT_SUCCESS',
    EDIT_ACTION_COMMENT_FAILURE: 'EDIT_ACTION_COMMENT_FAILURE',

    EDIT_TASK_ACTION_REQUEST: 'EDIT_TASK_ACTION_REQUEST',
    EDIT_TASK_ACTION_SUCCESS: 'EDIT_TASK__ACTION_SUCCESS',
    EDIT_TASK_ACTION_FAILURE: 'EDIT_TASK_ACTION_FAILURE',

    DELETE_ACTION_COMMENT_REQUEST: 'DELETE_ACTION_COMMENT_REQUEST',
    DELETE_ACTION_COMMENT_SUCCESS: 'DELETE_ACTION_COMMENT_SUCCESS',
    DELETE_ACTION_COMMENT_FAILURE: 'DELETE_ACTION_COMMENT_FAILURE',

    CREATE_RESULT_TASK_REQUEST: 'CREATE_RESULT_TASK_REQUEST',
    CREATE_RESULT_TASK_SUCCESS: 'CREATE_RESULT_TASK_SUCCESS',
    CREATE_RESULT_TASK_FAILURE: 'CREATE_RESULT_TASK_FAILURE',

    EDIT_RESULT_TASK_REQUEST: 'EDIT_RESULT_TASK_REQUEST',
    EDIT_RESULT_TASK_SUCCESS: 'EDIT_RESULT_TASK_SUCCESS',
    EDIT_RESULT_TASK_FAILURE: 'EDIT_RESULT_TASK_FAILURE',
    
    DELETE_EVALUATION_REQUEST: 'DELETE_EVALUATION_REQUEST',
    DELETE_EVALUATION_SUCCESS: 'DELETE_EVALUATION_SUCCESS',
    DELETE_EVALUATION_FAILURE: 'DELETE_EVALUATION_FAILURE',

    DELETE_TASK_ACTION_REQUEST: 'DELETE_TASK_ACTION_REQUEST',
    DELETE_TASK_ACTION_SUCCESS: 'DELETE_TASK_ACTION_SUCCESS',
    DELETE_TASK_ACTION_FAILURE: 'DELETE_TASK_ACTION_FAILURE',

    CREATE_TASK_ACTION_REQUEST: 'CREATE_TASK_ACTION_REQUEST',
    CREATE_TASK_ACTION_SUCCESS: 'CREATE_TASK_ACTION_SUCCESS',
    CREATE_TASK_ACTION_FAILURE: 'CREATE_TASK_ACTION_FAILURE',

    CREATE_TASK_COMMENT_REQUEST: 'CREATE_TASK_COMMENT_REQUEST',
    CREATE_TASK_COMMENT_SUCCESS: 'CREATE_TASK_COMMENT_SUCCESS',
    CREATE_TASK_COMMENT_FAILURE: 'CREATE_TASK_COMMENT_FAILURE',

    EDIT_TASK_COMMENT_REQUEST: 'EDIT_TASK_COMMENT_REQUEST',
    EDIT_TASK_COMMENT_SUCCESS: 'EDIT_TASK_COMMENT_SUCCESS',
    EDIT_TASK_COMMENT_FAILURE: 'EDIT_TASK_COMMENT_FAILURE',

    DELETE_TASK_COMMENT_REQUEST: 'DELETE_TASK_COMMENT_REQUEST',
    DELETE_TASK_COMMENT_SUCCESS: 'DELETE_TASK_COMMENT_SUCCESS',
    DELETE_TASK_COMMENT_FAILURE: 'DELETE_TASK_COMMENT_FAILURE',

    CREATE_COMMENT_OF_TASK_COMMENT_REQUEST: 'CREATE_COMMENT_OF_TASK_COMMENT_REQUEST',
    CREATE_COMMENT_OF_TASK_COMMENT_SUCCESS: 'CREATE_COMMENT_OF_TASK_COMMENT_SUCCESS',
    CREATE_COMMENT_OF_TASK_COMMENT_FAILURE: 'CREATE_COMMENT_OF_TASK_COMMENT_FAILURE',

    EDIT_COMMENT_OF_TASK_COMMENT_REQUEST: 'EDIT_COMMENT_OF_TASK_COMMENT_REQUEST',
    EDIT_COMMENT_OF_TASK_COMMENT_SUCCESS: 'EDIT_COMMENT_OF_TASK_COMMENT_SUCCESS',
    EDIT_COMMENT_OF_TASK_COMMENT_FAILURE: 'EDIT_COMMENT_OF_TASK_COMMENT_FAILURE',

    DELETE_COMMENT_OF_TASK_COMMENT_REQUEST: 'DELETE_COMMENT_OF_TASK_COMMENT_REQUEST',
    DELETE_COMMENT_OF_TASK_COMMENT_SUCCESS: 'DELETE_COMMENT_OF_TASK_COMMENT_SUCCESS',
    DELETE_COMMENT_OF_TASK_COMMENT_FAILURE: 'DELETE_COMMENT_OF_TASK_COMMENT_FAILURE',

    EVALUATION_ACTION_REQUEST: 'EVALUATION_ACTION_REQUEST',
    EVALUATION_ACTION_SUCCESS: 'EVALUATION_ACTION_SUCCESS',
    EVALUATION_ACTION_FAILURE: 'EVALUATION_ACTION_FAILURE',

    CONFIRM_ACTION_REQUEST: 'CONFIRM_ACTION_REQUEST',
    CONFIRM_ACTION_SUCCESS: 'CONFIRM_ACTION_SUCCESS',
    CONFIRM_ACTION_FAILURE: 'CONFIRM_ACTION_FAILURE',



    UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
    UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_FAILURE: 'UPLOAD_FILE_FAILURE',

    ADD_TASK_LOG_REQUEST: "ADD_TASK_LOG_REQUEST",
    ADD_TASK_LOG_SUCCESS: "ADD_TASK_LOG_SUCCESS",
    ADD_TASK_LOG_FAILURE: "ADD_TASK_LOG_FAILURE",

    DELETE_FILE_ACTION_REQUEST: 'DELETE_FILE_ACTION_REQUEST',
    DELETE_FILE_ACTION_SUCCESS: 'DELETE_FILE_ACTION_SUCCESS',
    DELETE_FILE_ACTION_FAILURE: 'DELETE_FILE_ACTION_FAILURE',

    DELETE_FILE_COMMENT_OF_ACTION_REQUEST: 'DELETE_FILE_COMMENT_OF_ACTION_REQUEST',
    DELETE_FILE_COMMENT_OF_ACTION_SUCCESS: 'DELETE_FILE_COMMENT_OF_ACTION_SUCCESS',
    DELETE_FILE_COMMENT_OF_ACTION_FAILURE: 'DELETE_FILE_COMMENT_OF_ACTION_FAILURE',

    DELETE_FILE_TASK_COMMENT_REQUEST: 'DELETE_FILE_TASK_COMMENT_REQUEST',
    DELETE_FILE_TASK_COMMENT_SUCCESS: 'DELETE_FILE_TASK_COMMENT_SUCCESS',
    DELETE_FILE_TASK_COMMENT_FAILURE: 'DELETE_FILE_TASK_COMMENT_FAILURE',

    DELETE_FILE_CHILD_TASK_COMMENT_REQUEST: 'DELETE_FILE_CHILD_TASK_COMMENT_REQUEST',
    DELETE_FILE_CHILD_TASK_COMMENT_SUCCESS: 'DELETE_FILE_CHILD_TASK_COMMENT_SUCCESS',
    DELETE_FILE_CHILD_TASK_COMMENT_FAILURE: 'DELETE_FILE_CHILD_TASK_COMMENT_FAILURE',

    GET_TASK_LOG_REQUEST: "GET_TASK_LOG_REQUEST",
    GET_TASK_LOG_SUCCESS: "GET_TASK_LOG_SUCCESS",
    GET_TASK_LOG_FAILURE: "GET_TASK_LOG_FAILURE",

    EDIT_TASK_BY_RESPONSIBLE_REQUEST: 'EDIT_TASK_BY_RESPONSIBLE_REQUEST',
    EDIT_TASK_BY_RESPONSIBLE_SUCCESS: 'EDIT_TASK_BY_RESPONSIBLE_SUCCESS',
    EDIT_TASK_BY_RESPONSIBLE_FAILURE: 'EDIT_TASK_BY_RESPONSIBLE_FAILURE',

    EDIT_TASK_BY_ACCOUNTABLE_REQUEST: 'EDIT_TASK_BY_ACCOUNTABLE_REQUEST',
    EDIT_TASK_BY_ACCOUNTABLE_SUCCESS: 'EDIT_TASK_BY_ACCOUNTABLE_SUCCESS',
    EDIT_TASK_BY_ACCOUNTABLE_FAILURE: 'EDIT_TASK_BY_ACCOUNTABLE_FAILURE',

    EVALUATE_TASK_BY_RESPONSIBLE_REQUEST: 'EVALUATE_TASK_BY_RESPONSIBLE_REQUEST',
    EVALUATE_TASK_BY_RESPONSIBLE_SUCCESS: 'EVALUATE_TASK_BY_RESPONSIBLE_SUCCESS',
    EVALUATE_TASK_BY_RESPONSIBLE_FAILURE: 'EVALUATE_TASK_BY_RESPONSIBLE_FAILURE',

    EVALUATE_TASK_BY_CONSULTED_REQUEST: 'EVALUATE_TASK_BY_CONSULTED_REQUEST',
    EVALUATE_TASK_BY_CONSULTED_SUCCESS: 'EVALUATE_TASK_BY_CONSULTED_SUCCESS',
    EVALUATE_TASK_BY_CONSULTED_FAILURE: 'EVALUATE_TASK_BY_CONSULTED_FAILURE',

    EVALUATE_TASK_BY_ACCOUNTABLE_REQUEST: 'EVALUATE_TASK_BY_ACCOUNTABLE_REQUEST',
    EVALUATE_TASK_BY_ACCOUNTABLE_SUCCESS: 'EVALUATE_TASK_BY_ACCOUNTABLE_SUCCESS',
    EVALUATE_TASK_BY_ACCOUNTABLE_FAILURE: 'EVALUATE_TASK_BY_ACCOUNTABLE_FAILURE',

    DELETE_FILE_TASK_REQUEST: 'DELETE_FILE_TASK_REQUEST',
    DELETE_FILE_TASK_SUCCESS: 'DELETE_FILE_TASK_SUCCESS',
    DELETE_FILE_TASK_FAILURE: 'DELETE_FILE_TASK_FAILURE',

    DELETE_DOCUMENT_TASK_REQUEST: 'DELETE_DOCUMENT_TASK_REQUEST',
    DELETE_DOCUMENT_TASK_SUCCESS: 'DELETE_DOCUMENT_TASK_SUCCESS',
    DELETE_DOCUMENT_TASK_FAILURE: 'DELETE_DOCUMENT_TASK_FAILURE',

    EDIT_DOCUMENT_TASK_REQUEST: 'EDIT_DOCUMENT_TASK_REQUEST',
    EDIT_DOCUMENT_TASK_SUCCESS: 'EDIT_DOCUMENT_TASK_SUCCESS',
    EDIT_DOCUMENT_TASK_FAILURE: 'EDIT_DOCUMENT_TASK_FAILURE',
};