export const performTaskConstants = {
    GETTASK_BYID_REQUEST: 'GETTASK_BYID_REQUEST',
    GETTASK_BYID_SUCCESS: 'GETTASK_BYID_SUCCESS',
    GETTASK_BYID_FAILURE: 'GETTASK_BYID_FAILURE',

    EDIT_ACTIVATE_OF_TASK_REQUEST: 'EDIT_ACTIVATE_OF_TASK_REQUEST',
    EDIT_ACTIVATE_OF_TASK_SUCCESS: 'EDIT_ACTIVATE_OF_TASK_SUCCESS',
    EDIT_ACTIVATE_OF_TASK_FAILURE: 'EDIT_ACTIVATE_OF_TASK_FAILURE',

    GET_TIMESHEET_LOGS_REQUEST: 'GET_TIMESHEET_LOGS_REQUEST',
    GET_TIMESHEET_LOGS_SUCCESS: 'GET_TIMESHEET_LOGS_SUCCESS',
    GET_TIMESHEET_LOGS_FAILURE: 'GET_TIMESHEET_LOGS_FAILURE',

    GET_TIMERSTATUS_REQUEST: 'GET_TIMERSTATUS_REQUEST',
    GET_TIMERSTATUS_SUCCESS: 'GET_TIMERSTATUS_SUCCESS',
    GET_TIMERSTATUS_FAILURE: 'GET_TIMERSTATUS_FAILURE',

    START_TIMER_REQUEST: 'START_TIMER_REQUEST',
    START_TIMER_SUCCESS: 'START_TIMER_SUCCESS',
    START_TIMER_FAILURE: 'START_TIMER_FAILURE',

    PAUSE_TIMER_REQUEST: 'PAUSE_TIMER_REQUEST',
    PAUSE_TIMER_SUCCESS: 'PAUSE_TIMER_SUCCESS',
    PAUSE_TIMER_FAILURE: 'PAUSE_TIMER_FAILURE',

    CONTINUE_TIMER_REQUEST: 'CONTINUE_TIMER_REQUEST',
    CONTINUE_TIMER_SUCCESS: 'CONTINUE_TIMER_SUCCESS',
    CONTINUE_TIMER_FAILURE: 'CONTINUE_TIMER_FAILURE',

    STOP_TIMER_REQUEST: 'STOP_TIMER_REQUEST',
    STOP_TIMER_SUCCESS: 'STOP_TIMER_SUCCESS',
    STOP_TIMER_FAILURE: 'STOP_TIMER_FAILURE',

    STOP_TIMER_ALL_DEVICES_SUCCESS: 'STOP_TIMER_ALL_DEVICES_SUCCESS',

    EDIT_TIME_SHEET_LOG_REQUEST: 'EDIT_TIME_SHEET_LOG_REQUEST',
    EDIT_TIME_SHEET_LOG_SUCCESS: 'EDIT_TIME_SHEET_LOG_SUCCESS',
    EDIT_TIME_SHEET_LOG_FAILE: 'EDIT_TIME_SHEET_LOG_FAILE',

    CREATE_ACTION_COMMENT_REQUEST: 'CREATE_ACTION_COMMENT_REQUEST',
    CREATE_ACTION_COMMENT_SUCCESS: 'CREATE_ACTION_COMMENT_SUCCESS',
    CREATE_ACTION_COMMENT_FAILURE: 'CREATE_ACTION_COMMENT_FAILURE',

    EDIT_ACTION_COMMENT_REQUEST: 'EDIT_ACTION_COMMENT_REQUEST',
    EDIT_ACTION_COMMENT_SUCCESS: 'EDIT_ACTION_COMMENT_SUCCESS',
    EDIT_ACTION_COMMENT_FAILURE: 'EDIT_ACTION_COMMENT_FAILURE',

    EDIT_TASK_ACTION_REQUEST: 'EDIT_TASK_ACTION_REQUEST',
    EDIT_TASK_ACTION_SUCCESS: 'EDIT_TASK__ACTION_SUCCESS',
    EDIT_TASK_ACTION_FAILURE: 'EDIT_TASK_ACTION_FAILURE',

    DELETE_ACTION_COMMENT_REQUEST: 'DELETE_ACTION_COMMENT_REQUEST',
    DELETE_ACTION_COMMENT_SUCCESS: 'DELETE_ACTION_COMMENT_SUCCESS',
    DELETE_ACTION_COMMENT_FAILURE: 'DELETE_ACTION_COMMENT_FAILURE',

    CREATE_RESULT_TASK_REQUEST: 'CREATE_RESULT_TASK_REQUEST',
    CREATE_RESULT_TASK_SUCCESS: 'CREATE_RESULT_TASK_SUCCESS',
    CREATE_RESULT_TASK_FAILURE: 'CREATE_RESULT_TASK_FAILURE',

    EDIT_RESULT_TASK_REQUEST: 'EDIT_RESULT_TASK_REQUEST',
    EDIT_RESULT_TASK_SUCCESS: 'EDIT_RESULT_TASK_SUCCESS',
    EDIT_RESULT_TASK_FAILURE: 'EDIT_RESULT_TASK_FAILURE',

    DELETE_EVALUATION_REQUEST: 'DELETE_EVALUATION_REQUEST',
    DELETE_EVALUATION_SUCCESS: 'DELETE_EVALUATION_SUCCESS',
    DELETE_EVALUATION_FAILURE: 'DELETE_EVALUATION_FAILURE',

    DELETE_TASK_ACTION_REQUEST: 'DELETE_TASK_ACTION_REQUEST',
    DELETE_TASK_ACTION_SUCCESS: 'DELETE_TASK_ACTION_SUCCESS',
    DELETE_TASK_ACTION_FAILURE: 'DELETE_TASK_ACTION_FAILURE',

    CREATE_TASK_ACTION_REQUEST: 'CREATE_TASK_ACTION_REQUEST',
    CREATE_TASK_ACTION_SUCCESS: 'CREATE_TASK_ACTION_SUCCESS',
    CREATE_TASK_ACTION_FAILURE: 'CREATE_TASK_ACTION_FAILURE',

    CREATE_TASK_COMMENT_REQUEST: 'CREATE_TASK_COMMENT_REQUEST',
    CREATE_TASK_COMMENT_SUCCESS: 'CREATE_TASK_COMMENT_SUCCESS',
    CREATE_TASK_COMMENT_FAILURE: 'CREATE_TASK_COMMENT_FAILURE',

    EDIT_TASK_COMMENT_REQUEST: 'EDIT_TASK_COMMENT_REQUEST',
    EDIT_TASK_COMMENT_SUCCESS: 'EDIT_TASK_COMMENT_SUCCESS',
    EDIT_TASK_COMMENT_FAILURE: 'EDIT_TASK_COMMENT_FAILURE',

    DELETE_TASK_COMMENT_REQUEST: 'DELETE_TASK_COMMENT_REQUEST',
    DELETE_TASK_COMMENT_SUCCESS: 'DELETE_TASK_COMMENT_SUCCESS',
    DELETE_TASK_COMMENT_FAILURE: 'DELETE_TASK_COMMENT_FAILURE',

    CREATE_COMMENT_OF_TASK_COMMENT_REQUEST: 'CREATE_COMMENT_OF_TASK_COMMENT_REQUEST',
    CREATE_COMMENT_OF_TASK_COMMENT_SUCCESS: 'CREATE_COMMENT_OF_TASK_COMMENT_SUCCESS',
    CREATE_COMMENT_OF_TASK_COMMENT_FAILURE: 'CREATE_COMMENT_OF_TASK_COMMENT_FAILURE',

    EDIT_COMMENT_OF_TASK_COMMENT_REQUEST: 'EDIT_COMMENT_OF_TASK_COMMENT_REQUEST',
    EDIT_COMMENT_OF_TASK_COMMENT_SUCCESS: 'EDIT_COMMENT_OF_TASK_COMMENT_SUCCESS',
    EDIT_COMMENT_OF_TASK_COMMENT_FAILURE: 'EDIT_COMMENT_OF_TASK_COMMENT_FAILURE',

    DELETE_COMMENT_OF_TASK_COMMENT_REQUEST: 'DELETE_COMMENT_OF_TASK_COMMENT_REQUEST',
    DELETE_COMMENT_OF_TASK_COMMENT_SUCCESS: 'DELETE_COMMENT_OF_TASK_COMMENT_SUCCESS',
    DELETE_COMMENT_OF_TASK_COMMENT_FAILURE: 'DELETE_COMMENT_OF_TASK_COMMENT_FAILURE',

    EVALUATION_ACTION_REQUEST: 'EVALUATION_ACTION_REQUEST',
    EVALUATION_ACTION_SUCCESS: 'EVALUATION_ACTION_SUCCESS',
    EVALUATION_ACTION_FAILURE: 'EVALUATION_ACTION_FAILURE',

    DELETE_ACTION_EVALUATION_REQUEST: 'DELETE_ACTION_EVALUATION_REQUEST',
    DELETE_ACTION_EVALUATION_SUCCESS: 'DELETE_ACTION_EVALUATION_SUCCESS',
    DELETE_ACTION_EVALUATION_FAILURE: 'DELETE_ACTION_EVALUATION_FAILURE',

    CONFIRM_ACTION_REQUEST: 'CONFIRM_ACTION_REQUEST',
    CONFIRM_ACTION_SUCCESS: 'CONFIRM_ACTION_SUCCESS',
    CONFIRM_ACTION_FAILURE: 'CONFIRM_ACTION_FAILURE',



    UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
    UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_FAILURE: 'UPLOAD_FILE_FAILURE',

    ADD_TASK_LOG_REQUEST: "ADD_TASK_LOG_REQUEST",
    ADD_TASK_LOG_SUCCESS: "ADD_TASK_LOG_SUCCESS",
    ADD_TASK_LOG_FAILURE: "ADD_TASK_LOG_FAILURE",

    DELETE_FILE_ACTION_REQUEST: 'DELETE_FILE_ACTION_REQUEST',
    DELETE_FILE_ACTION_SUCCESS: 'DELETE_FILE_ACTION_SUCCESS',
    DELETE_FILE_ACTION_FAILURE: 'DELETE_FILE_ACTION_FAILURE',

    DELETE_FILE_COMMENT_OF_ACTION_REQUEST: 'DELETE_FILE_COMMENT_OF_ACTION_REQUEST',
    DELETE_FILE_COMMENT_OF_ACTION_SUCCESS: 'DELETE_FILE_COMMENT_OF_ACTION_SUCCESS',
    DELETE_FILE_COMMENT_OF_ACTION_FAILURE: 'DELETE_FILE_COMMENT_OF_ACTION_FAILURE',

    DELETE_FILE_TASK_COMMENT_REQUEST: 'DELETE_FILE_TASK_COMMENT_REQUEST',
    DELETE_FILE_TASK_COMMENT_SUCCESS: 'DELETE_FILE_TASK_COMMENT_SUCCESS',
    DELETE_FILE_TASK_COMMENT_FAILURE: 'DELETE_FILE_TASK_COMMENT_FAILURE',

    DELETE_FILE_CHILD_TASK_COMMENT_REQUEST: 'DELETE_FILE_CHILD_TASK_COMMENT_REQUEST',
    DELETE_FILE_CHILD_TASK_COMMENT_SUCCESS: 'DELETE_FILE_CHILD_TASK_COMMENT_SUCCESS',
    DELETE_FILE_CHILD_TASK_COMMENT_FAILURE: 'DELETE_FILE_CHILD_TASK_COMMENT_FAILURE',

    GET_TASK_LOG_REQUEST: "GET_TASK_LOG_REQUEST",
    GET_TASK_LOG_SUCCESS: "GET_TASK_LOG_SUCCESS",
    GET_TASK_LOG_FAILURE: "GET_TASK_LOG_FAILURE",

    EDIT_TASK_BY_RESPONSIBLE_REQUEST: 'EDIT_TASK_BY_RESPONSIBLE_REQUEST',
    EDIT_TASK_BY_RESPONSIBLE_SUCCESS: 'EDIT_TASK_BY_RESPONSIBLE_SUCCESS',
    EDIT_TASK_BY_RESPONSIBLE_FAILURE: 'EDIT_TASK_BY_RESPONSIBLE_FAILURE',

    EDIT_TASK_BY_ACCOUNTABLE_REQUEST: 'EDIT_TASK_BY_ACCOUNTABLE_REQUEST',
    EDIT_TASK_BY_ACCOUNTABLE_SUCCESS: 'EDIT_TASK_BY_ACCOUNTABLE_SUCCESS',
    EDIT_TASK_BY_ACCOUNTABLE_FAILURE: 'EDIT_TASK_BY_ACCOUNTABLE_FAILURE',

    EVALUATE_TASK_BY_RESPONSIBLE_REQUEST: 'EVALUATE_TASK_BY_RESPONSIBLE_REQUEST',
    EVALUATE_TASK_BY_RESPONSIBLE_SUCCESS: 'EVALUATE_TASK_BY_RESPONSIBLE_SUCCESS',
    EVALUATE_TASK_BY_RESPONSIBLE_FAILURE: 'EVALUATE_TASK_BY_RESPONSIBLE_FAILURE',

    EVALUATE_TASK_BY_CONSULTED_REQUEST: 'EVALUATE_TASK_BY_CONSULTED_REQUEST',
    EVALUATE_TASK_BY_CONSULTED_SUCCESS: 'EVALUATE_TASK_BY_CONSULTED_SUCCESS',
    EVALUATE_TASK_BY_CONSULTED_FAILURE: 'EVALUATE_TASK_BY_CONSULTED_FAILURE',

    EVALUATE_TASK_BY_ACCOUNTABLE_REQUEST: 'EVALUATE_TASK_BY_ACCOUNTABLE_REQUEST',
    EVALUATE_TASK_BY_ACCOUNTABLE_SUCCESS: 'EVALUATE_TASK_BY_ACCOUNTABLE_SUCCESS',
    EVALUATE_TASK_BY_ACCOUNTABLE_FAILURE: 'EVALUATE_TASK_BY_ACCOUNTABLE_FAILURE',

    EDIT_HOURS_SPENT_IN_EVALUATION_REQUEST: 'EDIT_HOURS_SPENT_IN_EVALUATION_REQUEST',
    EDIT_HOURS_SPENT_IN_EVALUATION_SUCCESS: 'EDIT_HOURS_SPENT_IN_EVALUATION_SUCCESS',
    EDIT_HOURS_SPENT_IN_EVALUATION_FAILURE: 'EDIT_HOURS_SPENT_IN_EVALUATION_FAILURE',

    DELETE_FILE_TASK_REQUEST: 'DELETE_FILE_TASK_REQUEST',
    DELETE_FILE_TASK_SUCCESS: 'DELETE_FILE_TASK_SUCCESS',
    DELETE_FILE_TASK_FAILURE: 'DELETE_FILE_TASK_FAILURE',

    DELETE_DOCUMENT_TASK_REQUEST: 'DELETE_DOCUMENT_TASK_REQUEST',
    DELETE_DOCUMENT_TASK_SUCCESS: 'DELETE_DOCUMENT_TASK_SUCCESS',
    DELETE_DOCUMENT_TASK_FAILURE: 'DELETE_DOCUMENT_TASK_FAILURE',

    EDIT_DOCUMENT_TASK_REQUEST: 'EDIT_DOCUMENT_TASK_REQUEST',
    EDIT_DOCUMENT_TASK_SUCCESS: 'EDIT_DOCUMENT_TASK_SUCCESS',
    EDIT_DOCUMENT_TASK_FAILURE: 'EDIT_DOCUMENT_TASK_FAILURE',

    EDIT_STATUS_OF_TASK_REQUEST: 'EDIT_STATUS_OF_TASK_REQUEST',
    EDIT_STATUS_OF_TASK_SUCCESS: 'EDIT_STATUS_OF_TASK_SUCCESS',
    EDIT_STATUS_OF_TASK_FAILURE: 'EDIT_STATUS_OF_TASK_FAILURE',

    EDIT_TASK_INFORMATION_REQUEST: 'EDIT_TASK_INFORMATION_REQUEST',
    EDIT_TASK_INFORMATION_SUCCESS: 'EDIT_TASK_INFORMATION_SUCCESS',
    EDIT_TASK_INFORMATION_FAILURE: 'EDIT_TASK_INFORMATION_FAILURE',

    CONFIRM_TASK_REQUEST: 'CONFIRM_TASK_REQUEST',
    CONFIRM_TASK_SUCCESS: 'CONFIRM_TASK_SUCCESS',
    CONFIRM_TASK_FAILURE: 'CONFIRM_TASK_FAILURE',

    REQUEST_AND_APPROVAL_CLOSE_TASK_REQUEST: 'REQUEST_AND_APPROVAL_CLOSE_TASK_REQUEST',
    REQUEST_AND_APPROVAL_CLOSE_TASK_SUCCESS: 'REQUEST_AND_APPROVAL_CLOSE_TASK_SUCCESS',
    REQUEST_AND_APPROVAL_CLOSE_TASK_FAILURE: 'REQUEST_AND_APPROVAL_CLOSE_TASK_FAILURE',

    OPEN_TASK_AGAIN_REQUEST: 'OPEN_TASK_AGAIN_REQUEST',
    OPEN_TASK_AGAIN_SUCCESS: 'OPEN_TASK_AGAIN_SUCCESS',
    OPEN_TASK_AGAIN_FAILURE: 'OPEN_TASK_AGAIN_FAILURE',

    EDIT_EMPLOYEE_COLLABORATED_WITH_ORGANIZATIONAL_UNIT_REQUEST: 'EDIT_EMPLOYEE_COLLABORATED_WITH_ORGANIZATIONAL_UNIT_REQUEST',
    EDIT_EMPLOYEE_COLLABORATED_WITH_ORGANIZATIONAL_UNIT_SUCCESS: 'EDIT_EMPLOYEE_COLLABORATED_WITH_ORGANIZATIONAL_UNIT_SUCCESS',
    EDIT_EMPLOYEE_COLLABORATED_WITH_ORGANIZATIONAL_UNIT_FAILURE: 'EDIT_EMPLOYEE_COLLABORATED_WITH_ORGANIZATIONAL_UNIT_FAILURE',

    CREATE_COMMENT_PROCESS_REQUEST: 'CREATE_COMMENT_PROCESS_REQUEST',
    CREATE_COMMENT_PROCESS_SUCCESS: 'CREATE_COMMENT_PROCESS_SUCCESS',
    CREATE_COMMENT_PROCESS_FAILURE: 'CREATE_COMMENT_PROCESS_FAILURE',

    EDIT_COMMENT_PROCESS_REQUEST: 'EDIT_COMMENT_PROCESS_REQUEST',
    EDIT_COMMENT_PROCESS_SUCCESS: 'EDIT_COMMENT_PROCESS_SUCCESS',
    EDIT_COMMENT_PROCESS_FAILURE: 'EDIT_COMMENT_PROCESS_FAILURE',

    DELETE_COMMENT_PROCESS_REQUEST: 'DELETE_COMMENT_PROCESS_REQUEST',
    DELETE_COMMENT_PROCESS_SUCCESS: 'DELETE_COMMENT_PROCESS_SUCCESS',
    DELETE_COMMENT_PROCESS_FAILURE: 'DELETE_COMMENT_PROCESS_FAILURE',

    CREATE_CHILD_COMMENT_REQUEST: 'CREATE_CHILD_COMMENT_REQUEST',
    CREATE_CHILD_COMMENT_SUCCESS: 'CREATE_CHILD_COMMENT_SUCCESS',
    CREATE_CHILD_COMMENT_FAILURE: 'CREATE_CHILD_COMMENT_FAILURE',

    EDIT_CHILD_COMMENT_REQUEST: 'EDIT_CHILD_COMMENT_REQUEST',
    EDIT_CHILD_COMMENT_SUCCESS: 'EDIT_CHILD_COMMENT_SUCCESS',
    EDIT_CHILD_COMMENT_FAILURE: 'EDIT_CHILD_COMMENT_FAILURE',

    DELETE_CHILD_COMMENT_REQUEST: 'DELETE_CHILD_COMMENT_REQUEST',
    DELETE_CHILD_COMMENT_SUCCESS: 'DELETE_CHILD_COMMENT_SUCCESS',
    DELETE_CHILD_COMMENT_FAILURE: 'DELETE_CHILD_COMMENT_FAILURE',

    DELETE_FILE_COMMENT_REQUEST: 'DELETE_FILE_COMMENT_REQUEST',
    DELETE_FILE_COMMENT_SUCCESS: 'DELETE_FILE_COMMENT_SUCCESS',
    DELETE_FILE_COMMENT_FAILURE: 'DELETE_FILE_COMMENT_FAILURE',

    DELETE_FILE_CHILD_COMMENT_REQUEST: 'DELETE_FILE_CHILD_COMMENT_REQUEST',
    DELETE_FILE_CHILD_COMMENT_SUCCESS: 'DELETE_FILE_CHILD_COMMENT_SUCCESS',
    DELETE_FILE_CHILD_COMMENT_FAILURE: 'DELETE_FILE_CHILD_COMMENT_FAILURE',

    CREATE_COMMENT_PROCESS_INCOMING_REQUEST: 'CREATE_COMMENT_PROCESS_INCOMING_REQUEST',
    CREATE_COMMENT_PROCESS_INCOMING_SUCCESS: 'CREATE_COMMENT_PROCESS_INCOMING_SUCCESS',
    CREATE_COMMENT_PROCESS_INCOMING_FAILURE: 'CREATE_COMMENT_PROCESS_INCOMING_FAILURE',

    EDIT_COMMENT_PROCESS_INCOMING_REQUEST: 'EDIT_COMMENT_PROCESS_INCOMING_REQUEST',
    EDIT_COMMENT_PROCESS_INCOMING_SUCCESS: 'EDIT_COMMENT_PROCESS_INCOMING_SUCCESS',
    EDIT_COMMENT_PROCESS_INCOMING_FAILURE: 'EDIT_COMMENT_PROCESS_INCOMING_FAILURE',

    DELETE_COMMENT_PROCESS_INCOMING_REQUEST: 'DELETE_COMMENT_PROCESS_INCOMING_REQUEST',
    DELETE_COMMENT_PROCESS_INCOMING_SUCCESS: 'DELETE_COMMENT_PROCESS_INCOMING_SUCCESS',
    DELETE_COMMENT_PROCESS_INCOMING_FAILURE: 'DELETE_COMMENT_PROCESS_INCOMING_FAILURE',

    CREATE_CHILD_COMMENT_INCOMING_REQUEST: 'CREATE_CHILD_COMMENT_INCOMING_REQUEST',
    CREATE_CHILD_COMMENT_INCOMING_SUCCESS: 'CREATE_CHILD_COMMENT_INCOMING_SUCCESS',
    CREATE_CHILD_COMMENT_INCOMING_FAILURE: 'CREATE_CHILD_COMMENT_INCOMING_FAILURE',

    EDIT_CHILD_COMMENT_INCOMING_REQUEST: 'EDIT_CHILD_COMMENT_INCOMING_REQUEST',
    EDIT_CHILD_COMMENT_INCOMING_SUCCESS: 'EDIT_CHILD_COMMENT_INCOMING_SUCCESS',
    EDIT_CHILD_COMMENT_INCOMING_FAILURE: 'EDIT_CHILD_COMMENT_INCOMING_FAILURE',

    DELETE_CHILD_COMMENT_INCOMING_REQUEST: 'DELETE_CHILD_COMMENT_INCOMING_REQUEST',
    DELETE_CHILD_COMMENT_INCOMING_SUCCESS: 'DELETE_CHILD_COMMENT_INCOMING_SUCCESS',
    DELETE_CHILD_COMMENT_INCOMING_FAILURE: 'DELETE_CHILD_COMMENT_INCOMING_FAILURE',

    DELETE_FILE_CHILD_COMMENT_INCOMING_REQUEST: 'DELETE_FILE_CHILD_COMMENT_INCOMING_REQUEST',
    DELETE_FILE_CHILD_COMMENT_INCOMING_SUCCESS: 'DELETE_FILE_CHILD_COMMENT_INCOMING_SUCCESS',
    DELETE_FILE_CHILD_COMMENT_INCOMING_FAILURE: 'DELETE_FILE_CHILD_COMMENT_INCOMING_FAILURE',

    GET_ALL_PRECEEDING_TASKS_REQUEST: 'GET_ALL_PRECEEDING_TASKS_REQUEST',
    GET_ALL_PRECEEDING_TASKS__SUCCESS: 'GET_ALL_PRECEEDING_TASKS__SUCCESS',
    GET_ALL_PRECEEDING_TASKS_FAILURE: 'GET_ALL_PRECEEDING_TASKS_FAILURE',

    SORT_ACTIONS_REQUEST: 'SORT_ACTIONS_REQUEST',
    SORT_ACTIONS_SUCCESS: 'SORT_ACTIONS_SUCCESS',
    SORT_ACTIONS_FAILURE: 'SORT_ACTIONS_FAILURE',

    REFRESH_DATA_TASK: 'REFRESH_DATA_TASK',

    EVALUATION_ALL_ACTION_REQUEST: 'EVALUATION_ALL_ACTION_REQUEST',
    EVALUATION_ALL_ACTION_SUCCESS: 'EVALUATION_ALL_ACTION_SUCCESS',
    EVALUATION_ALL_ACTION_FAILURE: 'EVALUATION_ALL_ACTION_FAILURE',

    GET_CURRENT_TASK_TIMESHEET_LOG_IN_UNIT_REQUEST: 'GET_CURRENT_TASK_TIMESHEET_LOG_IN_UNIT_REQUEST',
    GET_CURRENT_TASK_TIMESHEET_LOG_IN_UNIT_SUCCESS: 'GET_CURRENT_TASK_TIMESHEET_LOG_IN_UNIT_SUCCESS',
    GET_CURRENT_TASK_TIMESHEET_LOG_IN_UNIT_FAILURE: 'GET_CURRENT_TASK_TIMESHEET_LOG_IN_UNIT_FAILURE',

    CREATE_TASK_OUTPUT_REQUEST: 'CREATE_TASK_OUTPUT_REQUEST',
    CREATE_TASK_OUTPUT_SUCCESS: 'CREATE_TASK_OUTPUT_SUCCESS',
    CREATE_TASK_OUTPUT_FAILURE: 'CREATE_TASK_OUTPUT_FAILURE',

    GET_TASK_OUTPUTS_REQUEST: 'GET_TASK_OUTPUTS_REQUEST',
    GET_TASK_OUTPUTS_SUCCESS: 'GET_TASK_OUTPUTS_SUCCESS',
    GET_TASK_OUTPUTS_FAILURE: 'GET_TASK_OUTPUTS_FAILURE',

    APPROVE_TASK_OUTPUTS_REQUEST: 'APPROVE_TASK_OUTPUTS_REQUEST',
    APPROVE_TASK_OUTPUTS_SUCCESS: 'APPROVE_TASK_OUTPUTS_SUCCESS',
    APPROVE_TASK_OUTPUTS_FAILURE: 'APPROVE_TASK_OUTPUTS_FAILURE',

    EDIT_SUBMISSION_RESULTS_REQUEST: 'EDIT_SUBMISSION_RESULTS_REQUEST',
    EDIT_SUBMISSION_RESULTS_SUCCESS: 'EDIT_SUBMISSION_RESULTS_SUCCESS',
    EDIT_SUBMISSION_RESULTS_FAILURE: 'EDIT_SUBMISSION_RESULTS_FAILURE',

    DELETE_SUBMISSION_RESULTS_REQUEST: 'DELETE_SUBMISSION_RESULTS_REQUEST',
    DELETE_SUBMISSION_RESULTS_SUCCESS: 'DELETE_SUBMISSION_RESULTS_SUCCESS',
    DELETE_SUBMISSION_RESULTS_FAILURE: 'DELETE_SUBMISSION_RESULTS_FAILURE',
};