export const issueReportConstants = {
    GET_ALL_ISSUES_REQUEST: "GET_ALL_ISSUES_REQUEST",
    GET_ALL_ISSUES_SUCCESS: "GET_ALL_ISSUES_SUCCESS",
    GET_ALL_ISSUES_FAILURE: "GET_ALL_ISSUES_FAILURE",

    GET_ISSUE_BY_ID_REQUEST: "GET_ISSUE_BY_ID_REQUEST",
    GET_ISSUE_BY_ID_SUCCESS: "GET_ISSUE_BY_ID_SUCCESS",
    GET_ISSUE_BY_ID_FAILURE: "GET_ISSUE_BY_ID_FAILURE",

    CREATE_ISSUE_REPORT_REQUEST: "CREATE_ISSUE_REPORT_REQUEST",
    CREATE_ISSUE_REPORT_SUCCESS: "CREATE_ISSUE_REPORT_SUCCESS",
    CREATE_ISSUE_REPORT_FAILURE: "CREATE_ISSUE_REPORT_FAILURE",

    EDIT_ISSUE_REPORT_REQUEST: "EDIT_ISSUE_REPORT_REQUEST",
    EDIT_ISSUE_REPORT_SUCCESS: "EDIT_ISSUE_REPORT_SUCCESS",
    EDIT_ISSUE_REPORT_FAILURE: "EDIT_ISSUE_REPORT_FAILURE",

    DELETE_ISSUE_REPORT_REQUEST: "DELETE_ISSUE_REPORT_REQUEST",
    DELETE_ISSUE_REPORT_SUCCESS: "DELETE_ISSUE_REPORT_SUCCESS",
    DELETE_ISSUE_REPORT_FAILURE: "DELETE_ISSUE_REPORT_FAILURE",
}