export const DepartmentConstants = {
    GET_DEPARTMENTS_REQUEST: 'GET_DEPARTMENTS_REQUEST',
    GET_DEPARTMENTS_SUCCESS: 'GET_DEPARTMENTS_SUCCESS',
    GET_DEPARTMENTS_FAILE: 'GET_DEPARTMENTS_FAILE',

    CREATE_DEPARTMENT_REQUEST: 'CREATE_DEPARTMENT_REQUEST',
    CREATE_DEPARTMENT_SUCCESS: 'CREATE_DEPARTMENT_SUCCESS',
    CREATE_DEPARTMENT_FAILE: 'CREATE_DEPARTMENT_FAILE',

    DELETE_DEPARTMENT_REQUEST: 'DELETE_DEPARTMENT_REQUEST',
    DELETE_DEPARTMENT_SUCCESS: 'DELETE_DEPARTMENT_SUCCESS',
    DELETE_DEPARTMENT_FAILE: 'DELETE_DEPARTMENT_FAILE',
}