export const transportationConstants = {
    GET_ALL_DATA_REQUEST: "GET_ALL_DATA_REQUEST",
    GET_ALL_DATA_SUCCESS: "GET_ALL_DATA_SUCCESS",
    GET_EXTERNAL_SYSTEM_SESSION_ID: "GET_EXTERNAL_SESSION_ID",
    GET_SESSION_ID_SUCCESS: "GET_SESSION_ID_SUCCESS",

    GET_ON_TIME_DELIVERY_RATE: "GET_ON_TIME_DELIVERY_RATE",
    GET_ON_TIME_DELIVERY_RATE_SUCCESS: "GET_ON_TIME_DELIVERY_RATE_SUCCESS",
    GET_ON_TIME_DELIVERY_RATE_FAILED: "GET_ON_TIME_DELIVERY_RATE_FAILED",

    GET_ON_TIME_DELIVERY_RATE_PER_MONTH: "GET_ON_TIME_DELIVERY_RATE_PER_MONTH",
    GET_ON_TIME_DELIVERY_RATE_PER_MONTH_SUCCESS: "GET_ON_TIME_DELIVERY_RATE_PER_MONTH_SUCCESS",
    GET_ON_TIME_DELIVERY_RATE_PER_MONTH_FAILED: "GET_ON_TIME_DELIVERY_RATE_PER_MONTH_FAILED",

    GET_ESTIMATED_ON_TIME_DELIVERY_RATE_PER_MONTH: "GET_ESTIMATED_ON_TIME_DELIVERY_RATE_PER_MONTH",
    GET_ESTIMATED_ON_TIME_DELIVERY_RATE_PER_MONTH_SUCCESS: "GET_ESTIMATED_ON_TIME_DELIVERY_RATE_PER_MONTH_SUCCESS",
    GET_ESTIMATED_ON_TIME_DELIVERY_RATE_PER_MONTH_FAILED: "GET_ESTIMATED_ON_TIME_DELIVERY_RATE_PER_MONTH_FAILED",

    GET_DELIVERY_LATE_DAY_AVERAGE_PER_MONTH: "GET_DELIVERY_LATE_DAY_AVERAGE_PER_MONTH",
    GET_DELIVERY_LATE_DAY_AVERAGE_PER_MONTH_SUCCESS: "GET_DELIVERY_LATE_DAY_AVERAGE_PER_MONTH_SUCCESS",
    GET_DELIVERY_LATE_DAY_AVERAGE_PER_MONTH_FAILED: "GET_DELIVERY_LATE_DAY_AVERAGE_PER_MONTH_FAILED",

    GET_TOP_LATE_DELIVERY_DAY: "GET_TOP_LATE_DELIVERY_DAY",
    GET_TOP_LATE_DELIVERY_DAY_SUCCESS: "GET_TOP_LATE_DELIVERY_DAY_SUCCESS",
    GET_TOP_LATE_DELIVERY_DAY_FAILED: "GET_TOP_LATE_DELIVERY_DAY_FAILED",

    GET_TOP_LATE_PRODUCTS: "GET_TOP_LATE_PRODUCTS",
    GET_TOP_LATE_PRODUCTS_SUCCESS: "GET_TOP_LATE_PRODUCTS_SUCCESS",
    GET_TOP_LATE_PRODUCTS_FAILED: "GET_TOP_LATE_PRODUCTS_FAILED",

    GET_TOP_LATE_STOCKS: "GET_TOP_LATE_STOCKS",
    GET_TOP_LATE_STOCKS_SUCCESS: "GET_TOP_LATE_STOCKS_SUCCESS",
    GET_TOP_LATE_STOCKS_FAILED: "GET_TOP_LATE_STOCKS_FAILED"
}
