export const transportationConstants = {
    GET_ALL_DATA_REQUEST: "GET_ALL_DATA_REQUEST",
    GET_ALL_DATA_SUCCESS: "GET_ALL_DATA_SUCCESS",
    GET_EXTERNAL_SYSTEM_SESSION_ID: "GET_EXTERNAL_SESSION_ID",
    GET_SESSION_ID_SUCCESS: "GET_SESSION_ID_SUCCESS",

    GET_ON_TIME_DELIVERY_RATE: "GET_ON_TIME_DELIVERY_RATE",
    GET_ON_TIME_DELIVERY_RATE_SUCCESS: "GET_ON_TIME_DELIVERY_RATE_SUCCESS",
    GET_ON_TIME_DELIVERY_RATE_FAILED: "GET_ON_TIME_DELIVERY_RATE_FAILED"
}