export * from './agePyramidChart';
export * from './employeeDashBoard';
// export * from './barAndLineChart';
// export * from './multipleBarChart';
export * from './annualLeaveTrendsChart';
export * from './humanResourceChartBySalary';
export * from './humanResourceIncreaseAndDecreaseChart';
export * from './highestSalaryChart';
export * from './qualificationChart';
export * from './salaryOfOrganizationalUnitsChart';
export * from './trendOfOvertime';
export * from './tabHumanResource';
export * from './tabSalary';
export * from './tabAnualLeave';
export * from './tabIntegratedStatistics';
export * from './annualLeaveChartAndTable';