export const GoodConstants = {
    GETALL_GOOD_BY_TYPE_REQUEST: 'GET_GOOD_BY_TYPE_REQUEST',
    GETALL_GOOD_BY_TYPE_SUCCESS: 'GET_GOOD_BY_TYPE_SUCCESS',
    GETALL_GOOD_BY_TYPE_FAILURE: 'GET_GOOD_BY_TYPE_FAILURE',

    PAGINATE_GOOD_BY_TYPE_REQUEST: 'PAGINATE_GOOD_BY_TYPE_REQUEST',
    PAGINATE_GOOD_BY_TYPE_SUCCESS: 'PAGINATE_GOOD_BY_TYPE_SUCCESS',
    PAGINATE_GOOD_BY_TYPE_FAILURE: 'PAGINATE_GOOD_BY_TYPE_FAILURE',

    CREATE_GOOD_REQUEST: 'CREATE_GOOD_REQUEST',
    CREATE_GOOD_SUCCESS: 'CREATE_GOOD_SUCCESS',
    CREATE_GOOD_FAILURE: 'CREATE_GOOD_FAILURE',

    UPDATE_GOOD_REQUEST: 'UPDATE_GOOD_REQUEST',
    UPDATE_GOOD_SUCCESS: 'UPDATE_GOOD_SUCCESS',
    UPDATE_GOOD_FAILURE: 'UPDATE_GOOD_FAILURE',

    DELETE_GOOD_REQUEST: 'DELETE_GOOD_REQUEST',
    DELETE_GOOD_SUCCESS: 'DELETE_GOOD_SUCCESS',
    DELETE_GOOD_FAILURE: 'DELETE_GOOD_FAILURE',
}