export const dashboardConstants = {
    GETALL_KPIUNIT_REQUEST: 'GETALL_KPIUNIT_REQUEST',
    GETALL_KPIUNIT_SUCCESS: 'GETALL_KPIUNIT_SUCCESS',
    GETALL_KPIUNIT_FAILURE: 'GETALL_KPIUNIT_FAILURE',

    EVALUATE_KPIUNIT_REQUEST: 'EVALUATE_KPIUNIT_REQUEST',
    EVALUATE_KPIUNIT_SUCCESS: 'EVALUATE_KPIUNIT_SUCCESS',
    EVALUATE_KPIUNIT_FAILURE: 'EVALUATE_KPIUNIT_FAILURE',

    // ADD_KPIUNIT_REQUEST: 'ADD_KPIUNIT_REQUEST',
    // ADD_KPIUNIT_SUCCESS: 'ADD_KPIUNIT_SUCCESS',
    // ADD_KPIUNIT_FAILURE: 'ADD_KPIUNIT_FAILURE',

    // GETCURRENT_KPIUNIT_REQUEST: 'GETCURRENT_KPIUNIT_REQUEST',
    // GETCURRENT_KPIUNIT_SUCCESS: 'GETCURRENT_KPIUNIT_SUCCESS',
    // GETCURRENT_KPIUNIT_FAILURE: 'GETCURRENT_KPIUNIT_FAILURE',

    // GETCHILDTARGET_CURRENTTARGET_REQUEST: 'GETCHILDTARGET_CURRENTTARGET_REQUEST',
    // GETCHILDTARGET_CURRENTTARGET_SUCCESS: 'GETCHILDTARGET_CURRENTTARGET_SUCCESS',
    // GETCHILDTARGET_CURRENTTARGET_FAILURE: 'GETCHILDTARGET_CURRENTTARGET_FAILURE',
}