export const RoleDefaultConstants = {
    GET_ROLES_DEFAULT_REQUEST: 'GET_ROLES_DEFAULT_REQUEST',
    GET_ROLES_DEFAULT_SUCCESS: 'GET_ROLES_DEFAULT_SUCCESS',
    GET_ROLES_DEFAULT_FAILE: 'GET_ROLES_DEFAULT_FAILE',
}