export const DepreciationConstants = {
  UPDATE_DEPRECIATION_REQUEST: 'UPDATE_DEPRECIATION_REQUEST',
  UPDATE_DEPRECIATION_SUCCESS: 'UPDATE_DEPRECIATION_SUCCESS',
  UPDATE_DEPRECIATION_FAILURE: 'UPDATE_DEPRECIATION_FAILURE'
}
