export const WorkPlanConstants = {
  GET_WORK_PLAN_REQUEST: 'GET_WORK_PLAN_REQUEST',
  GET_WORK_PLAN_SUCCESS: 'GET_WORK_PLAN_SUCCESS',
  GET_WORK_PLAN_FAILURE: 'GET_WORK_PLAN_FAILURE',

  CREATE_WORK_PLAN_REQUEST: 'CREATE_NEW_WORK_PLAN_REQUEST',
  CREATE_WORK_PLAN_SUCCESS: 'CREATE_NEW_WORK_PLAN_SUCCESS',
  CREATE_WORK_PLAN_FAILURE: 'CREATE_NEW_WORK_PLAN_FAILURE',

  DELETE_WORK_PLAN_REQUEST: 'DELETE_WORK_PLAN_REQUEST',
  DELETE_WORK_PLAN_SUCCESS: 'DELETE_WORK_PLAN_SUCCESS',
  DELETE_WORK_PLAN_FAILURE: 'DELETE_WORK_PLAN_FAILURE',

  UPDATE_WORK_PLAN_REQUEST: 'UPDATE_WORK_PLAN_REQUEST',
  UPDATE_WORK_PLAN_SUCCESS: 'UPDATE_WORK_PLAN_SUCCESS',
  UPDATE_WORK_PLAN_FAILURE: 'UPDATE_WORK_PLAN_FAILURE',

  IMPORT_WORK_PLAN_REQUEST: 'IMPORT_WORK_PLAN_EMPLOYEE_REQUEST',
  IMPORT_WORK_PLAN_SUCCESS: 'IMPORT_WORK_PLAN_EMPLOYEE_SUCCESS',
  IMPORT_WORK_PLAN_FAILURE: 'IMPORT_WORK_PLAN_EMPLOYEE_FAILURE'
}
