export const LinkConstants = {
    GET_LINKS_REQUEST: 'GET_LINKS_REQUEST',
    GET_LINKS_SUCCESS: 'GET_LINKS_SUCCESS',
    GET_LINKS_FAILE: 'GET_LINKS_FAILE',

    SHOW_LINK_REQUEST: 'SHOW_LINK_REQUEST',
    SHOW_LINK_SUCCESS: 'SHOW_LINK_SUCCESS',
    SHOW_LINK_FAILE: 'SHOW_LINK_FAILE',

    CREATE_LINK_REQUEST: 'CREATE_LINK_REQUEST',
    CREATE_LINK_SUCCESS: 'CREATE_LINK_SUCCESS',
    CREATE_LINK_FAILE: 'CREATE_LINK_FAILE',

    GET_LINKS_OF_ROLE_REQUEST: 'GET_LINKS_OF_ROLE_REQUEST',
    GET_LINKS_OF_ROLE_SUCCESS: 'GET_LINKS_OF_ROLE_SUCCESS',
    GET_LINKS_OF_ROLE_FAILE: 'GET_LINKS_OF_ROLE_FAILE',
}