export const performTaskConstants = {
    GET_LOGTIMER_REQUEST: 'GET_LOGTIMER_REQUEST',
    GET_LOGTIMER_SUCCESS: 'GET_LOGTIMER_SUCCESS',
    GET_LOGTIMER_FAILURE: 'GET_LOGTIMER_FAILURE',

    GET_TIMERSTATUS_REQUEST: 'GET_TIMERSTATUS_REQUEST',
    GET_TIMERSTATUS_SUCCESS: 'GET_TIMERSTATUS_SUCCESS',
    GET_TIMERSTATUS_FAILURE: 'GET_TIMERSTATUS_FAILURE',

    START_TIMER_REQUEST: 'START_TIMER_REQUEST',
    START_TIMER_SUCCESS: 'START_TIMER_SUCCESS',
    START_TIMER_FAILURE: 'START_TIMER_FAILURE',

    PAUSE_TIMER_REQUEST: 'PAUSE_TIMER_REQUEST',
    PAUSE_TIMER_SUCCESS: 'PAUSE_TIMER_SUCCESS',
    PAUSE_TIMER_FAILURE: 'PAUSE_TIMER_FAILURE',

    CONTINUE_TIMER_REQUEST: 'CONTINUE_TIMER_REQUEST',
    CONTINUE_TIMER_SUCCESS: 'CONTINUE_TIMER_SUCCESS',
    CONTINUE_TIMER_FAILURE: 'CONTINUE_TIMER_FAILURE',

    STOP_TIMER_REQUEST: 'STOP_TIMER_REQUEST',
    STOP_TIMER_SUCCESS: 'STOP_TIMER_SUCCESS',
    STOP_TIMER_FAILURE: 'STOP_TIMER_FAILURE',

    GET_COMMENTTASK_REQUEST: 'GET_COMMENTTASK_REQUEST',
    GET_COMMENTTASK_SUCCESS: 'GET_COMMENTTASK_SUCCESS',
    GET_COMMENTTASK_FAILURE: 'GET_COMMENTTASK_FAILURE',
    
    ADDNEW_COMMENTTASK_REQUEST: 'ADDNEW_COMMENTTASK_REQUEST',
    ADDNEW_COMMENTTASK_SUCCESS: 'ADDNEW_COMMENTTASK_SUCCESS',
    ADDNEW_COMMENTTASK_FAILURE: 'ADDNEW_COMMENTTASK_FAILURE',
    
    EDIT_COMMENTTASK_REQUEST: 'EDIT_COMMENTTASK_REQUEST',
    EDIT_COMMENTTASK_SUCCESS: 'EDIT_COMMENTTASK_SUCCESS',
    EDIT_COMMENTTASK_FAILURE: 'EDIT_COMMENTTASK_FAILURE',
    
    DELETE_COMMENTTASK_REQUEST: 'DELETE_COMMENTTASK_REQUEST',
    DELETE_COMMENTTASK_SUCCESS: 'DELETE_COMMENTTASK_SUCCESS',
    DELETE_COMMENTTASK_FAILURE: 'DELETE_COMMENTTASK_FAILURE',
};