export const performTaskConstants = {
    GET_LOGTIMER_REQUEST: 'GET_LOGTIMER_REQUEST',
    GET_LOGTIMER_SUCCESS: 'GET_LOGTIMER_SUCCESS',
    GET_LOGTIMER_FAILURE: 'GET_LOGTIMER_FAILURE',

    GET_TIMERSTATUS_REQUEST: 'GET_TIMERSTATUS_REQUEST',
    GET_TIMERSTATUS_SUCCESS: 'GET_TIMERSTATUS_SUCCESS',
    GET_TIMERSTATUS_FAILURE: 'GET_TIMERSTATUS_FAILURE',

    START_TIMER_REQUEST: 'START_TIMER_REQUEST',
    START_TIMER_SUCCESS: 'START_TIMER_SUCCESS',
    START_TIMER_FAILURE: 'START_TIMER_FAILURE',

    PAUSE_TIMER_REQUEST: 'PAUSE_TIMER_REQUEST',
    PAUSE_TIMER_SUCCESS: 'PAUSE_TIMER_SUCCESS',
    PAUSE_TIMER_FAILURE: 'PAUSE_TIMER_FAILURE',

    CONTINUE_TIMER_REQUEST: 'CONTINUE_TIMER_REQUEST',
    CONTINUE_TIMER_SUCCESS: 'CONTINUE_TIMER_SUCCESS',
    CONTINUE_TIMER_FAILURE: 'CONTINUE_TIMER_FAILURE',

    STOP_TIMER_REQUEST: 'STOP_TIMER_REQUEST',
    STOP_TIMER_SUCCESS: 'STOP_TIMER_SUCCESS',
    STOP_TIMER_FAILURE: 'STOP_TIMER_FAILURE',

    GET_COMMENTTASK_REQUEST: 'GET_COMMENTTASK_REQUEST',
    GET_COMMENTTASK_SUCCESS: 'GET_COMMENTTASK_SUCCESS',
    GET_COMMENTTASK_FAILURE: 'GET_COMMENTTASK_FAILURE',
    
    ADDNEW_COMMENTTASK_REQUEST: 'ADDNEW_COMMENTTASK_REQUEST',
    ADDNEW_COMMENTTASK_SUCCESS: 'ADDNEW_COMMENTTASK_SUCCESS',
    ADDNEW_COMMENTTASK_FAILURE: 'ADDNEW_COMMENTTASK_FAILURE',
    
    EDIT_COMMENTTASK_REQUEST: 'EDIT_COMMENTTASK_REQUEST',
    EDIT_COMMENTTASK_SUCCESS: 'EDIT_COMMENTTASK_SUCCESS',
    EDIT_COMMENTTASK_FAILURE: 'EDIT_COMMENTTASK_FAILURE',

    EDIT_ACTIONTASK_REQUEST: 'EDIT_ACTIONTASK_REQUEST',
    EDIT_ACTIONTASK_SUCCESS: 'EDIT_ACTIONTASK_SUCCESS',
    EDIT_ACTIONTASK_FAILURE: 'EDIT_ACTIONTASK_FAILURE',
    
    DELETE_COMMENTTASK_REQUEST: 'DELETE_COMMENTTASK_REQUEST',
    DELETE_COMMENTTASK_SUCCESS: 'DELETE_COMMENTTASK_SUCCESS',
    DELETE_COMMENTTASK_FAILURE: 'DELETE_COMMENTTASK_FAILURE',

    CREATE_RESULT_TASK_REQUEST: 'CREATE_RESULT_TASK_REQUEST',
    CREATE_RESULT_TASK_SUCCESS: 'CREATE_RESULT_TASK_SUCCESS',
    CREATE_RESULT_TASK_FAILURE: 'CREATE_RESULT_TASK_FAILURE',

    EDIT_RESULT_TASK_REQUEST: 'EDIT_RESULT_TASK_REQUEST',
    EDIT_RESULT_TASK_SUCCESS: 'EDIT_RESULT_TASK_SUCCESS',
    EDIT_RESULT_TASK_FAILURE: 'EDIT_RESULT_TASK_FAILURE',
    DELETE_ACTIONTASK_REQUEST: 'DELETE_ACTIONTASK_REQUEST',
    DELETE_ACTIONTASK_SUCCESS: 'DELETE_ACTIONTASK_SUCCESS',
    DELETE_ACTIONTASK_FAILURE: 'DELETE_ACTIONTASK_FAILURE',

    ADDNEW_ACTIONTASK_REQUEST: 'ADDNEW_ACTIONTASK_REQUEST',
    ADDNEW_ACTIONTASK_SUCCESS: 'ADDNEW_ACTIONTASK_SUCCESS',
    ADDNEW_ACTIONTASK_FAILURE: 'ADDNEW_ACTIONTASK_FAILURE',
    
    GET_ACTIONTASK_REQUEST: 'GET_ACTIONTASK_REQUEST',
    GET_ACTIONTASK_SUCCESS: 'GET_ACTIONTASK_SUCCESS',
    GET_ACTIONTASK_FAILURE: 'GET_ACTIONTASK_FAILURE',
};