export const vehicleConstants = {
    GET_ALL_ONLY_VEHICLE_NAME_REQUEST: "GET_ALL_ONLY_VEHICLE_NAME_REQUEST",
    GET_ALL_ONLY_VEHICLE_NAME_SUCCESS: "GET_ALL_ONLY_VEHICLE_NAME_SUCCESS",
    GET_ALL_ONLY_VEHICLE_NAME_FAILURE: "GET_ALL_ONLY_VEHICLE_NAME_FAILURE",

    GET_ALL_VEHICLE_SCHEDULE_REQUEST: "GET_ALL_VEHICLE_SCHEDULE_REQUEST",
    GET_ALL_VEHICLE_SCHEDULE_SUCCESS: "GET_ALL_VEHICLE_SCHEDULE_SUCCESS",
    GET_ALL_VEHICLE_SCHEDULE_FAILURE: "GET_ALL_VEHICLE_SCHEDULE_FAILURE",

    GET_ALL_VEHICLE_WITH_CONDITION_REQUEST: "GET_ALL_VEHICLE_WITH_CONDITION_REQUEST",
    GET_ALL_VEHICLE_WITH_CONDITION_SUCCESS: "GET_ALL_VEHICLE_WITH_CONDITION_SUCCESS",
    GET_ALL_VEHICLE_WITH_CONDITION_FAILURE: "GET_ALL_VEHICLE_WITH_CONDITION_FAILURE",

    DELETE_VEHICLE_REQUEST: "DELETE_DELETE_VEHICLE_REQUEST",
    DELETE_VEHICLE_SUCCESS: "DELETE_VEHICLE_SUCCESS",
    DELETE_VEHICLE_FAILURE: "DELETE_VEHICLE_FAILURE",

    CREATE_VEHICLE_REQUEST: "CREATE_VEHICLE_REQUEST",
    CREATE_VEHICLE_SUCCESS: "CREATE_VEHICLE_SUCCESS",
    CREATE_VEHICLE_FAILURE: "CREATE_VEHICLE_FAILURE",

    EDIT_VEHICLE_REQUEST: "EDIT_VEHICLE_REQUEST",
    EDIT_VEHICLE_SUCCESS: "EDIT_VEHICLE_SUCCESS",
    EDIT_VEHICLE_FAILURE: "EDIT_VEHICLE_FAILURE",

    GET_VEHICLE_DETAIL_REQUEST: "GET_VEHICLE_DETAIL_REQUEST",
    GET_VEHICLE_DETAIL_SUCCESS: "GET_VEHICLE_DETAIL_SUCCESS",
    GET_VEHICLE_DETAIL_FAILURE: "GET_VEHICLE_DETAIL_FAILURE",

    CALCULATE_VEHICLES_COST_REQUEST: "CALCULATE_VEHICLES_COST_REQUEST",
    CALCULATE_VEHICLES_COST_SUCCESS: "CALCULATE_VEHICLES_COST_SUCCESS",
    CALCULATE_VEHICLES_COST_FAILURE: "CALCULATE_VEHICLES_COST_FAILURE",

    GET_VEHICLES_COST_REQUEST: "GET_VEHICLES_COST_REQUEST",
    GET_VEHICLES_COST_SUCCESS: "GET_VEHICLES_COST_SUCCESS",
    GET_VEHICLES_COST_FAILURE: "GET_VEHICLES_COST_FAILURE",

    UPDATE_REALTIME_VEHICLE_STATUS: "UPDATE_REALTIME_VEHICLE_STATUS",
}