export const managerConstants = {
    GETALL_KPIUNIT_REQUEST: 'GETALL_KPIUNIT_REQUEST',
    GETALL_KPIUNIT_SUCCESS: 'GETALL_KPIUNIT_SUCCESS',
    GETALL_KPIUNIT_FAILURE: 'GETALL_KPIUNIT_FAILURE',

    EVALUATE_KPIUNIT_REQUEST: 'EVALUATE_KPIUNIT_REQUEST',
    EVALUATE_KPIUNIT_SUCCESS: 'EVALUATE_KPIUNIT_SUCCESS',
    EVALUATE_KPIUNIT_FAILURE: 'EVALUATE_KPIUNIT_FAILURE',

    GETCHILDTARGET_CURRENTTARGET_REQUEST: 'GETCHILDTARGET_CURRENTTARGET_REQUEST',
    GETCHILDTARGET_CURRENTTARGET_SUCCESS: 'GETCHILDTARGET_CURRENTTARGET_SUCCESS',
    GETCHILDTARGET_CURRENTTARGET_FAILURE: 'GETCHILDTARGET_CURRENTTARGET_FAILURE',
}