export const AdminDepartmentConstants = {
    GET_ALL_ADMIN_DEPARTMENT_REQUEST: 'GET_ALL_ADMIN_DEPARTMENT_REQUEST',
    GET_ALL_ADMIN_DEPARTMENT_SUCCESS: 'GET_ALL_ADMIN_DEPARTMENT_SUCCESS',
    GET_ALL_ADMIN_DEPARTMENT_FAILURE: 'GET_ALL_ADMIN_DEPARTMENT_FAILURE',

    CREATE_ADMIN_DEPARTMENT_REQUEST: 'CREATE_ADMIN_DEPARTMENT_REQUEST',
    CREATE_ADMIN_DEPARTMENT_SUCCESS: 'CREATE_ADMIN_DEPARTMENT_SUCCESS',
    CREATE_ADMIN_DEPARTMENT_FAILURE: 'CREATE_ADMIN_DEPARTMENT_FAILURE',

    UPDATE_ADMIN_DEPARTMENT_REQUEST: 'UPDATE_ADMIN_DEPARTMENT_REQUEST',
    UPDATE_ADMIN_DEPARTMENT_SUCCESS: 'UPDATE_ADMIN_DEPARTMENT_SUCCESS',
    UPDATE_ADMIN_DEPARTMENT_FAILURE: 'UPDATE_ADMIN_DEPARTMENT_FAILURE'
}