export const manufacturingPlanConstants = {
    GET_ALL_MANUFACTURING_PLANS_REQUEST: "GET_ALL_MANUFACTURING_PLANS_REQUEST",
    GET_ALL_MANUFACTURING_PLANS_SUCCESS: "GET_ALL_MANUFACTURING_PLANS_SUCCESS",
    GET_ALL_MANUFACTURING_PLANS_FAILURE: "GET_ALL_MANUFACTURING_PLANS_FAILURE",

    GET_ALL_APPROVERS_OF_PLAN_REQUEST: 'GET_ALL_APPROVERS_OF_PLAN_REQUEST',
    GET_ALL_APPROVERS_OF_PLAN_SUCCESS: 'GET_ALL_APPROVERS_OF_PLAN_SUCCESS',
    GET_ALL_APPROVERS_OF_PLAN_FAILURE: 'GET_ALL_APPROVERS_OF_PLAN_FAILURE',
}