export const SystemSettingConstants = {
    CREATE_BACKUP_REQUEST: 'CREATE_BACKUP_REQUEST',
    CREATE_BACKUP_SUCCESS: 'CREATE_BACKUP_SUCCESS',
    CREATE_BACKUP_FAILE: 'CREATE_BACKUP_FAILE',

    SET_SCHEDULE_BACKUP_AUTOMATIC_REQUEST: 'SET_SCHEDULE_BACKUP_AUTOMATIC_REQUEST',
    SET_SCHEDULE_BACKUP_AUTOMATIC_SUCCESS: 'SET_SCHEDULE_BACKUP_AUTOMATIC_SUCCESS',
    SET_SCHEDULE_BACKUP_AUTOMATIC_FAILE: 'SET_SCHEDULE_BACKUP_AUTOMATIC_FAILE',

    GET_RESTORE_DATA_REQUEST: 'GET_RESTORE_DATA_REQUEST',
    GET_RESTORE_DATA_SUCCESS: 'GET_RESTORE_DATA_SUCCESS',
    GET_RESTORE_DATA_FAILE: 'GET_RESTORE_DATA_FAILE',

    RESTORE_REQUEST: 'RESTORE_REQUEST',
    RESTORE_SUCCESS: 'RESTORE_SUCCESS',
    RESTORE_FAILE: 'RESTORE_FAILE',
}