export const SocketConstants = {
  CONNECT_SOCKET_IO: 'CONNECT_SOCKET_IO',

  DISCONNECT_SOCKET_IO: 'DISCONNECT_SOCKET_IO',

  SEND_NOTIFICATION: 'SEND_NOTIFICATION',

  RECEIVE_NOTIFICATION: 'RECEIVE_NOTIFICATION'
}
