services:
  database:
    container_name: database
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - service-db:/data/db
      - service-db:/data/configdb
      - service-db:/data/log
    networks:
      - vnist-network
  init-db:
    image: node:alpine
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: sh -c "cd /app && npm install -f && npm run init"
    networks:
      - vnist-network
volumes:
  service-db:
    driver: local
networks:
  vnist-network:
    driver: bridge
#  server:
#    image: node:16-alpine
#    restart: always
#    ports:
#      - "8000:8000"
#    depends_on:
#      - mongo
#    env_file:
#      - ./server/.env
#    volumes:
#        - ./server:/app
#        - /app/node_modules
#    command: sh -c "cd /app && npm install -f && npm start && npm run init"
