version: "3.8"
services:
  delegation-service:
    container_name: delegation-service
    image: node:alpine
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./node_modules:/app/node_modules
      - ./:/app
    command: sh -c "cd /app && npm install && npm start"
