export const AuthorizationLoggingConstants = {
  GET_AUTHORIZATION_LOGGING_REQUEST: 'GET_AUTHORIZATION_LOGGING_REQUEST',
  GET_AUTHORIZATION_LOGGING_SUCCESS: 'GET_AUTHORIZATION_LOGGING_SUCCESS',
  GET_AUTHORIZATION_LOGGING_FAILURE: 'GET_AUTHORIZATION_LOGGING_FAILURE'
}
