export const managerKPIConstants = {
  GETALL_KPIPERSONAL_REQUEST: 'GETALL_KPIPERSONAL_REQUEST',
  GETALL_KPIPERSONAL_SUCCESS: 'GETALL_KPIPERSONAL_SUCCESS',
  GETALL_KPIPERSONAL_FAILURE: 'GETALL_KPIPERSONAL_FAILURE',

  GETALL_KPIPERSONAL_OFTASK_REQUEST: 'GETALL_KPIPERSONAL_OFTASK_REQUEST',
  GETALL_KPIPERSONAL_OFTASK_SUCCESS: 'GETALL_KPIPERSONAL_OFTASK_SUCCESS',
  GETALL_KPIPERSONAL_OFTASK_FAILURE: 'GETALL_KPIPERSONAL_OFTASK_FAILURE',

  GETALL_KPIPERSONAL_IN_ORGANIZATION_BY_MONTH_REQUEST: 'GETALL_KPIPERSONAL_IN_ORGANIZATION_BY_MONTH_REQUEST',
  GETALL_KPIPERSONAL_IN_ORGANIZATION_BY_MONTH_SUCCESS: 'GETALL_KPIPERSONAL_IN_ORGANIZATION_BY_MONTH_SUCCESS',
  GETALL_KPIPERSONAL_IN_ORGANIZATION_BY_MONTH_FAILURE: 'GETALL_KPIPERSONAL_IN_ORGANIZATION_BY_MONTH_FAILURE',

  COPY_KPIPERSONALS_REQUEST: 'COPY_KPIPERSONALS_REQUEST',
  COPY_KPIPERSONALS_SUCCESS: 'COPY_KPIPERSONALS_SUCCESS',
  COPY_KPIPERSONALS_FAILURE: 'COPY_KPIPERSONALS_FAILURE',

  GET_EMPLOYEE_KPI_SET_REQUEST: 'GET_EMPLOYEE_KPI_SET_REQUEST',
  GET_EMPLOYEE_KPI_SET_SUCCESS: 'GET_EMPLOYEE_KPI_SET_SUCCESS',
  GET_EMPLOYEE_KPI_SET_FAILURE: 'GET_EMPLOYEE_KPI_SET_FAILURE'
}
