export const managerKPIConstants = {
    
    GETALL_KPIPERSONAL_REQUEST: 'GETALL_KPIPERSONAL_REQUEST',
    GETALL_KPIPERSONAL_SUCCESS: 'GETALL_KPIPERSONAL_SUCCESS',
    GETALL_KPIPERSONAL_FAILURE: 'GETALL_KPIPERSONAL_FAILURE',
    
    GETALL_KPIPERSONAL_OFTASK_REQUEST: 'GETALL_KPIPERSONAL_OFTASK_REQUEST',
    GETALL_KPIPERSONAL_OFTASK_SUCCESS: 'GETALL_KPIPERSONAL_OFTASK_SUCCESS',
    GETALL_KPIPERSONAL_OFTASK_FAILURE: 'GETALL_KPIPERSONAL_OFTASK_FAILURE',
    
};