export const AssetTypeConstants = {
    GET_ASSET_TYPE_REQUEST: 'GET_ASSET_TYPE_REQUEST',
    GET_ASSET_TYPE_SUCCESS: 'GET_ASSET_TYPE_SUCCESS',
    GET_ASSET_TYPE_FAILURE: 'GET_ASSET_TYPE_FAILURE',

    GET_DOCUMENT_DOMAINS_REQUEST: 'GET_DOCUMENT_DOMAINS_REQUEST',
    GET_DOCUMENT_DOMAINS_SUCCESS: 'GET_DOCUMENT_DOMAINS_SUCCESS',
    GET_DOCUMENT_DOMAINS_FAILE: 'GET_DOCUMENT_DOMAINS_FAILE',

    CREATE_DOCUMENT_DOMAIN_REQUEST: 'CREATE_DOCUMENT_DOMAIN_REQUEST',
    CREATE_DOCUMENT_DOMAIN_SUCCESS: 'CREATE_DOCUMENT_DOMAIN_SUCCESS',
    CREATE_DOCUMENT_DOMAIN_FAILE: 'CREATE_DOCUMENT_DOMAIN_FAILE',

    EDIT_DOCUMENT_DOMAIN_REQUEST: 'EDIT_DOCUMENT_DOMAIN_REQUEST',
    EDIT_DOCUMENT_DOMAIN_SUCCESS: 'EDIT_DOCUMENT_DOMAIN_SUCCESS',
    EDIT_DOCUMENT_DOMAIN_FAILE: 'EDIT_DOCUMENT_DOMAIN_FAILE',

    DELETE_DOCUMENT_DOMAIN_REQUEST: 'DELETE_DOCUMENT_DOMAIN_REQUEST',
    DELETE_DOCUMENT_DOMAIN_SUCCESS: 'DELETE_DOCUMENT_DOMAIN_SUCCESS',
    DELETE_DOCUMENT_DOMAIN_FAILE: 'DELETE_DOCUMENT_DOMAIN_FAILE',
}
export const Users = {
    GET_ALL_USERS : 'GET_ALL_USERS'
}
