export const ContractConstant  = {
    GET_CONTRACT_REQUEST: 'GET_CONTRACT_REQUEST',
    GET_CONTRACT_SUCCESS: 'GET_CONTRACT_SUCCESS',
    GET_CONTRACT_FAILURE: 'GET_CONTRACT_FAILURE',

    CREATE_CONTRACT_REQUEST: 'CREATE_NEW_CONTRACT_REQUEST',
    CREATE_CONTRACT_SUCCESS: 'CREATE_NEW_CONTRACT_SUCCESS',
    CREATE_CONTRACT_FAILURE: 'CREATE_NEW_CONTRACT_FAILURE',

    DELETE_CONTRACT_REQUEST: 'DELETE_CONTRACT_REQUEST',
    DELETE_CONTRACT_SUCCESS:  'DELETE_CONTRACT_SUCCESS',
    DELETE_CONTRACT_FAILURE:  'DELETE_CONTRACT_FAILURE',

    UPDATE_CONTRACT_REQUEST: 'UPDATE_CONTRACT_REQUEST',
    UPDATE_CONTRACT_SUCCESS: 'UPDATE_CONTRACT_SUCCESS',
    UPDATE_CONTRACT_FAILURE: 'UPDATE_CONTRACT_FAILURE',

};