export const DistributeTransferConstants = {
    GET_DISTRIBUTETRANSFER_REQUEST: 'GET_DISTRIBUTETRANSFER_REQUEST',
    GET_DISTRIBUTETRANSFER_SUCCESS: 'GET_DISTRIBUTETRANSFER_SUCCESS',
    GET_DISTRIBUTETRANSFER_FAILURE: 'GET_DISTRIBUTETRANSFER_FAILURE',

    CREATE_DISTRIBUTETRANSFER_REQUEST: 'CREATE_NEW_DISTRIBUTETRANSFER_REQUEST',
    CREATE_DISTRIBUTETRANSFER_SUCCESS: 'CREATE_NEW_DISTRIBUTETRANSFER_SUCCESS',
    CREATE_DISTRIBUTETRANSFER_FAILURE: 'CREATE_NEW_DISTRIBUTETRANSFER_FAILURE',

    DELETE_DISTRIBUTETRANSFER_REQUEST: 'DELETE_DISTRIBUTETRANSFER_REQUEST',
    DELETE_DISTRIBUTETRANSFER_SUCCESS:  'DELETE_DISTRIBUTETRANSFER_SUCCESS',
    DELETE_DISTRIBUTETRANSFER_FAILURE:  'DELETE_DISTRIBUTETRANSFER_FAILURE',

    UPDATE_DISTRIBUTETRANSFER_REQUEST: 'UPDATE_DISTRIBUTETRANSFER_REQUEST',
    UPDATE_DISTRIBUTETRANSFER_SUCCESS: 'UPDATE_DISTRIBUTETRANSFER_SUCCESS',
    UPDATE_DISTRIBUTETRANSFER_FAILURE: 'UPDATE_DISTRIBUTETRANSFER_FAILURE',
};