export const DistributeTransferConstants = {
    GET_DISTRIBUTE_TRANSFER_REQUEST: 'GET_DISTRIBUTE_TRANSFER_REQUEST',
    GET_DISTRIBUTE_TRANSFER_SUCCESS: 'GET_DISTRIBUTE_TRANSFER_SUCCESS',
    GET_DISTRIBUTE_TRANSFER_FAILURE: 'GET_DISTRIBUTE_TRANSFER_FAILURE',

    CREATE_DISTRIBUTE_TRANSFER_REQUEST: 'CREATE_NEW_DISTRIBUTE_TRANSFER_REQUEST',
    CREATE_DISTRIBUTE_TRANSFER_SUCCESS: 'CREATE_NEW_DISTRIBUTE_TRANSFER_SUCCESS',
    CREATE_DISTRIBUTE_TRANSFER_FAILURE: 'CREATE_NEW_DISTRIBUTE_TRANSFER_FAILURE',

    DELETE_DISTRIBUTE_TRANSFER_REQUEST: 'DELETE_DISTRIBUTE_TRANSFER_REQUEST',
    DELETE_DISTRIBUTE_TRANSFER_SUCCESS: 'DELETE_DISTRIBUTE_TRANSFER_SUCCESS',
    DELETE_DISTRIBUTE_TRANSFER_FAILURE: 'DELETE_DISTRIBUTE_TRANSFER_FAILURE',

    UPDATE_DISTRIBUTE_TRANSFER_REQUEST: 'UPDATE_DISTRIBUTE_TRANSFER_REQUEST',
    UPDATE_DISTRIBUTE_TRANSFER_SUCCESS: 'UPDATE_DISTRIBUTE_TRANSFER_SUCCESS',
    UPDATE_DISTRIBUTE_TRANSFER_FAILURE: 'UPDATE_DISTRIBUTE_TRANSFER_FAILURE',
};