export const DashboardUnitConstants = {
    GET_ALL_UNIT_DASHBOARD_DATA_REQUEST: 'GET_ALL_UNIT_DASHBOARD_DATA_REQUEST',
    GET_ALL_UNIT_DASHBOARD_DATA_SUCCESS: 'GET_ALL_UNIT_DASHBOARD_DATA_SUCCESS',
    GET_ALL_UNIT_DASHBOARD_DATA_FAILURE: 'GET_ALL_UNIT_DASHBOARD_DATA_FAILURE',
}