export const CapacityConstant = {
  GET_CAPACITY_LIST_REQUEST: 'GET_CAPACITY_LIST_REQUEST',
  GET_CAPACITY_LIST_SUCCESS: 'GET_CAPACITY_LIST_SUCCESS',
  GET_CAPACITY_LIST_FAILURE: 'GET_CAPACITY_LIST_FAILURE',
}
