export const CapacityConstant = {
  GET_CAPACITY_LIST_REQUEST: 'GET_CAPACITY_LIST_REQUEST',
  GET_CAPACITY_LIST_SUCCESS: 'GET_CAPACITY_LIST_SUCCESS',
  GET_CAPACITY_LIST_FAILURE: 'GET_CAPACITY_LIST_FAILURE',

  ADD_CAPACITY_REQUEST: 'ADD_CAPACITY_REQUEST',
  ADD_CAPACITY_SUCCESS: 'ADD_CAPACITY_SUCCESS',
  ADD_CAPACITY_FAILURE: 'ADD_CAPACITY_FAILURE',

  EDIT_CAPACITY_REQUEST: 'EDIT_CAPACITY_REQUEST',
  EDIT_CAPACITY_SUCCESS: 'EDIT_CAPACITY_SUCCESS',
  EDIT_CAPACITY_FAILURE: 'EDIT_CAPACITY_FAILURE',

  DELETE_CAPACITY_REQUEST: 'DELETE_CAPACITY_REQUEST',
  DELETE_CAPACITY_SUCCESS: 'DELETE_CAPACITY_SUCCESS',
  DELETE_CAPACITY_FAILURE: 'DELETE_CAPACITY_FAILURE',
}
