export const StatisticConstants = {
  GET_LIST_TASKS_EVAL: 'GET_LIST_TASKS_EVAL',
  GET_LIST_TASKS_EVAL_SUCCESS: 'GET_LIST_TASKS_EVAL_SUCCESS',
  GET_LIST_TASKS_EVAL_FAILE: 'GET_LIST_TASKS_EVAL_FAILE'
}
