export const RecommendDistributeConstants = {
  GET_RECOMMEND_DISTRIBUTE_REQUEST: 'GET_RECOMMEND_DISTRIBUTE_REQUEST',
  GET_RECOMMEND_DISTRIBUTE_SUCCESS: 'GET_RECOMMEND_DISTRIBUTE_SUCCESS',
  GET_RECOMMEND_DISTRIBUTE_FAILURE: 'GET_RECOMMEND_DISTRIBUTE_FAILURE',

  UPDATE_RECOMMEND_DISTRIBUTE_REQUEST: 'UPDATE_RECOMMEND_DISTRIBUTE_REQUEST',
  UPDATE_RECOMMEND_DISTRIBUTE_SUCCESS: 'UPDATE_RECOMMEND_DISTRIBUTE_SUCCESS',
  UPDATE_RECOMMEND_DISTRIBUTE_FAILURE: 'UPDATE_RECOMMEND_DISTRIBUTE_FAILURE',

  DELETE_RECOMMEND_DISTRIBUTE_REQUEST: 'DELETE_RECOMMEND_DISTRIBUTE_REQUEST',
  DELETE_RECOMMEND_DISTRIBUTE_SUCCESS: 'DELETE_RECOMMEND_DISTRIBUTE_SUCCESS',
  DELETE_RECOMMEND_DISTRIBUTE_FAILURE: 'DELETE_RECOMMEND_DISTRIBUTE_FAILURE',

  CREATE_USAGE_REQUEST: 'CREATE_NEW_USAGE_REQUEST',
  CREATE_USAGE_SUCCESS: 'CREATE_NEW_USAGE_SUCCESS',
  CREATE_USAGE_FAILURE: 'CREATE_NEW_USAGE_FAILURE',

  UPDATE_USAGE_REQUEST: 'UPDATE_USAGE_REQUEST',
  UPDATE_USAGE_SUCCESS: 'UPDATE_USAGE_SUCCESS',
  UPDATE_USAGE_FAILURE: 'UPDATE_USAGE_FAILURE',

  DELETE_USAGE_REQUEST: 'DELETE_USAGE_REQUEST',
  DELETE_USAGE_SUCCESS: 'DELETE_USAGE_SUCCESS',
  DELETE_USAGE_FAILURE: 'DELETE_USAGE_FAILURE',

  RECALL_ASSET_REQUEST: 'RECALL_ASSET_REQUEST',
  RECALL_ASSET_SUCCESS: 'RECALL_ASSET_SUCCESS',
  RECALL_ASSET_FAILURE: 'RECALL_ASSET_FAILURE'
}
