export const PrivilegeApiContants = {
    CREATE_PRIVILEGE_API_REQUEST: 'CREATE_PRIVILEGE_API_REQUEST',
    CREATE_PRIVILEGE_API_SUCCESS: 'CREATE_PRIVILEGE_API_SUCCESS',
    CREATE_PRIVILEGE_API_FAILURE: 'CREATE_PRIVILEGE_API_FAILURE',

    GET_PRIVILEGE_API_REQUEST: 'GET_PRIVILEGE_API_REQUEST',
    GET_PRIVILEGE_API_SUCCESS: 'GET_PRIVILEGE_API_SUCCESS',
    GET_PRIVILEGE_API_FAILURE: 'GET_PRIVILEGE_API_FAILURE',
}