export const SchedulingProjectsConstants = {
    ADD_PROJECT_TASKS_CPM: 'ADD_PROJECT_TASKS_CPM',
    ADD_PROJECT_TASKS_CPM_SUCCESS: 'ADD_PROJECT_TASKS_CPM_SUCCESS',
    ADD_PROJECT_TASKS_CPM_FAILE: 'ADD_PROJECT_TASKS_CPM_FAILE',
}