export const SchedulingProjectsConstants = {
    ADD_PROJECT_TASKS_CPM: 'ADD_PROJECT_TASKS_CPM',
    ADD_PROJECT_TASKS_CPM_SUCCESS: 'ADD_PROJECT_TASKS_CPM_SUCCESS',
    ADD_PROJECT_TASKS_CPM_FAIL: 'ADD_PROJECT_TASKS_CPM_FAIL',
    ADD_PROJECT_PHASE_CPM: 'ADD_PROJECT_PHASE_CPM',
    ADD_PROJECT_PHASE_CPM_SUCCESS: 'ADD_PROJECT_PHASE_CPM_SUCCESS',
    ADD_PROJECT_PHASE_CPM_FAIL: 'ADD_PROJECT_PHASE_CPM_FAIL',
}