export const ExternalServiceConsumerConstants = {
    CREATE_EXTERNAL_SERVICE_CONSUMER_REQUEST: 'CREATE_EXTERNAL_SERVICE_CONSUMER_REQUEST',
    CREATE_EXTERNAL_SERVICE_CONSUMER_SUCCESS: 'CREATE_EXTERNAL_SERVICE_CONSUMER_SUCCESS',
    CREATE_EXTERNAL_SERVICE_CONSUMER_FAILURE: 'CREATE_EXTERNAL_SERVICE_CONSUMER_FAILURE',
    
    GET_EXTERNAL_SERVICE_CONSUMER_REQUEST: 'GET_EXTERNAL_SERVICE_CONSUMER_REQUEST',
    GET_EXTERNAL_SERVICE_CONSUMER_SUCCESS: 'GET_EXTERNAL_SERVICE_CONSUMER_SUCCESS',
    GET_EXTERNAL_SERVICE_CONSUMER_FAILURE: 'GET_EXTERNAL_SERVICE_CONSUMER_FAILURE',

    EDIT_EXTERNAL_SERVICE_CONSUMER_REQUEST: 'EDIT_EXTERNAL_SERVICE_CONSUMER_REQUEST',
    EDIT_EXTERNAL_SERVICE_CONSUMER_SUCCESS: 'EDIT_EXTERNAL_SERVICE_CONSUMER_SUCCESS',
    EDIT_EXTERNAL_SERVICE_CONSUMER_FAILURE: 'EDIT_EXTERNAL_SERVICE_CONSUMER_FAILURE',

    DELETE_EXTERNAL_SERVICE_CONSUMER_REQUEST: 'DELETE_EXTERNAL_SERVICE_CONSUMER_REQUEST',
    DELETE_EXTERNAL_SERVICE_CONSUMER_SUCCESS: 'DELETE_EXTERNAL_SERVICE_CONSUMER_SUCCESS',
    DELETE_EXTERNAL_SERVICE_CONSUMER_FAILURE: 'DELETE_EXTERNAL_SERVICE_CONSUMER_FAILURE',

}