export const NotificationConstants = {
    GET_NOTIFICATIONS_REQUEST: 'GET_NOTIFICATIONS_REQUEST',
    GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
    GET_NOTIFICATIONS_FAILE: 'GET_NOTIFICATIONS_FAILE',

    GET_NOTIFICATIONS_RECEIVERED_REQUEST: 'GET_NOTIFICATIONS_RECEIVERED_REQUEST',
    GET_NOTIFICATIONS_RECEIVERED_SUCCESS: 'GET_NOTIFICATIONS_RECEIVERED_SUCCESS',
    GET_NOTIFICATIONS_RECEIVERED_FAILE: 'GET_NOTIFICATIONS_RECEIVERED_FAILE',

    GET_NOTIFICATIONS_SENT_REQUEST: 'GET_NOTIFICATIONS_SENT_REQUEST',
    GET_NOTIFICATIONS_SENT_SUCCESS: 'GET_NOTIFICATIONS_SENT_SUCCESS',
    GET_NOTIFICATIONS_SENT_FAILE: 'GET_NOTIFICATIONS_SENT_FAILE',

    CREATE_NOTIFICATION_REQUEST: 'CREATE_NOTIFICATION_REQUEST',
    CREATE_NOTIFICATION_SUCCESS: 'CREATE_NOTIFICATION_SUCCESS',
    CREATE_NOTIFICATION_FAILE: 'CREATE_NOTIFICATION_FAILE',
}