export const EducationConstants = {
  GET_LISTEDUCATION_REQUEST: 'GET_LIST_EDUCATION_REQUEST',
  GET_LISTEDUCATION_SUCCESS: 'GET_LIST_EDUCATION_SUCCESS',
  GET_LISTEDUCATION_FAILURE: 'GET_LIST_EDUCATION_FAILURE',

  CREATE_EDUCATION_REQUEST: 'CREATE_NEW_EDUCATION_REQUEST',
  CREATE_EDUCATION_SUCCESS: 'CREATE_NEW_EDUCATION_SUCCESS',
  CREATE_EDUCATION_FAILURE: 'CREATE_NEW_EDUCATION_FAILURE',

  DELETE_EDUCATION_REQUEST: 'DELETE_EDUCATION_REQUEST',
  DELETE_EDUCATION_SUCCESS: 'DELETE_EDUCATION_SUCCESS',
  DELETE_EDUCATION_FAILURE: 'DELETE_EDUCATION_FAILURE',

  UPDATE_EDUCATION_REQUEST: 'UPDATE_EDUCATION_REQUEST',
  UPDATE_EDUCATION_SUCCESS: 'UPDATE_EDUCATION_SUCCESS',
  UPDATE_EDUCATION_FAILURE: 'UPDATE_EDUCATION_FAILURE'
}
