export const InternalPolicyConstants = {
  CREATE_INTERNAL_POLICY_REQUEST: 'CREATE_INTERNAL_POLICY_REQUEST',
  CREATE_INTERNAL_POLICY_SUCCESS: 'CREATE_INTERNAL_POLICY_SUCCESS',
  CREATE_INTERNAL_POLICY_FAILURE: 'CREATE_INTERNAL_POLICY_FAILURE',

  GET_INTERNAL_POLICY_REQUEST: 'GET_INTERNAL_POLICY_REQUEST',
  GET_INTERNAL_POLICY_SUCCESS: 'GET_INTERNAL_POLICY_SUCCESS',
  GET_INTERNAL_POLICY_FAILURE: 'GET_INTERNAL_POLICY_FAILURE',

  UPDATE_AUTO_INTERNAL_POLICY_REQUEST: 'UPDATE_AUTO_INTERNAL_POLICY_REQUEST',
  UPDATE_AUTO_INTERNAL_POLICY_SUCCESS: 'UPDATE_AUTO_INTERNAL_POLICY_SUCCESS',
  UPDATE_AUTO_INTERNAL_POLICY_FAILURE: 'UPDATE_AUTO_INTERNAL_POLICY_FAILURE',

  EDIT_INTERNAL_POLICY_REQUEST: 'EDIT_INTERNAL_POLICY_REQUEST',
  EDIT_INTERNAL_POLICY_SUCCESS: 'EDIT_INTERNAL_POLICY_SUCCESS',
  EDIT_INTERNAL_POLICY_FAILURE: 'EDIT_INTERNAL_POLICY_FAILURE',

  DELETE_INTERNAL_POLICY_REQUEST: 'DELETE_INTERNAL_POLICY_REQUEST',
  DELETE_INTERNAL_POLICY_SUCCESS: 'DELETE_INTERNAL_POLICY_SUCCESS',
  DELETE_INTERNAL_POLICY_FAILURE: 'DELETE_INTERNAL_POLICY_FAILURE'
}
