export const ApiRegistrationConstants = {
    REGISTER_TO_USE_API_REQUEST: 'REGISTER_TO_USE_API_REQUEST',
    REGISTER_TO_USE_API_SUCCESS: 'REGISTER_TO_USE_API_SUCCESS',
    REGISTER_TO_USE_API_FAILURE: 'REGISTER_TO_USE_API_FAILURE',

    GET_API_REGISTRATION_REQUEST: 'GET_API_REGISTRATION_REQUEST',
    GET_API_REGISTRATION_SUCCESS: 'GET_API_REGISTRATION_SUCCESS',
    GET_API_REGISTRATION_FAILURE: 'GET_API_REGISTRATION_FAILURE',
}