export const kpiMemberConstants = {
    GETALL_KPIMEMBER_OfUNIT_REQUEST: 'GETALL_KPIMEMBER_OfUNIT_REQUEST',
    GETALL_KPIMEMBER_OfUNIT_SUCCESS: 'GETALL_KPIMEMBER_OfUNIT_SUCCESS',
    GETALL_KPIMEMBER_OfUNIT_FAILURE: 'GETALL_KPIMEMBER_OfUNIT_FAILURE',
    
    GETALL_KPIMEMBER_REQUEST: 'GETALL_KPIMEMBER_REQUEST',
    GETALL_KPIMEMBER_SUCCESS: 'GETALL_KPIMEMBER_SUCCESS',
    GETALL_KPIMEMBER_FAILURE: 'GETALL_KPIMEMBER_FAILURE',

    GET_KPIMEMBER_BYMONTH_REQUEST: 'GET_KPIMEMBER_BYMONTH_REQUEST',
    GET_KPIMEMBER_BYMONTH_SUCCESS: 'GET_KPIMEMBER_BYMONTH_SUCCESS',
    GET_KPIMEMBER_BYMONTH_FAILURE: 'GET_KPIMEMBER_BYMONTH_FAILURE',
    
    GET_KPIMEMBER_BYID_REQUEST: 'GET_KPIMEMBER_BYID_REQUEST',
    GET_KPIMEMBER_BYID_SUCCESS: 'GET_KPIMEMBER_BYID_SUCCESS',
    GET_KPIMEMBER_BYID_FAILURE: 'GET_KPIMEMBER_BYID_FAILURE',

    APPROVE_KPIMEMBER_REQUEST: 'APPROVE_KPIMEMBER_REQUEST',
    APPROVE_KPIMEMBER_SUCCESS: 'APPROVE_KPIMEMBER_SUCCESS',
    APPROVE_KPIMEMBER_FAILURE: 'APPROVE_KPIMEMBER_FAILURE',

    EDITTARGET_KPIMEMBER_REQUEST: 'EDITTARGET_KPIMEMBER_REQUEST',
    EDITTARGET_KPIMEMBER_SUCCESS: 'EDITTARGET_KPIMEMBER_SUCCESS',
    EDITTARGET_KPIMEMBER_FAILURE: 'EDITTARGET_KPIMEMBER_FAILURE',

    EDITSTATUS_TARGET_KPIMEMBER_REQUEST: 'EDITSTATUS_TARGET_KPIMEMBER_REQUEST',
    EDITSTATUS_TARGET_KPIMEMBER_SUCCESS: 'EDITSTATUS_TARGET_KPIMEMBER_SUCCESS',
    EDITSTATUS_TARGET_KPIMEMBER_FAILURE: 'EDITSTATUS_TARGET_KPIMEMBER_FAILURE',

    GET_TASK_BYID_REQUEST: 'GET_TASK_BYID_REQUEST',
    GET_TASK_BYID_SUCCESS: 'GET_TASK_BYID_SUCCESS',
    GET_TASK_BYID_FAILURE: 'GET_TASK_BYID_FAILURE',

    SET_POINTKPI_REQUEST: 'SET_POINTKPI_REQUEST',
    SET_POINTKPI_SUCCESS: 'SET_POINTKPI_SUCCESS',
    SET_POINTKPI_FAILURE: 'SET_POINTKPI_FAILURE',


}