export const NotificationConstants = {
    GET_MANUAL_NOTIFICATIONS_REQUEST: 'GET_MANUAL_NOTIFICATIONS_REQUEST',
    GET_MANUAL_NOTIFICATIONS_SUCCESS: 'GET_MANUAL_NOTIFICATIONS_SUCCESS',
    GET_MANUAL_NOTIFICATIONS_FAILE: 'GET_MANUAL_NOTIFICATIONS_FAILE',

    GET_NOTIFICATIONS_REQUEST: 'GET_NOTIFICATIONS_REQUEST',
    GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
    GET_NOTIFICATIONS_FAILE: 'GET_NOTIFICATIONS_FAILE',

    CREATE_NOTIFICATION_REQUEST: 'CREATE_NOTIFICATION_REQUEST',
    CREATE_NOTIFICATION_SUCCESS: 'CREATE_NOTIFICATION_SUCCESS',
    CREATE_NOTIFICATION_FAILE: 'CREATE_NOTIFICATION_FAILE',

    READED_NOTIFICATION_REQUEST: 'READED_NOTIFICATION_REQUEST',
    READED_NOTIFICATION_SUCCESS: 'READED_NOTIFICATION_SUCCESS',
    READED_NOTIFICATION_FAILE: 'READED_NOTIFICATION_FAILE',

}