export const NotificationConstants = {
    GET_NOTIFICATIONS_RECEIVERED_REQUEST: 'GET_NOTIFICATIONS_RECEIVERED_REQUEST',
    GET_NOTIFICATIONS_RECEIVERED_SUCCESS: 'GET_NOTIFICATIONS_RECEIVERED_SUCCESS',
    GET_NOTIFICATIONS_RECEIVERED_FAILE: 'GET_NOTIFICATIONS_RECEIVERED_FAILE',

    GET_NOTIFICATIONS_SENT_REQUEST: 'GET_NOTIFICATIONS_SENT_REQUEST',
    GET_NOTIFICATIONS_SENT_SUCCESS: 'GET_NOTIFICATIONS_SENT_SUCCESS',
    GET_NOTIFICATIONS_SENT_FAILE: 'GET_NOTIFICATIONS_SENT_FAILE',

    CREATE_NOTIFICATION_REQUEST: 'CREATE_NOTIFICATION_REQUEST',
    CREATE_NOTIFICATION_SUCCESS: 'CREATE_NOTIFICATION_SUCCESS',
    CREATE_NOTIFICATION_FAILE: 'CREATE_NOTIFICATION_FAILE',

    DELETE_NOTIFICATION_RECEIVERED_REQUEST: 'DELETE_NOTIFICATION_RECEIVERED_REQUEST',
    DELETE_NOTIFICATION_RECEIVERED_SUCCESS: 'DELETE_NOTIFICATION_RECEIVERED_SUCCESS',
    DELETE_NOTIFICATION_RECEIVERED_FAILE: 'DELETE_NOTIFICATION_RECEIVERED_FAILE',

    DELETE_NOTIFICATION_SENT_REQUEST: 'DELETE_NOTIFICATION_SENT_REQUEST',
    DELETE_NOTIFICATION_SENT_SUCCESS: 'DELETE_NOTIFICATION_SENT_SUCCESS',
    DELETE_NOTIFICATION_SENT_FAILE: 'DELETE_NOTIFICATION_SENT_FAILE',
}