export const TransportationCostManagementConstants = {
    GET_ALL_VEHICLE_COST_REQUEST: "GET_ALL_VEHICLE_COST_REQUEST",
    GET_ALL_VEHICLE_COST_SUCCESS: "GET_ALL_VEHICLE_COST_SUCCESS",
    GET_ALL_VEHICLE_COST_FAILURE: "GET_ALL_VEHICLE_COST_FAILURE",

    CREATE_VEHICLE_COST_REQUEST: "CREATE_VEHICLE_COST_REQUEST",
    CREATE_VEHICLE_COST_SUCCESS: "CREATE_VEHICLE_COST_SUCCESS",
    CREATE_VEHICLE_COST_FAILURE: "CREATE_VEHICLE_COST_FAILURE",

    UPDATE_VEHICLE_COST_REQUEST: "UPDATE_VEHICLE_COST_REQUEST",
    UPDATE_VEHICLE_COST_SUCCESS: "UPDATE_VEHICLE_COST_SUCCESS",
    UPDATE_VEHICLE_COST_FAILURE: "UPDATE_VEHICLE_COST_FAILURE",

    GET_COST_FORMULA_REQUEST: "GET_COST_FORMULA_REQUEST",
    GET_COST_FORMULA_SUCCESS: "GET_COST_FORMULA_SUCCESS",
    GET_COST_FORMULA_FAILURE: "GET_COST_FORMULA_FAILURE",

    CREATE_COST_FORMULA_REQUEST: "CREATE_COST_FORMULA_REQUEST",
    CREATE_COST_FORMULA_SUCCESS: "CREATE_COST_FORMULA_SUCCESS",
    CREATE_COST_FORMULA_FAILURE: "CREATE_COST_FORMULA_FAILURE",

    DELETE_VEHICLE_COST_REQUEST: 'DELETE_VEHICLE_COST_REQUEST',
    DELETE_VEHICLE_COST_SUCCESS: 'DELETE_VEHICLE_COST_SUCCESS',
    DELETE_VEHICLE_COST_FAILURE: 'DELETE_VEHICLE_COST_FAILURE',

    CREATE_CREATE_OR_UPDATE_COST_REQUEST: "CREATE_CREATE_OR_UPDATE_COST_REQUEST",
    CREATE_CREATE_OR_UPDATE_COST_SUCCESS: "CREATE_CREATE_OR_UPDATE_COST_SUCCESS",
    CREATE_CREATE_OR_UPDATE_COST_FAILURE: "CREATE_CREATE_OR_UPDATE_COST_FAILURE",

    GET_ALL_SHIPPER_COST_REQUEST: "GET_ALL_SHIPPER_COST_REQUEST",
    GET_ALL_SHIPPER_COST_SUCCESS: "GET_ALL_SHIPPER_COST_SUCCESS",
    GET_ALL_SHIPPER_COST_FAILURE: "GET_ALL_SHIPPER_COST_FAILURE",

    CALCULATE_SHIPPER_COST_REQUEST: "CALCULATE_SHIPPER_COST_REQUEST",
    CALCULATE_SHIPPER_COST_SUCCESS: "CALCULATE_SHIPPER_COST_SUCCESS",
    CALCULATE_SHIPPER_COST_FAILURE: "CALCULATE_SHIPPER_COST_FAILURE",
}