export const ManufacturingProcessConstants = {
    GET_ALL_MANUFACTURE_PROCESS_REQUEST: "GET_ALL_MANUFACTURE_PROCESS_REQUEST",
    GET_ALL_MANUFACTURE_PROCESS_SUCCESS: "GET_ALL_MANUFACTURE_PROCESS_SUCCESS",
    GET_ALL_MANUFACTURE_PROCESS_FAILURE: "GET_ALL_MANUFACTURE_PROCESS_FAILURE",

    GET_MANUFACTURE_PROCESS_BY_ID_REQUEST: "GET_MANUFACTURE_PROCESS_BY_ID_REQUEST",
    GET_MANUFACTURE_PROCESS_BY_ID_SUCCESS: "GET_MANUFACTURE_PROCESS_BY_ID_SUCCESS",
    GET_MANUFACTURE_PROCESS__BY_ID_FAILURE: "GET_MANUFACTURE_PROCESS_BY_ID_FAILURE",

    CREATE_MANUFACTURE_PROCESS_REQUEST: "CREATE_MANUFACTURE_PROCESS_REQUEST",
    CREATE_MANUFACTURE_PROCESS_SUCCESS: "CREATE_MANUFACTURE_PROCESS_SUCCESS",
    CREATE_MANUFACTURE_PROCESS_FAILURE: "CREATR_MANUFACTURE_PROCESS_FAILURE",

    EDIT_MANUFACTURE_PROCESS_REQUEST: "EDIT_MANUFACTURE_PROCESS_REQUEST",
    EDIT_MANUFACTURE_PROCESS_SUCCESS: "EDIT_MANUFACTURE_PROCESS_SUCCESS",
    EDIT_MANUFACTURE_PROCESS_FAILURE: "EDIT_MANUFACTURE_PROCESS_FAILURE",

    DELETE_MANUFACTURE_PROCESS_REQUEST: "DELETE_MANUFACTURE_PROCESS_REQUEST",
    DELETE_MANUFACTURE_PROCESS_SUCCESS: "DELETE_MANUFACTURE_PROCESS_SUCCESS",
    DELETE_MANUFACTURE_PROCESS_FAILURE: "DELETE_MANUFACTURE_PROCESS_FAILURE",
}