export const transportRequirementsConstants = {
    GET_ALL_TRANSPORT_REQUIREMENTS_REQUEST: "GET_ALL_TRANSPORT_REQUIREMENTS_REQUEST",
    GET_ALL_TRANSPORT_REQUIREMENTS_SUCCESS: "GET_ALL_TRANSPORT_REQUIREMENTS_SUCCESS",
    GET_ALL_TRANSPORT_REQUIREMENTS_FAILURE: "GET_ALL_TRANSPORT_REQUIREMENTS_FAILURE",

    CREATE_TRANSPORT_REQUIREMENT_REQUEST: "CREATE_TRANSPORT_REQUIREMENT_REQUEST",
    CREATE_TRANSPORT_REQUIREMENT_SUCCESS: "CREATE_TRANSPORT_REQUIREMENT_SUCCESS",
    CREATE_TRANSPORT_REQUIREMENT_FAILURE: "CREATE_TRANSPORT_REQUIREMENT_FAILURE",
}
