export const transportRequirementsConstants = {
    GET_ALL_TRANSPORT_REQUIREMENTS_REQUEST: "GET_ALL_TRANSPORT_REQUIREMENTS_REQUEST",
    GET_ALL_TRANSPORT_REQUIREMENTS_SUCCESS: "GET_ALL_TRANSPORT_REQUIREMENTS_SUCCESS",
    GET_ALL_TRANSPORT_REQUIREMENTS_FAILURE: "GET_ALL_TRANSPORT_REQUIREMENTS_FAILURE",
}
