export const forecastConstants = {
    CREATE_FORECAST_REQUEST: 'CREATE_FORECAST_REQUEST',
    CREATE_FORECAST_SUCCESS: 'CREATE_FORECAST_SUCCESS',
    CREATE_FORECAST_FAILURE: 'CREATE_FORECAST_FAILURE',
    GET_TOP5_PRODUCTS_REQUEST: 'GET_TOP5_PRODUCTS_REQUEST',
    GET_TOP5_PRODUCTS_SUCCESS: 'GET_TOP5_PRODUCTS_SUCCESS',
    GET_TOP5_PRODUCTS_FAILURE: 'GET_TOP5_PRODUCTS_FAILURE',
    GET_BOTTOM5_PRODUCTS_REQUEST: 'GET_BOTTOM5_PRODUCTS_REQUEST',
    GET_BOTTOM5_PRODUCTS_SUCCESS: 'GET_BOTTOM5_PRODUCTS_SUCCESS',
    GET_BOTTOM5_PRODUCTS_FAILURE: 'GET_BOTTOM5_PRODUCTS_FAILURE',
    GET_ALL_FORECASTS_REQUEST: 'GET_ALL_FORECASTS_REQUEST',
    GET_ALL_FORECASTS_SUCCESS: 'GET_ALL_FORECASTS_SUCCESS',
    GET_ALL_FORECASTS_FAILURE: 'GET_ALL_FORECASTS_FAILURE',
    GET_COUNT_FORECASTS_REQUEST: 'GET_COUNT_FORECASTS_REQUEST',
    GET_COUNT_FORECASTS_SUCCESS: 'GET_COUNT_FORECASTS_SUCCESS',
    GET_COUNT_FORECASTS_FAILURE: 'GET_COUNT_FORECASTS_FAILURE'
};
