export const forecastConstants = {
    GET_ALL_FORECASTS_REQUEST: "GET_ALL_FORECASTS_REQUEST",
    GET_ALL_FORECASTS_SUCCESS: "GET_ALL_FORECASTS_SUCCESS",
    GET_ALL_FORECASTS_FAILURE: "GET_ALL_FORECASTS_FAILURE",
};
