export const BillConstants = {

    GET_BILL_BY_TYPE_REQUEST: 'GET_BILL_BY_TYPE_REQUEST',
    GET_BILL_BY_TYPE_SUCCESS: 'GET_BILL_BY_TYPE_SUCCESS',
    GET_BILL_BY_TYPE_FAILURE: 'GET_BILL_BY_TYPE_FAILURE',

    GET_PAGINATE_REQUEST: 'GET_PAGINATE_REQUEST',
    GET_PAGINATE_SUCCESS: 'GET_PAGINATE_SUCCESS',
    GET_PAGINATE_FAILURE: 'GET_PAGINATE_FAILURE',

    GET_BILL_BY_GOOD_REQUEST: 'GET_BILL_BY_GOOD_REQUEST',
    GET_BILL_BY_GOOD_SUCCESS: 'GET_BILL_BY_GOOD_SUCCESS',
    GET_BILL_BY_GOOD_FAILURE: 'GET_BILL_BY_GOOD_FAILURE',

    GET_BILL_DETAIL_REQUEST: 'GET_BILL_DETAIL_REQUEST',
    GET_BILL_DETAIL_SUCCESS: 'GET_BILL_DETAIL_SUCCESS',
    GET_BILL_DETAIL_FAILURE: 'GET_BILL_DETAIL_FAILURE',
}