export const DocumentConstants = {
    // Administration
    GET_DOCUMENT_TYPES_REQUEST: 'GET_DOCUMENT_TYPES_REQUEST',
    GET_DOCUMENT_TYPES_SUCCESS: 'GET_DOCUMENT_TYPES_SUCCESS',
    GET_DOCUMENT_TYPES_FAILE: 'GET_DOCUMENT_TYPES_FAILE',

    CREATE_DOCUMENT_TYPE_REQUEST: 'CREATE_DOCUMENT_TYPE_REQUEST',
    CREATE_DOCUMENT_TYPE_SUCCESS: 'CREATE_DOCUMENT_TYPE_SUCCESS',
    CREATE_DOCUMENT_TYPE_FAILE: 'CREATE_DOCUMENT_TYPE_FAILE',

    // User
}