export const DocumentConstants = {
    // Administration
    GET_DOCUMENTS_REQUEST: 'GET_DOCUMENTS_REQUEST',
    GET_DOCUMENTS_SUCCESS: 'GET_DOCUMENTS_SUCCESS',
    GET_DOCUMENTS_FAILE: 'GET_DOCUMENTS_FAILE',

    CREATE_DOCUMENT_REQUEST: 'CREATE_DOCUMENT_REQUEST',
    CREATE_DOCUMENT_SUCCESS: 'CREATE_DOCUMENT_SUCCESS',
    CREATE_DOCUMENT_FAILE: 'CREATE_DOCUMENT_FAILE',

    EDIT_DOCUMENT_REQUEST: 'EDIT_DOCUMENT_REQUEST',
    EDIT_DOCUMENT_SUCCESS: 'EDIT_DOCUMENT_SUCCESS',
    EDIT_DOCUMENT_FAILE: 'EDIT_DOCUMENT_FAILE',

    
    DOWNLOAD_DOCUMENT_FILE_REQUEST: 'DOWNLOAD_DOCUMENT_FILE_REQUEST',
    DOWNLOAD_DOCUMENT_FILE_SUCCESS: 'DOWNLOAD_DOCUMENT_FILE_SUCCESS',
    DOWNLOAD_DOCUMENT_FILE_FAILE: 'DOWNLOAD_DOCUMENT_FILE_FAILE',

    GET_DOCUMENT_CATEGORIES_REQUEST: 'GET_DOCUMENT_CATEGORIES_REQUEST',
    GET_DOCUMENT_CATEGORIES_SUCCESS: 'GET_DOCUMENT_CATEGORIES_SUCCESS',
    GET_DOCUMENT_CATEGORIES_FAILE: 'GET_DOCUMENT_CATEGORIES_FAILE',

    CREATE_DOCUMENT_CATEGORY_REQUEST: 'CREATE_DOCUMENT_CATEGORY_REQUEST',
    CREATE_DOCUMENT_CATEGORY_SUCCESS: 'CREATE_DOCUMENT_CATEGORY_SUCCESS',
    CREATE_DOCUMENT_CATEGORY_FAILE: 'CREATE_DOCUMENT_CATEGORY_FAILE',

    GET_DOCUMENT_DOMAINS_REQUEST: 'GET_DOCUMENT_DOMAINS_REQUEST',
    GET_DOCUMENT_DOMAINS_SUCCESS: 'GET_DOCUMENT_DOMAINS_SUCCESS',
    GET_DOCUMENT_DOMAINS_FAILE: 'GET_DOCUMENT_DOMAINS_FAILE',

    CREATE_DOCUMENT_DOMAIN_REQUEST: 'CREATE_DOCUMENT_DOMAIN_REQUEST',
    CREATE_DOCUMENT_DOMAIN_SUCCESS: 'CREATE_DOCUMENT_DOMAIN_SUCCESS',
    CREATE_DOCUMENT_DOMAIN_FAILE: 'CREATE_DOCUMENT_DOMAIN_FAILE',

    // User
}