export const homeConstants = {
    GET_NEWSFEED_REQUEST: 'GET_NEWSFEED_REQUEST',
    GET_NEWSFEED_SUCCESS: 'GET_NEWSFEED_SUCCESS',
    GET_NEWSFEED_FAILURE: 'GET_NEWSFEED_FAILURE',

    RECEIVE_NEWSFEED_SUCCESS: 'RECEIVE_NEWSFEED_SUCCESS'
}