export const JourneyConstants = {
    GET_ALL_JOURNEYS_REQUEST: "GET_ALL_JOURNEYS_REQUEST",
    GET_ALL_JOURNEYS_SUCCESS: "GET_ALL_JOURNEYS_SUCCESS",
    GET_ALL_JOURNEYS_FAILURE: "GET_ALL_JOURNEYS_FAILURE",

    GET_COST_OF_ALL_JOURNEYS_REQUEST: "GET_COST_OF_ALL_JOURNEYS_REQUEST",
    GET_COST_OF_ALL_JOURNEYS_SUCCESS: "GET_COST_OF_ALL_JOURNEYS_SUCCESS",
    GET_COST_OF_ALL_JOURNEYS_FAILURE: "GET_COST_OF_ALL_JOURNEYS_FAILURE",

    DELETE_JOURNEY_REQUEST: "DELETE_DELETE_JOURNEY_REQUEST",
    DELETE_JOURNEY_SUCCESS: "DELETE_JOURNEY_SUCCESS",
    DELETE_JOURNEY_FAILURE: "DELETE_JOURNEY_FAILURE",

    CREATE_JOURNEY_REQUEST: "CREATE_JOURNEY_REQUEST",
    CREATE_JOURNEY_SUCCESS: "CREATE_JOURNEY_SUCCESS",
    CREATE_JOURNEY_FAILURE: "CREATE_JOURNEY_FAILURE",

    EDIT_JOURNEY_REQUEST: "EDIT_JOURNEY_REQUEST",
    EDIT_JOURNEY_SUCCESS: "EDIT_JOURNEY_SUCCESS",
    EDIT_JOURNEY_FAILURE: "EDIT_JOURNEY_FAILURE",

    GET_DETAIL_JOURNEY_REQUEST: "GET_DETAIL_JOURNEY_REQUEST",
    GET_DETAIL_JOURNEY_SUCCESS: "GET_DETAIL_JOURNEY_SUCCESS",
    GET_DETAIL_JOURNEY_FAILURE: "GET_DETAIL_JOURNEY_FAILURE",

    REFRESH_JOURNEY_DATA: "REFRESH_JOURNEY_DATA"
}