export const employeeConstants = {
    GETALL_REQUEST: 'EMPLOYEE_GETALL_REQUEST',
    GETALL_SUCCESS: 'EMPLOYEE_GETALL_SUCCESS',
    GETALL_FAILURE: 'EMPLOYEE_GETALL_FAILURE',

    GETLIST_EMPLOYEE_REQUEST: 'EMPLOYEE_GET_LIST_EMPLOYEE_REQUEST',
    GETLIST_EMPLOYEE_SUCCESS: 'EMPLOYEE_GET_LIST_EMPLOYEE_SUCCESS',
    GETLIST_EMPLOYEE_FAILURE: 'EMPLOYEE_GET_LIST_EMPLOYEE_FAILURE',

};