export const EmployeeConstants = {
    GETALL_REQUEST: 'EMPLOYEE_GETALL_REQUEST',
    GETALL_SUCCESS: 'EMPLOYEE_GETALL_SUCCESS',
    GETALL_FAILURE: 'EMPLOYEE_GETALL_FAILURE',

    ADDEMPLOYEE_REQUEST: 'EMPLOYEE_ADDEMPLOYEE_REQUEST',
    ADDEMPLOYEE_SUCCESS: 'EMPLOYEE_ADDEMPLOYEE_SUCCESS',
    ADDEMPLOYEE_FAILURE: 'EMPLOYEE_ADDEMPLOYEE_FAILURE',

    UPDATE_INFOR_EMPLOYEE_REQUEST: 'EMPLOYEE_UPDATE_INFOR_EMPLOYEE_REQUEST',
    UPDATE_INFOR_EMPLOYEE_SUCCESS: 'EMPLOYEE_UPDATE_INFOR_EMPLOYEE_SUCCESS',
    UPDATE_INFOR_EMPLOYEE_FAILURE: 'EMPLOYEE_UPDATE_INFOR_EMPLOYEE_FAILURE',

    UPLOAD_AVATAR_REQUEST: "ULOAD_AVATAR_EMPLOYEE_REQUEST",
    UPLOAD_AVATAR_SUCCESS: "ULOAD_AVATAR_EMPLOYEE_SUCCESS",
    UPLOAD_AVATAR_FAILURE: "ULOAD_AVATAR_EMPLOYEE_FAILURE",

    UPDATE_CONTRACT_REQUEST: "UPDATE_CONTRACT_EMPLOYEE_REQUEST",
    UPDATE_CONTRACT_SUCCESS: "UPDATE_CONTRACT_EMPLOYEE_SUCCESS",
    UPDATE_CONTRACT_FAILURE: "UPDATE_CONTRACT_EMPLOYEE_FAILURE",

    UPDATE_CERTIFICATESHORT_REQUEST: "UPDATE_CERTIFICATESHORT_EMPLOYEE_REQUEST",
    UPDATE_CERTIFICATESHORT_SUCCESS: "UPDATE_CERTIFICATESHORT_EMPLOYEE_SUCCESS",
    UPDATE_CERTIFICATESHORT_FAILURE: "UPDATE_CERTIFICATESHORT_EMPLOYEE_FAILURE",

    UPDATE_CERTIFICATE_REQUEST: "UPDATE_CERTIFICATE_EMPLOYEE_REQUEST",
    UPDATE_CERTIFICATE_SUCCESS: "UPDATE_CERTIFICATE_EMPLOYEE_SUCCESS",
    UPDATE_CERTIFICATE_FAILURE: "UPDATE_CERTIFICATE_EMPLOYEE_FAILURE",

    UPDATE_FILE_REQUEST: "UPDATE_FILE_EMPLOYEE_REQUEST",
    UPDATE_FILE_SUCCESS: "UPDATE_FILE_EMPLOYEE_SUCCESS",
    UPDATE_FILE_FAILURE: "UPDATE_FILE_EMPLOYEE_FAILURE",

    CHECK_EMPLOYEENUMBER_REQUEST: "CHECK_EMPLOYEENUMBER_EMPLOYEE_REQUEST",
    CHECK_EMPLOYEENUMBER_SUCCESS: "CHECK_EMPLOYEENUMBER_EMPLOYEE_SUCCESS",
    CHECK_EMPLOYEENUMBER_FAILURE: "CHECK_EMPLOYEENUMBER_EMPLOYEE_FAILURE",

    CHECK_EMAILCOMPANY_REQUEST: "CHECK_EMAILCOMPANY_EMPLOYEE_REQUEST",
    CHECK_EMAILCOMPANY_SUCCESS: "CHECK_EMAILCOMPANY_EMPLOYEE_SUCCESS",
    CHECK_EMAILCOMPANY_FAILURE: "CHECK_EMAILCOMPANY_EMPLOYEE_FAILURE",

    DELETE_EMPLOYEE_REQUEST: 'DELETE_EMPLOYEE_REQUEST',
    DELETE_EMPLOYEE_SUCCESS: 'DELETE_EMPLOYEE_SUCCESS',
    DELETE_EMPLOYEE_FAILURE: 'DELETE_EMPLOYEE_FAILURE',

    CHECK_ARRAY_EMPLOYEENUMBER_REQUEST: "CHECK_ARRAY_EMPLOYEENUMBER_EMPLOYEE_REQUEST",
    CHECK_ARRAY_EMPLOYEENUMBER_SUCCESS: "CHECK_ARRAY_EMPLOYEENUMBER_EMPLOYEE_SUCCESS",
    CHECK_ARRAY_EMPLOYEENUMBER_FAILURE: "CHECK_ARRAY_EMPLOYEENUMBER_EMPLOYEE_FAILURE",

};