export const AssetTypeConstants = {
    GET_ASSET_TYPE_REQUEST: 'GET_ASSET_TYPE_REQUEST',
    GET_ASSET_TYPE_SUCCESS: 'GET_ASSET_TYPE_SUCCESS',
    GET_ASSET_TYPE_FAILURE: 'GET_ASSET_TYPE_FAILURE',

    CREATE_ASSET_TYPE_REQUEST: 'CREATE_NEW_ASSET_TYPE_REQUEST',
    CREATE_ASSET_TYPE_SUCCESS: 'CREATE_NEW_ASSET_TYPE_SUCCESS',
    CREATE_ASSET_TYPE_FAILURE: 'CREATE_NEW_ASSET_TYPE_FAILURE',

    DELETE_ASSET_TYPE_REQUEST: 'DELETE_ASSET_TYPE_REQUEST',
    DELETE_ASSET_TYPE_SUCCESS:  'DELETE_ASSET_TYPE_SUCCESS',
    DELETE_ASSETTYPE_FAILURE:  'DELETE_ASSET_TYPE_FAILURE',

    UPDATE_ASSET_TYPE_REQUEST: 'UPDATE_ASSET_TYPE_REQUEST',
    UPDATE_ASSET_TYPE_SUCCESS: 'UPDATE_ASSET_TYPE_SUCCESS',
    UPDATE_ASSET_TYPE_FAILURE: 'UPDATE_ASSET_TYPE_FAILURE',
}