export const AssetTypeConstants = {
    GET_ASSETTYPE_REQUEST: 'GET_ASSETTYPE_REQUEST',
    GET_ASSETTYPE_SUCCESS: 'GET_ASSETTYPE_SUCCESS',
    GET_ASSETTYPE_FAILURE: 'GET_ASSETTYPE_FAILURE',

    CREATE_ASSETTYPE_REQUEST: 'CREATE_NEW_ASSETTYPE_REQUEST',
    CREATE_ASSETTYPE_SUCCESS: 'CREATE_NEW_ASSETTYPE_SUCCESS',
    CREATE_ASSETTYPE_FAILURE: 'CREATE_NEW_ASSETTYPE_FAILURE',

    DELETE_ASSETTYPE_REQUEST: 'DELETE_ASSETTYPE_REQUEST',
    DELETE_ASSETTYPE_SUCCESS:  'DELETE_ASSETTYPE_SUCCESS',
    DELETE_ASSETTYPE_FAILURE:  'DELETE_ASSETTYPE_FAILURE',

    UPDATE_ASSETTYPE_REQUEST: 'UPDATE_ASSETTYPE_REQUEST',
    UPDATE_ASSETTYPE_SUCCESS: 'UPDATE_ASSETTYPE_SUCCESS',
    UPDATE_ASSETTYPE_FAILURE: 'UPDATE_ASSETTYPE_FAILURE',
}