export const CategoryConstants = {
    GETALL_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
    GETALL_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GETALL_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',

    PAGINATE_CATEGORY_REQUEST: 'PAGINATE_CATEGORY_REQUEST',
    PAGINATE_CATEGORY_SUCCESS: 'PAGINATE_CATEGORY_SUCCESS',
    PAGINATE_CATEGORY_FAILURE: 'PAGINATE_CATEGORY_FAILURE',

    GETALL_CATEGORY_BY_TYPE_REQUEST: 'GET_CATEGORY_BY_TYPE_REQUEST',
    GETALL_CATEGORY_BY_TYPE_SUCCESS: 'GET_CATEGORY_BY_TYPE_SUCCESS',
    GETALL_CATEGORY_BY_TYPE_FAILURE: 'GET_CATEGORY_BY_TYPE_FAILURE',

    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

    UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',

    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',
}