export const RootRoleConstants = {
  GET_ALL_ROOT_ROLE_REQUEST: 'GET_ALL_ROOT_ROLE_REQUEST',
  GET_ALL_ROOT_ROLE_SUCCESS: 'GET_ALL_ROOT_ROLE_SUCCESS',
  GET_ALL_ROOT_ROLE_FAILURE: 'GET_ALL_ROOT_ROLE_FAILURE'
}
