export const dashboardEmployeeKpiSetConstants = {
    
    GET_EMPLOYEE_KPI_SET_BY_MEMBER_REQUEST: 'GET_EMPLOYEE_KPI_SET_BY_MEMBER_REQUEST',
    GET_EMPLOYEE_KPI_SET_BY_MEMBER_SUCCESS: 'GET_EMPLOYEE_KPI_SET_BY_MEMBER_SUCCESS',
    GET_EMPLOYEE_KPI_SET_BY_MEMBER_FAILURE: 'GET_EMPLOYEE_KPI_SET_BY_MEMBER_FAILURE',
    
    GET_EMPLOYEE_KPI_SET_BY_ID_REQUEST: 'GET_EMPLOYEE_KPI_SET_BY_ID_REQUEST',
    GET_EMPLOYEE_KPI_SET_BY_ID_SUCCESS: 'GET_EMPLOYEE_KPI_SET_BY_ID_SUCCESS',
    GET_EMPLOYEE_KPI_SET_BY_ID_FAILURE: 'GET_EMPLOYEE_KPI_SET_BY_ID_FAILURE',

    GET_EMPLOYEE_KPI_SET_OF_TASK_REQUEST: 'GET_EMPLOYEE_KPI_SET_OF_TASK_REQUEST',
    GET_EMPLOYEE_KPI_SET_OF_TASK_SUCCESS: 'GET_EMPLOYEE_KPI_SET_OF_TASK_SUCCESS',
    GET_EMPLOYEE_KPI_SET_OF_TASK_FAILURE: 'GET_EMPLOYEE_KPI_SET_OF_TASK_FAILURE',
    
};