export const TaskPackageManagementConstants = {
  GET_TASK_PACKAGES_DATA: 'GET_TASK_PACKAGES_DATA',
  GET_TASK_PACKAGES_DATA_SUCCESS: 'GET_TASK_PACKAGES_DATA_SUCCESS',
  GET_TASK_PACKAGES_DATA_FAILED: 'GET_TASK_PACKAGES_DATA_FAILED',

  GET_TASK_TYPE_DATA: 'GET_TASK_TYPE_DATA',
  GET_TASK_TYPE_DATA_SUCCESS: 'GET_TASK_TYPE_DATA_SUCCESS',
  GET_TASK_TYPE_DATA_FAILED: 'GET_TASK_TYPE_DATA_FAILED',

  ADD_TASK_TYPE_DATA: 'ADD_TASK_TYPE_DATA',
  ADD_TASK_TYPE_DATA_SUCCESS: 'ADD_TASK_TYPE_DATA_SUCCESS',
  ADD_TASK_TYPE_DATA_FAILED: 'ADD_TASK_TYPE_DATA_FAILED',

  ADD_TASK_DATA: 'ADD_TASK_DATA',
  ADD_TASK_DATA_SUCCESS: 'ADD_TASK_DATA_SUCCESS',
  ADD_TASK_DATA_FAILED: 'ADD_TASK_DATA_FAILED'
}
