export const TaskPackageManagementConstants = {
  GET_TASK_PACKAGES_DATA: 'GET_TASK_PACKAGES_DATA',
  GET_TASK_PACKAGES_DATA_SUCCESS: 'GET_TASK_PACKAGES_DATA_SUCCESS',
  GET_TASK_PACKAGES_DATA_FAILED: 'GET_TASK_PACKAGES_DATA_FAILED'
}
