export const overviewKpiConstants = {
    
    GETALL_KPIPERSONAL_REQUEST: 'GETALL_KPIPERSONAL_REQUEST',
    GETALL_KPIPERSONAL_SUCCESS: 'GETALL_KPIPERSONAL_SUCCESS',
    GETALL_KPIPERSONAL_FAILURE: 'GETALL_KPIPERSONAL_FAILURE',
    
};