export const ExternalPolicyConstants = {
    CREATE_EXTERNAL_POLICY_REQUEST: 'CREATE_EXTERNAL_POLICY_REQUEST',
    CREATE_EXTERNAL_POLICY_SUCCESS: 'CREATE_EXTERNAL_POLICY_SUCCESS',
    CREATE_EXTERNAL_POLICY_FAILURE: 'CREATE_EXTERNAL_POLICY_FAILURE',
    
    GET_EXTERNAL_POLICY_REQUEST: 'GET_EXTERNAL_POLICY_REQUEST',
    GET_EXTERNAL_POLICY_SUCCESS: 'GET_EXTERNAL_POLICY_SUCCESS',
    GET_EXTERNAL_POLICY_FAILURE: 'GET_EXTERNAL_POLICY_FAILURE',

    UPDATE_AUTO_EXTERNAL_POLICY_REQUEST: 'UPDATE_AUTO_EXTERNAL_POLICY_REQUEST',
    UPDATE_AUTO_EXTERNAL_POLICY_SUCCESS: 'UPDATE_AUTO_EXTERNAL_POLICY_SUCCESS',
    UPDATE_AUTO_EXTERNAL_POLICY_FAILURE: 'UPDATE_AUTO_EXTERNAL_POLICY_FAILURE',

    EDIT_EXTERNAL_POLICY_REQUEST: 'EDIT_EXTERNAL_POLICY_REQUEST',
    EDIT_EXTERNAL_POLICY_SUCCESS: 'EDIT_EXTERNAL_POLICY_SUCCESS',
    EDIT_EXTERNAL_POLICY_FAILURE: 'EDIT_EXTERNAL_POLICY_FAILURE',

    DELETE_EXTERNAL_POLICY_REQUEST: 'DELETE_EXTERNAL_POLICY_REQUEST',
    DELETE_EXTERNAL_POLICY_SUCCESS: 'DELETE_EXTERNAL_POLICY_SUCCESS',
    DELETE_EXTERNAL_POLICY_FAILURE: 'DELETE_EXTERNAL_POLICY_FAILURE',

}