export const taskManagementConstants = {
    GETALL_TASK_REQUEST: 'GETALL_TASK_REQUEST',
    GETALL_TASK_SUCCESS: 'GETALL_TASK_SUCCESS',
    GETALL_TASK_FAILURE: 'GETALL_TASK_FAILURE',
    
    GETTASK_BYID_REQUEST: 'GETTASK_BYID_REQUEST',
    GETTASK_BYID_SUCCESS: 'GETTASK_BYID_SUCCESS',
    GETTASK_BYID_FAILURE: 'GETTASK_BYID_FAILURE',
    
    GETTASK_BYROLE_REQUEST: 'GETTASK_BYROLE_REQUEST',
    GETTASK_BYROLE_SUCCESS: 'GETTASK_BYROLE_SUCCESS',
    GETTASK_BYROLE_FAILURE: 'GETTASK_BYROLE_FAILURE',

    GETTASK_RESPONSIBLE_BYUSER_REQUEST: 'GETTASK_RESPONSIBLE_BYUSER_REQUEST',
    GETTASK_RESPONSIBLE_BYUSER_SUCCESS: 'GETTASK_RESPONSIBLE_BYUSER_SUCCESS',
    GETTASK_RESPONSIBLE_BYUSER_FAILURE: 'GETTASK_RESPONSIBLE_BYUSER_FAILURE',
    
    GETTASK_ACCOUNATABLE_BYUSER_REQUEST: 'GETTASK_ACCOUNATABLE_BYUSER_REQUEST',
    GETTASK_ACCOUNATABLE_BYUSER_SUCCESS: 'GETTASK_ACCOUNATABLE_BYUSER_SUCCESS',
    GETTASK_ACCOUNATABLE_BYUSER_FAILURE: 'GETTASK_ACCOUNATABLE_BYUSER_FAILURE',
    
    GETTASK_CONSULTED_BYUSER_REQUEST: 'GETTASK_CONSULTED_BYUSER_REQUEST',
    GETTASK_CONSULTED_BYUSER_SUCCESS: 'GETTASK_CONSULTED_BYUSER_SUCCESS',
    GETTASK_CONSULTED_BYUSER_FAILURE: 'GETTASK_CONSULTED_BYUSER_FAILURE',
    
    GETTASK_INFORMED_BYUSER_REQUEST: 'GETTASK_INFORMED_BYUSER_REQUEST',
    GETTASK_INFORMED_BYUSER_SUCCESS: 'GETTASK_INFORMED_BYUSER_SUCCESS',
    GETTASK_INFORMED_BYUSER_FAILURE: 'GETTASK_INFORMED_BYUSER_FAILURE',
    
    GETTASK_CREATOR_BYUSER_REQUEST: 'GETTASK_CREATOR_BYUSER_REQUEST',
    GETTASK_CREATOR_BYUSER_SUCCESS: 'GETTASK_CREATOR_BYUSER_SUCCESS',
    GETTASK_CREATOR_BYUSER_FAILURE: 'GETTASK_CREATOR_BYUSER_FAILURE',
    
    ADDNEW_TASK_REQUEST: 'ADD_TASK_REQUEST',
    ADDNEW_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADDNEW_TASK_FAILURE: 'ADD_TASK_FAILURE',
    
    EDIT_TASK_REQUEST: 'EDIT_TASK_REQUEST',
    EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
    EDIT_TASK_FAILURE: 'EDIT_TASK_FAILURE',
    
    DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAILURE: 'DELETE_TASK_FAILURE',
};