export const ComponentDefaultConstants = {
    GET_COMPONENTS_DEFAULT_REQUEST: 'GET_COMPONENTS_DEFAULT_REQUEST',
    GET_COMPONENTS_DEFAULT_SUCCESS: 'GET_COMPONENTS_DEFAULT_SUCCESS',
    GET_COMPONENTS_DEFAULT_FAILE: 'GET_COMPONENTS_DEFAULT_FAILE',

    GET_COMPONENTS_DEFAULT_PAGINATE_REQUEST: 'GET_COMPONENTS_DEFAULT_PAGINATE_REQUEST',
    GET_COMPONENTS_DEFAULT_PAGINATE_SUCCESS: 'GET_COMPONENTS_DEFAULT_PAGINATE_SUCCESS',
    GET_COMPONENTS_DEFAULT_PAGINATE_FAILE: 'GET_COMPONENTS_DEFAULT_PAGINATE_FAILE',

    SHOW_COMPONENT_DEFAULT_REQUEST: 'SHOW_COMPONENT_DEFAULT_REQUEST',
    SHOW_COMPONENT_DEFAULT_SUCCESS: 'SHOW_COMPONENT_DEFAULT_SUCCESS',
    SHOW_COMPONENT_DEFAULT_FAILE: 'SHOW_COMPONENT_DEFAULT_FAILE',

    CREATE_COMPONENT_DEFAULT_REQUEST: 'CREATE_COMPONENT_DEFAULT_REQUEST',
    CREATE_COMPONENT_DEFAULT_SUCCESS: 'CREATE_COMPONENT_DEFAULT_SUCCESS',
    CREATE_COMPONENT_DEFAULT_FAILE: 'CREATE_COMPONENT_DEFAULT_FAILE',

    EDIT_COMPONENT_DEFAULT_REQUEST: 'EDIT_COMPONENT_DEFAULT_REQUEST',
    EDIT_COMPONENT_DEFAULT_SUCCESS: 'EDIT_COMPONENT_DEFAULT_SUCCESS',
    EDIT_COMPONENT_DEFAULT_FAILE: 'EDIT_COMPONENT_DEFAULT_FAILE',

    DELETE_COMPONENT_DEFAULT_REQUEST: 'DELETE_COMPONENT_DEFAULT_REQUEST',
    DELETE_COMPONENT_DEFAULT_SUCCESS: 'DELETE_COMPONENT_DEFAULT_SUCCESS',
    DELETE_COMPONENT_DEFAULT_FAILE: 'DELETE_COMPONENT_DEFAULT_FAILE',
}