export const riskResponsePlanConstants ={
    
    GET_RISK_RESPONSE_PLAN_REQUEST: 'GET_RISK_RESPONSE_PLAN_REQUEST',
    GET_RISK_RESPONSE_PLAN_SUCCESS: 'GET_RISK_RESPONSE_PLAN_SUCCESS',
    GET_RISK_RESPONSE_PLAN_FAILURE: 'GET_RISK_RESPONSE_PLAN_FAILURE',

    EDIT_RISK_RESPONSE_PLAN_REQUEST: 'EDIT_RISK_RESPONSE_PLAN_REQUEST',
    EDIT_RISK_RESPONSE_PLAN_SUCCESS: 'EDIT_RISK_RESPONSE_PLAN_SUCCESS',
    EDIT_RISK_RESPONSE_PLAN_FAILURE: 'EDIT_RISK_RESPONSE_PLAN_FAILURE',

    CREATE_RISK_RESPONSE_PLAN_REQUEST: 'CREATE_RISK_RESPONSE_PLAN_REQUEST',
    CREATE_RISK_RESPONSE_PLAN_SUCCESS: 'CREATE_RISK_RESPONSE_PLAN_SUCCESS',
    CREATE_RISK_RESPONSE_PLAN_FAILURE: 'CREATE_RISK_RESPONSE_PLAN_FAILURE',

    DELETE_RISK_RESPONSE_PLAN_REQUEST: 'DELETE_RISK_RESPONSE_PLAN_REQUEST',
    DELETE_RISK_RESPONSE_PLAN_SUCCESS: 'DELETE_RISK_RESPONSE_PLAN_SUCCESS',
    DELETE_RISK_RESPONSE_PLAN_FAILURE: 'DELETE_RISK_RESPONSE_PLAN_FAILURE',

    GET_RISK_RESPONSE_PLAN_BY_ID_REQUEST: 'GET_RISK_RESPONSE_PLAN_BY_ID_REQUEST',
    GET_RISK_RESPONSE_PLAN_BY_ID_SUCCESS: 'GET_RISK_RESPONSE_PLAN_BY_ID_SUCCESS',
    GET_RISK_RESPONSE_PLAN_BY_ID_FAILURE: 'GET_RISK_RESPONSE_PLAN_BY_ID_FAILURE',
    
    GET_RISK_RESPONSE_PLAN_BY_RISK_ID_REQUEST: 'GET_RISK_RESPONSE_PLAN_BY_RISK_ID_REQUEST',
    GET_RISK_RESPONSE_PLAN_BY_RISK_ID_SUCCESS: 'GET_RISK_RESPONSE_PLAN_BY_RISK_ID_SUCCESS',
    GET_RISK_RESPONSE_PLAN_BY_RISK_ID_FAILURE: 'GET_RISK_RESPONSE_PLAN_BY_RISK_ID_FAILURE',
}