export const manufacturingMetricConstants = {
  GET_ALL_MANUFACTURING_KPIS_REQUEST: 'GET_ALL_MANUFACTURING_KPIS_REQUEST',
  GET_ALL_MANUFACTURING_KPIS_SUCCESS: 'GET_ALL_MANUFACTURING_KPIS_SUCCESS',
  GET_ALL_MANUFACTURING_KPIS_FAILURE: 'GET_ALL_MANUFACTURING_KPIS_FAILURE',

  GET_MANUFACTURING_KPI_BY_ID_REQUEST: 'GET_MANUFACTURING_KPI_BY_ID_REQUEST',
  GET_MANUFACTURING_KPI_BY_ID_SUCCESS: 'GET_MANUFACTURING_KPI_BY_ID_SUCCESS',
  GET_MANUFACTURING_KPI_BY_ID_FAILURE: 'GET_MANUFACTURING_KPI_BY_ID_FAILURE',

  CREATE_MANUFACTURING_KPI_REQUEST: 'CREATE_MANUFACTURING_KPI_REQUEST',
  CREATE_MANUFACTURING_KPI_SUCCESS: 'CREATE_MANUFACTURING_KPI_SUCCESS',
  CREATE_MANUFACTURING_KPI_FAILURE: 'CREATE_MANUFACTURING_KPI_FAILURE',

  EDIT_MANUFACTURING_KPIS_REQUEST: 'EDIT_MANUFACTURING_KPIS_REQUEST',
  EDIT_MANUFACTURING_KPIS_SUCCESS: 'EDIT_MANUFACTURING_KPIS_SUCCESS',
  EDIT_MANUFACTURING_KPIS_FAILURE: 'EDIT_MANUFACTURING_KPIS_FAILURE',

  EDIT_MANUFACTURING_KPI_REQUEST: 'EDIT_MANUFACTURING_KPI_REQUEST',
  EDIT_MANUFACTURING_KPI_SUCCESS: 'EDIT_MANUFACTURING_KPI_SUCCESS',
  EDIT_MANUFACTURING_KPI_FAILURE: 'EDIT_MANUFACTURING_KPI_FAILURE',

  GET_ALL_REPORT_ELEMENTS_REQUEST: 'GET_ALL_REPORT_ELEMENTS_REQUEST',
  GET_ALL_REPORT_ELEMENTS_SUCCESS: 'GET_ALL_REPORT_ELEMENTS_SUCCESS',
  GET_ALL_REPORT_ELEMENTS_FAILURE: 'GET_ALL_REPORT_ELEMENTS_FAILURE'
}
