export const CustomerConstants = {
    GET_CUSTOMER_GROUPS_REQUEST: 'GET_CUSTOMER_GROUPS_REQUEST',
    GET_CUSTOMER_GROUPS_SUCCESS: 'GET_CUSTOMER_GROUPS_SUCCESS',
    GET_CUSTOMER_GROUPS_FAILE: 'GET_CUSTOMER_GROUPS_FAILE',

    PAGINATE_CUSTOMER_GROUPS_REQUEST: 'PAGINATE_CUSTOMER_GROUPS_REQUEST',
    PAGINATE_CUSTOMER_GROUPS_SUCCESS: 'PAGINATE_CUSTOMER_GROUPS_SUCCESS',
    PAGINATE_CUSTOMER_GROUPS_FAILE: 'PAGINATE_CUSTOMER_GROUPS_FAILE',

    GET_LOCATIONS_REQUEST: 'GET_LOCATIONS_REQUEST',
    GET_LOCATIONS_SUCCESS: 'GET_LOCATIONS_SUCCESS',
    GET_LOCATIONS_FAILE: 'GET_LOCATIONS_FAILE',
}