export const CrmGroupConstants = {
    GET_CRM_GROUPS_REQUEST: 'GET_CRM_GROUPS_REQUEST',
    GET_CRM_GROUPS_SUCCESS: 'GET_CRM_GROUPS_SUCCESS',
    GET_CRM_GROUPS_FAILE: 'GET_CRM_GROUPS_FAILE',

    PAGINATE_CRM_GROUPS_REQUEST: 'PAGINATE_CRM_GROUPS_REQUEST',
    PAGINATE_CRM_GROUPS_SUCCESS: 'PAGINATE_CRM_GROUPS_SUCCESS',
    PAGINATE_CRM_GROUPS_FAILE: 'PAGINATE_CRM_GROUPS_FAILE',

    GET_CRM_GROUP_REQUEST: 'GET_CRM_GROUP_REQUEST',
    GET_CRM_GROUP_SUCCESS: 'GET_CRM_GROUP_SUCCESS',
    GET_CRM_GROUP_FAILE: 'GET_CRM_GROUP_FAILE',

    CREATE_CRM_GROUP_REQUEST: 'CREATE_CRM_GROUP_REQUEST',
    CREATE_CRM_GROUP_SUCCESS: 'CREATE_CRM_GROUP_SUCCESS',
    CREATE_CRM_GROUP_FAILE: 'CREATE_CRM_GROUP_FAILE',

    EDIT_CRM_GROUP_REQUEST: 'EDIT_CRM_GROUP_REQUEST',
    EDIT_CRM_GROUP_SUCCESS: 'EDIT_CRM_GROUP_SUCCESS',
    EDIT_CRM_GROUP_FAILE: 'EDIT_CRM_GROUP_FAILE',

    DELETE_CRM_GROUP_REQUEST: 'DELETE_CRM_GROUP_REQUEST',
    DELETE_CRM_GROUP_SUCCESS: 'DELETE_CRM_GROUP_SUCCESS',
    DELETE_CRM_GROUP_FAILE: 'DELETE_CRM_GROUP_FAILE',
}