export const exampleConstants = {
    GET_ALL_EXAMPLES_REQUEST: "GET_ALL_EXAMPLES_REQUEST",
    GET_ALL_EXAMPLES_SUCCESS: "GET_ALL_EXAMPLES_SUCCESS",
    GET_ALL_EXAMPLES_FAILURE: "GET_ALL_EXAMPLES_FAILURE",
}
