export const ConfigurationConstants = {
    GET_CONFIGURATION_REQUEST: 'GET_CONFIGURATION_REQUEST',
    GET_CONFIGURATION_SUCCESS: 'GET_CONFIGURATION_SUCCESS',
    GET_CONFIGURATION_FAILE: 'GET_CONFIGURATION_FAILE',

    CREATE_CONFIGURATION_REQUEST: 'CREATE_CONFIGURATION_REQUEST',
    CREATE_CONFIGURATION_SUCCESS: 'CREATE_CONFIGURATION_SUCCESS',
    CREATE_CONFIGURATION_FAILE: 'CREATE_CONFIGURATION_FAILE',

    EDIT_CONFIGURATION_REQUEST: 'EDIT_CONFIGURATION_REQUEST',
    EDIT_CONFIGURATION_SUCCESS: 'EDIT_CONFIGURATION_SUCCESS',
    EDIT_CONFIGURATION_FAILE: 'EDIT_CONFIGURATION_FAILE',
}