export const RiskDistributionConstants ={
    UPDATE_ALG_REQUEST: 'UPDATE_ALG_REQUEST',
    UPDATE_ALG_SUCCESS: 'UPDATE_ALG_SUCCESS',
    UPDATE_ALG_FAILURE: 'UPDATE_ALG_FAILURE',

    CHANGE_ALGORITHMS_REQUEST: 'CHANGE_ALGORITHMS_REQUEST',
    CHANGE_ALGORITHMS_SUCCESS: 'CHANGE_ALGORITHMS_SUCCESS',
    CHANGE_ALGORITHMS_FAILURE: 'CHANGE_ALGORITHMS_FAILURE',
    
    GET_RISK_DISTRIBUTION_REQUEST: 'GET_RISK_DISTRIBUTION_REQUEST',
    GET_RISK_DISTRIBUTION_SUCCESS: 'GET_RISK_DISTRIBUTION_SUCCESS',
    GET_RISK_DISTRIBUTION_FAILURE: 'GET_RISK_DISTRIBUTION_FAILURE',

    EDIT_RISK_DISTRIBUTION_REQUEST: 'EDIT_RISK_DISTRIBUTION_REQUEST',
    EDIT_RISK_DISTRIBUTION_SUCCESS: 'EDIT_RISK_DISTRIBUTION_SUCCESS',
    EDIT_RISK_DISTRIBUTION_FAILURE: 'EDIT_RISK_DISTRIBUTION_FAILURE',

    CREATE_RISK_DISTRIBUTION_REQUEST: 'CREATE_RISK_DISTRIBUTION_REQUEST',
    CREATE_RISK_DISTRIBUTION_SUCCESS: 'CREATE_RISK_DISTRIBUTION_SUCCESS',
    CREATE_RISK_DISTRIBUTION_FAILURE: 'CREATE_RISK_DISTRIBUTION_FAILURE',

    DELETE_RISK_DISTRIBUTION_REQUEST: 'DELETE_RISK_DISTRIBUTION_REQUEST',
    DELETE_RISK_DISTRIBUTION_SUCCESS: 'DELETE_RISK_DISTRIBUTION_SUCCESS',
    DELETE_RISK_DISTRIBUTION_FAILURE: 'DELETE_RISK_DISTRIBUTION_FAILURE',

    GET_RISK_DISTRIBUTION_BY_ID_REQUEST: 'GET_RISK_DISTRIBUTION_BY_ID_REQUEST',
    GET_RISK_DISTRIBUTION_BY_ID_SUCCESS: 'GET_RISK_DISTRIBUTION_BY_ID_SUCCESS',
    GET_RISK_DISTRIBUTION_BY_ID_FAILURE: 'GET_RISK_DISTRIBUTION_BY_ID_FAILURE',

    GET_PARENTS_OF_RISK_REQUEST: 'GET_PARENTS_OF_RISK_REQUEST',
    GET_PARENTS_OF_RISK_SUCCESS: 'GET_PARENTS_OF_RISK_SUCCESS',
    GET_PARENTS_OF_RISK_FAILURE: 'GET_PARENTS_OF_RISK_FAILURE',

    BAYESIAN_NETWORK_AUTO_CONFIG_REQUEST:  'BAYESIAN_NETWORK_AUTO_CONFIG_REQUEST',
    BAYESIAN_NETWORK_AUTO_CONFIG_SUCCESS:  'BAYESIAN_NETWORK_AUTO_CONFIG_SUCCESS',
    BAYESIAN_NETWORK_AUTO_CONFIG_FAILURE:  'BAYESIAN_NETWORK_AUTO_CONFIG_FAILURE',
    
    UPDATE_PROBABILITY_REQUEST:  'UPDATE_PROBABILITY_REQUEST',
    UPDATE_PROBABILITY_SUCCESS:  'UPDATE_PROBABILITY_SUCCESS',
    UPDATE_PROBABILITY_FAILURE:  'UPDATE_PROBABILITY_FAILURE'
    

}