export const QuoteConstants = {
    GET_ALL_QUOTES_REQUEST: 'GET_ALL_QUOTES_REQUEST',
    GET_ALL_QUOTES_SUCCESS: 'GET_ALL_QUOTES_SUCCESS',
    GET_ALL_QUOTES_FAILURE: 'GET_ALL_QUOTES_FAILURE',

    CREATE_QUOTE_REQUEST: 'CREATE_QUOTE_REQUEST',
    CREATE_QUOTE_SUCCESS: 'CREATE_QUOTE_SUCCESS',
    CREATE_QUOTE_FAILURE: 'CREATE_QUOTE_FAILURE',

    GET_DETAIL_QUOTE_REQUEST: 'GET_DETAIL_QUOTE_REQUEST',
    GET_DETAIL_QUOTE_FAILURE: 'GET_DETAIL_QUOTE_FAILURE',
    GET_DETAIL_QUOTE_SUCCESS: 'GET_DETAIL_QUOTE_SUCCESS',

    UPDATE_QUOTE_REQUEST: 'UPDATE_QUOTE_REQUEST',
    UPDATE_QUOTE_SUCCESS: 'UPDATE_QUOTE_SUCCESS',
    UPDATE_QUOTE_FAILURE: 'UPDATE_QUOTE_FAILURE'
}