export const SystemConstants = {
    GET_BACKUPS_REQUEST: 'GET_BACKUPS_REQUEST',
    GET_BACKUPS_SUCCESS: 'GET_BACKUPS_SUCCESS',
    GET_BACKUPS_FAILE: 'GET_BACKUPS_FAILE',

    CREATE_BACKUP_REQUEST: 'CREATE_BACKUP_REQUEST',
    CREATE_BACKUP_SUCCESS: 'CREATE_BACKUP_SUCCESS',
    CREATE_BACKUP_FAILE: 'CREATE_BACKUP_FAILE',

    DELETE_BACKUP_REQUEST: 'DELETE_BACKUP_REQUEST',
    DELETE_BACKUP_SUCCESS: 'DELETE_BACKUP_SUCCESS',
    DELETE_BACKUP_FAILE: 'DELETE_BACKUP_FAILE',

    RESTORE_REQUEST: 'RESTORE_REQUEST',
    RESTORE_SUCCESS: 'RESTORE_SUCCESS',
    RESTORE_FAILE: 'RESTORE_FAILE',
}