export const SystemConstants = {
    GET_BACKUPS_REQUEST: 'GET_BACKUPS_REQUEST',
    GET_BACKUPS_SUCCESS: 'GET_BACKUPS_SUCCESS',
    GET_BACKUPS_FAILE: 'GET_BACKUPS_FAILE',

    GET_CONFIG_BACKUP_REQUEST: 'GET_CONFIG_BACKUP_REQUEST',
    GET_CONFIG_BACKUP_SUCCESS: 'GET_CONFIG_BACKUP_SUCCESS',
    GET_CONFIG_BACKUP_FAILE: 'GET_CONFIG_BACKUP_FAILE',

    CREATE_BACKUP_REQUEST: 'CREATE_BACKUP_REQUEST',
    CREATE_BACKUP_SUCCESS: 'CREATE_BACKUP_SUCCESS',
    CREATE_BACKUP_FAILE: 'CREATE_BACKUP_FAILE',

    CONFIG_BACKUP_REQUEST: 'CONFIG_BACKUP_REQUEST',
    CONFIG_BACKUP_SUCCESS: 'CONFIG_BACKUP_SUCCESS',
    CONFIG_BACKUP_FAILE: 'CONFIG_BACKUP_FAILE',

    DELETE_BACKUP_REQUEST: 'DELETE_BACKUP_REQUEST',
    DELETE_BACKUP_SUCCESS: 'DELETE_BACKUP_SUCCESS',
    DELETE_BACKUP_FAILE: 'DELETE_BACKUP_FAILE',

    RESTORE_REQUEST: 'RESTORE_REQUEST',
    RESTORE_SUCCESS: 'RESTORE_SUCCESS',
    RESTORE_FAILE: 'RESTORE_FAILE',

    EDIT_BACKUP_INFO_REQUEST: 'EDIT_BACKUP_INFO_REQUEST',
    EDIT_BACKUP_INFO_SUCCESS: 'EDIT_BACKUP_INFO_SUCCESS',
    EDIT_BACKUP_INFO_FAILE: 'EDIT_BACKUP_INFO_FAILE',

    DOWNLOAD_BACKUP_VERSION_REQUEST: 'DOWNLOAD_BACKUP_VERSION_REQUEST',
    DOWNLOAD_BACKUP_VERSION_SUCCESS: 'DOWNLOAD_BACKUP_VERSION_SUCCESS',
    DOWNLOAD_BACKUP_VERSION_FAILE: 'DOWNLOAD_BACKUP_VERSION_FAILE',
}