export const qualityDasboardConstants = {
  GET_NUMBER_CREATED_INSPECTION_REQUEST: 'GET_NUMBER_CREATED_INSPECTION_REQUEST',
  GET_NUMBER_CREATED_INSPECTION_SUCCESS: 'GET_NUMBER_CREATED_INSPECTION_SUCCESS',
  GET_NUMBER_CREATED_INSPECTION_FAILURE: 'GET_NUMBER_CREATED_INSPECTION_FAILURE',

  GET_ERROR_NUM_BY_REPORTER_REQUEST: 'GET_ERROR_NUM_BY_REPORTER_REQUEST',
  GET_ERROR_NUM_BY_REPORTER_SUCCESS: 'GET_ERROR_NUM_BY_REPORTER_SUCCESS',
  GET_ERROR_NUM_BY_REPORTER_FAILURE: 'GET_ERROR_NUM_BY_REPORTER_FAILURE',

  GET_ERROR_NUM_BY_GROUP_REQUEST: 'GET_ERROR_NUM_BY_GROUP_REQUEST',
  GET_ERROR_NUM_BY_GROUP_SUCCESS: 'GET_ERROR_NUM_BY_GROUP_SUCCESS',
  GET_ERROR_NUM_BY_GROUP_FAILURE: 'GET_ERROR_NUM_BY_GROUP_FAILURE'
}
