export const ShipperConstants = {
    GET_ALL_SHIPPER_REQUEST: "GET_ALL_SHIPPER_REQUEST",
    GET_ALL_SHIPPER_SUCCESS: "GET_ALL_SHIPPER_SUCCESS",
    GET_ALL_SHIPPER_FAILURE: "GET_ALL_SHIPPER_FAILURE",

    GET_ALL_SHIPPER_NOT_CONFIRM_REQUEST: "GET_ALL_SHIPPER_NOT_CONFIRM_REQUEST",
    GET_ALL_SHIPPER_NOT_CONFIRM_SUCCESS: "GET_ALL_SHIPPER_NOT_CONFIRM_SUCCESS",
    GET_ALL_SHIPPER_NOT_CONFIRM_FAILURE: "GET_ALL_SHIPPER_NOT_CONFIRM_FAILURE",

    GET_ALL_SHIPPER_TASK_REQUEST: "GET_ALL_SHIPPER_TASK_REQUEST",
    GET_ALL_SHIPPER_TASK_SUCCESS: "GET_ALL_SHIPPER_TASK_SUCCESS",
    GET_ALL_SHIPPER_TASK_FAILURE: "GET_ALL_SHIPPER_TASK_FAILURE",

    GET_ALL_SHIPPER_SCHEDULE_REQUEST: "GET_ALL_SHIPPER_SCHEDULE_REQUEST",
    GET_ALL_SHIPPER_SCHEDULE_SUCCESS: "GET_ALL_SHIPPER_SCHEDULE_SUCCESS",
    GET_ALL_SHIPPER_SCHEDULE_FAILURE: "GET_ALL_SHIPPER_SCHEDULE_FAILURE",

    GET_ALL_SHIPPER_WITH_CONDITION_REQUEST: "GET_ALL_SHIPPER_WITH_CONDITION_REQUEST",
    GET_ALL_SHIPPER_WITH_CONDITION_SUCCESS: "GET_ALL_SHIPPER_WITH_CONDITION_SUCCESS",
    GET_ALL_SHIPPER_WITH_CONDITION_FAILURE: "GET_ALL_SHIPPER_WITH_CONDITION_FAILURE",

    DELETE_SHIPPER_REQUEST: "DELETE_DELETE_SHIPPER_REQUEST",
    DELETE_SHIPPER_SUCCESS: "DELETE_SHIPPER_SUCCESS",
    DELETE_SHIPPER_FAILURE: "DELETE_SHIPPER_FAILURE",

    CREATE_SHIPPER_REQUEST: "CREATE_SHIPPER_REQUEST",
    CREATE_SHIPPER_SUCCESS: "CREATE_SHIPPER_SUCCESS",
    CREATE_SHIPPER_FAILURE: "CREATE_SHIPPER_FAILURE",

    EDIT_SHIPPER_REQUEST: "EDIT_SHIPPER_REQUEST",
    EDIT_SHIPPER_SUCCESS: "EDIT_SHIPPER_SUCCESS",
    EDIT_SHIPPER_FAILURE: "EDIT_SHIPPER_FAILURE",

    GET_SHIPPER_DETAIL_REQUEST: "GET_SHIPPER_DETAIL_REQUEST",
    GET_SHIPPER_DETAIL_SUCCESS: "GET_SHIPPER_DETAIL_SUCCESS",
    GET_SHIPPER_DETAIL_FAILURE: "GET_SHIPPER_DETAIL_FAILURE",

    GET_SHIPPER_FREE_FOR_JOURNEY_REQUEST: "GET_SHIPPER_FREE_FOR_JOURNEY_REQUEST",
    GET_SHIPPER_FREE_FOR_JOURNEY_SUCCESS: "GET_SHIPPER_FREE_FOR_JOURNEY_SUCCESS",
    GET_SHIPPER_FREE_FOR_JOURNEY_FAILURE: "GET_SHIPPER_FREE_FOR_JOURNEY_FAILURE",

    CALCULATE_SHIPPER_SALARY_REQUEST: "CALCULATE_SHIPPER_SALARY_REQUEST",
    CALCULATE_SHIPPER_SALARY_SUCCESS: "CALCULATE_SHIPPER_SALARY_SUCCESS",
    CALCULATE_SHIPPER_SALARY_FAILURE: "CALCULATE_SHIPPER_SALARY_FAILURE",

    SAVE_SHIPPER_SALARY_REQUEST: "SAVE_SHIPPER_SALARY_REQUEST",
    SAVE_SHIPPER_SALARY_SUCCESS: "SAVE_SHIPPER_SALARY_SUCCESS",
    SAVE_SHIPPER_SALARY_FAILURE: "SAVE_SHIPPER_SALARY_FAILURE",

    GET_ALL_SHIPPER_SALARY_REQUEST: "GET_ALL_SHIPPER_SALARY_REQUEST",
    GET_ALL_SHIPPER_SALARY_SUCCESS: "GET_ALL_SHIPPER_SALARY_SUCCESS",
    GET_ALL_SHIPPER_SALARY_FAILURE: "GET_ALL_SHIPPER_SALARY_FAILURE",

    UPDATE_REALTIME_SHIPPER_STATUS: "UPDATE_REALTIME_SHIPPER_STATUS"
}