export const CrmUnitKPIConstants = {
    GET_CRM_CRMUNITKPI_REQUEST: 'GET_CRM_CRMUNITKPI_REQUEST',
    GET_CRM_CRMUNITKPI_SUCCESS: 'GET_CRM_CRMUNITKPI_SUCCESS',
    GET_CRM_CRMUNITKPI_FAILE: 'GET_CRM_CRMUNITKPI_FAILE',

    EDIT_CRM_CRMUNITKPI_REQUEST: 'EDIT_CRM_CRMUNITKPI_REQUEST',
    EDIT_CRM_CRMUNITKPI_SUCCESS: 'EDIT_CRM_CRMUNITKPI_SUCCESS',
    EDIT_CRM_CRMUNITKPI_FAILE: 'EDIT_CRM_CRMUNITKPI_FAILE',

}