export const RecommendProcureConstants = {
    GET_RECOMMENDPROCURE_REQUEST: 'GET_RECOMMENDPROCURE_REQUEST',
    GET_RECOMMENDPROCURE_SUCCESS: 'GET_RECOMMENDPROCURE_SUCCESS',
    GET_RECOMMENDPROCURE_FAILURE: 'GET_RECOMMENDPROCURE_FAILURE',

    CREATE_RECOMMENDPROCURE_REQUEST: 'CREATE_NEW_RECOMMENDPROCURE_REQUEST',
    CREATE_RECOMMENDPROCURE_SUCCESS: 'CREATE_NEW_RECOMMENDPROCURE_SUCCESS',
    CREATE_RECOMMENDPROCURE_FAILURE: 'CREATE_NEW_RECOMMENDPROCURE_FAILURE',

    DELETE_RECOMMENDPROCURE_REQUEST: 'DELETE_RECOMMENDPROCURE_REQUEST',
    DELETE_RECOMMENDPROCURE_SUCCESS:  'DELETE_RECOMMENDPROCURE_SUCCESS',
    DELETE_RECOMMENDPROCURE_FAILURE:  'DELETE_RECOMMENDPROCURE_FAILURE',

    UPDATE_RECOMMENDPROCURE_REQUEST: 'UPDATE_RECOMMENDPROCURE_REQUEST',
    UPDATE_RECOMMENDPROCURE_SUCCESS: 'UPDATE_RECOMMENDPROCURE_SUCCESS',
    UPDATE_RECOMMENDPROCURE_FAILURE: 'UPDATE_RECOMMENDPROCURE_FAILURE',
};