const mongoose = require("mongoose");
const {
  InventoryWarehouse,
  Employee,
  Major,
  CareerPosition,
} = require("../models");

require("dotenv").config();

const initInventoryWarehouseData = async () => {
  let connectOptions =
    process.env.DB_AUTHENTICATION === "true"
      ? {
          useNewUrlParser: true,
          useUnifiedTopology: true,
          useCreateIndex: true,
          useFindAndModify: false,
          user: process.env.DB_USERNAME,
          pass: process.env.DB_PASSWORD,
        }
      : {
          useNewUrlParser: true,
          useUnifiedTopology: true,
          useCreateIndex: true,
          useFindAndModify: false,
        };
  const vnistDB = mongoose.createConnection(
    `mongodb://${process.env.DB_HOST}:${process.env.DB_PORT || "27017"}/vnist`,
    connectOptions
  );
  if (!vnistDB) throw "DB vnist cannot connect";

  console.log("DB vnist connected");

  const initModels = (db) => {
    if (!db.models.InventoryWarehouse) InventoryWarehouse(db);
  };

  initModels(vnistDB);

  console.log("Tạo dữ liệu cho inventory kho");
  await InventoryWarehouse(vnistDB).insertMany([
    {
      location: "A10-100-R-2052-1914-0",
      item_no: 835099,
      item_description: "AMERICAN YELLOW 120CT",
      pack: 4,
      size: "5#",
      item_wgt: 20,
      weekly_mvmt: 13.6,
      item_cost: 43.14,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-100-R-2052-1914-84",
      item_no: 645709,
      item_description: "TRAY-FOOD RED PLAID 1#",
      pack: 1000,
      size: "1#",
      item_wgt: 12.5,
      weekly_mvmt: 30.2,
      item_cost: 15.73,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-101-L-2232-1926-0",
      item_no: 425186,
      item_description: "LEMONADE ICE TEA HALF/HALF",
      pack: 8,
      size: "59 OZ",
      item_wgt: 29.5,
      weekly_mvmt: 41.4,
      item_cost: 12.88,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-101-L-2232-1926-84",
      item_no: 621606,
      item_description: "MUSTARD YELLOW 104 OZ JUG",
      pack: 6,
      size: "104 OZ",
      item_wgt: 42,
      weekly_mvmt: 6.2,
      item_cost: 23.07,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-104-R-2052-1962-0",
      item_no: 606600,
      item_description: "CRACKER OYSTER INDIV pack",
      pack: 150,
      size: ".5 OZ",
      item_wgt: 3,
      weekly_mvmt: 42.6,
      item_cost: 13.31,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-104-R-2052-1962-84",
      item_no: 171002,
      item_description: "SALAMI HARD",
      pack: 6,
      size: "6.5#",
      item_wgt: 39,
      weekly_mvmt: 445,
      item_cost: 3.24,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-105-L-2232-1986-0",
      item_no: 432496,
      item_description: "PEANUT CLUSTER MAPLE CREAM",
      pack: 1,
      size: "23#",
      item_wgt: 23,
      weekly_mvmt: 9.6,
      item_cost: 55.7,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-105-L-2232-1986-84",
      item_no: 417009,
      item_description: "GRAPEFRUIT JUICE PURE SQUEEZE",
      pack: 6,
      size: "59 OZ",
      item_wgt: 25.65,
      weekly_mvmt: 27.6,
      item_cost: 19.61,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-108-R-2052-2022-0",
      item_no: 370011,
      item_description: "COTTAGE CHEESE SMALL CURD",
      pack: 12,
      size: "8 OZ",
      item_wgt: 6,
      weekly_mvmt: 42.6,
      item_cost: 10.6718,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-108-R-2052-2022-84",
      item_no: 624085,
      item_description: "POTATO SALAD SINGLE SERVE CUP",
      pack: 6,
      size: "6 OZ",
      item_wgt: 4.5,
      weekly_mvmt: 689.8,
      item_cost: 5.16,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-109-L-2232-2046-0",
      item_no: 514503,
      item_description: "T-SACK-THANK YOU HI-D",
      pack: 2000,
      size: "12X7X21",
      item_wgt: 28.5,
      weekly_mvmt: 27,
      item_cost: 33.2,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-109-L-2232-2046-84",
      item_no: 189700,
      item_description: "CREAM CHEESE PLAIN",
      pack: 10,
      size: "3#",
      item_wgt: 30,
      weekly_mvmt: 115.2,
      item_cost: 1.8995,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-112-R-2052-2082-0",
      item_no: 841462,
      item_description: "PEPPERONI SAND. SLICED",
      pack: 8,
      size: "2#",
      item_wgt: 16,
      weekly_mvmt: 82.8,
      item_cost: 3.39,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-112-R-2052-2082-84",
      item_no: 699667,
      item_description: "PEPPERONI CHEESE & CRACKERS",
      pack: 6,
      size: "3.9 OZ",
      item_wgt: 23.4,
      weekly_mvmt: 473,
      item_cost: 10.8,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-113-L-2232-2094-0",
      item_no: 923937,
      item_description: "HAM POLISH 98%",
      pack: 3,
      size: "11#",
      item_wgt: 35,
      weekly_mvmt: 42.8,
      item_cost: 2.25,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-113-L-2232-2094-84",
      item_no: 201002,
      item_description: "DRESSING REF RANCH DELUXE",
      pack: 4,
      size: "GALLON",
      item_wgt: 31.05,
      weekly_mvmt: 17.4,
      item_cost: 36.74,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-117-R-2052-2142-0",
      item_no: 582912,
      item_description: "TURKEY BREAST MAPLE HONEY",
      pack: 2,
      size: "6-7#",
      item_wgt: 12.8,
      weekly_mvmt: 43,
      item_cost: 3.04,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-117-R-2052-2142-84",
      item_no: 126000,
      item_description: "SWISS 4 X 4 LOT",
      pack: 2,
      size: "8# AVG",
      item_wgt: 16,
      weekly_mvmt: 293.4,
      item_cost: 2.49,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-118-L-2232-2154-0",
      item_no: 505514,
      item_description: "SHIPPER BAR CHIP GARLIC",
      pack: 36,
      size: "7 OZ",
      item_wgt: 26.6,
      weekly_mvmt: 0,
      item_cost: 64.08,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-118-L-2232-2154-84",
      item_no: 514793,
      item_description: "FILLING SPUN GOLD LEMON",
      pack: 1,
      size: "38#",
      item_wgt: 38,
      weekly_mvmt: 12,
      item_cost: 22.6,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-121-R-2052-2190-0",
      item_no: 892146,
      item_description: "HAM DINNER BNLS WHOLE",
      pack: 2,
      size: "9#",
      item_wgt: 16,
      weekly_mvmt: 4,
      item_cost: 2.1,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-121-R-2052-2190-84",
      item_no: 294005,
      item_description: "TURKEY BREAST SMOKIN CHIPOTLE",
      pack: 3,
      size: "4.5#",
      item_wgt: 13.5,
      weekly_mvmt: 41,
      item_cost: 3.63,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-122-L-2232-2214-0",
      item_no: 667500,
      item_description: "BAGS WHITE KRAFT 6#",
      pack: 500,
      size: "6X4X11",
      item_wgt: 11,
      weekly_mvmt: 25.4,
      item_cost: 10.18,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-122-L-2232-2214-84",
      item_no: 719183,
      item_description: "PIZZA SAUCE W/OIL & SPICES",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 45.2,
      weekly_mvmt: 19.6,
      item_cost: 22.28,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-125-R-2052-2250-0",
      item_no: 208000,
      item_description: "ROAST BEEF TOP ROUND",
      pack: 2,
      size: "7.5#",
      item_wgt: 15,
      weekly_mvmt: 43.4,
      item_cost: 4.28,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-125-R-2052-2250-84",
      item_no: 157500,
      item_description: "ROAST BEEF LONDON BROIL",
      pack: 2,
      size: "7#",
      item_wgt: 13.5,
      weekly_mvmt: 120.6,
      item_cost: 5.88,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-126-L-2232-2274-0",
      item_no: 840216,
      item_description: "AMERICAN RIBBON SL 120 F/S",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 0.5,
      item_cost: 2.059,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-126-L-2232-2274-84",
      item_no: 934556,
      item_description: "HAM COUNTRY",
      pack: 2,
      size: "14-16#",
      item_wgt: 30,
      weekly_mvmt: 0,
      item_cost: 2.58,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-129-R-2052-2310-0",
      item_no: 237541,
      item_description: "BACON THICK SLICED",
      pack: 24,
      size: "16 OZ",
      item_wgt: 24,
      weekly_mvmt: 19,
      item_cost: 3.99,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-129-R-2052-2310-84",
      item_no: 226800,
      item_description: "HAM OLD FASH SMOKEHOUSE",
      pack: 2,
      size: "10#",
      item_wgt: 20,
      weekly_mvmt: 308.2,
      item_cost: 3.4,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-12-L-2232-678-0",
      item_no: 672017,
      item_description: "ICING GREEN N GLOSSY",
      pack: 1,
      size: "23#",
      item_wgt: 23,
      weekly_mvmt: 0,
      item_cost: 26.89,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-130-L-2232-2322-0",
      item_no: 196733,
      item_description: "ALMONDS ROASTED SEA SALT",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 3.4,
      item_cost: 80.69,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-130-L-2232-2322-84",
      item_no: 646800,
      item_description: "PINEAPPLE TIDBITS IN JUICE",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 40.5,
      weekly_mvmt: 22.2,
      item_cost: 35.67,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-134-R-2052-2370-0",
      item_no: 615143,
      item_description: "COFFEE WOODWARD AVE BLEND",
      pack: 6,
      size: "8 OZ",
      item_wgt: 3,
      weekly_mvmt: 43.8,
      item_cost: 22.8,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-134-R-2052-2370-84",
      item_no: 240400,
      item_description: "TURKEY BREAST GOURMET LITE",
      pack: 2,
      size: "7#",
      item_wgt: 14,
      weekly_mvmt: 90.4,
      item_cost: 5.1,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-135-L-2232-2382-0",
      item_no: 326902,
      item_description: "HAM ITALIAN STYLE HOT",
      pack: 2,
      size: "5#",
      item_wgt: 10,
      weekly_mvmt: 16.6,
      item_cost: 3.6,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-135-L-2232-2382-84",
      item_no: 835650,
      item_description: "SESAME SEED TOASTED",
      pack: 1,
      size: "50#",
      item_wgt: 50,
      weekly_mvmt: 2,
      item_cost: 58.5,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-138-R-2052-2418-0",
      item_no: 762586,
      item_description: "TURKEY BREAST JP NATURAL",
      pack: 2,
      size: "8#",
      item_wgt: 16,
      weekly_mvmt: 43.6,
      item_cost: 3.55,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-138-R-2052-2418-84",
      item_no: 265745,
      item_description: "TURKEY BREAST LOW SODIUM",
      pack: 2,
      size: "7.5#",
      item_wgt: 15,
      weekly_mvmt: 108.2,
      item_cost: 3.63,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-140-L-2232-2442-0",
      item_no: 829233,
      item_description: "TURKEY BREAST BROWNED DLX",
      pack: 2,
      size: "9#",
      item_wgt: 18.2,
      weekly_mvmt: 21.2,
      item_cost: 2.39,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-140-L-2232-2442-84",
      item_no: 582929,
      item_description: "TURKEY BREAST GOLDEN BROWNED",
      pack: 2,
      size: "8-10#",
      item_wgt: 16.9,
      weekly_mvmt: 379.2,
      item_cost: 2.54,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-143-R-2052-2478-0",
      item_no: 362286,
      item_description: "POTATOES MASHED HOMESTYLE",
      pack: 6,
      size: "24 OZ",
      item_wgt: 9,
      weekly_mvmt: 44.2,
      item_cost: 10.34,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-143-R-2052-2478-84",
      item_no: 214000,
      item_description: "SALAMI HARD HICKORY",
      pack: 6,
      size: "6#",
      item_wgt: 36,
      weekly_mvmt: 187.6,
      item_cost: 3.28,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-145-L-2232-2502-0",
      item_no: 674500,
      item_description: "T-SACK-THANK YOU LOW-D",
      pack: 1000,
      size: "12X7X22",
      item_wgt: 13,
      weekly_mvmt: 49.6,
      item_cost: 25.37,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-145-L-2232-2502-84",
      item_no: 557871,
      item_description: "PEANUT BRITTLE",
      pack: 1,
      size: "20#",
      item_wgt: 20,
      weekly_mvmt: 32.6,
      item_cost: 29.55,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-148-R-2052-2538-0",
      item_no: 139100,
      item_description: "TURKEY BREAST HOMESTYLE",
      pack: 2,
      size: "8#",
      item_wgt: 16,
      weekly_mvmt: 59.6,
      item_cost: 5.1,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-148-R-2052-2538-84",
      item_no: 226700,
      item_description: "TURKEY BREAST OVEN ROASTED",
      pack: 2,
      size: "8#",
      item_wgt: 16,
      weekly_mvmt: 162.8,
      item_cost: 3.7,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-149-L-2232-2550-0",
      item_no: 359052,
      item_description: "KEFIR DRINK LF MANGO",
      pack: 6,
      size: "32 OZ",
      item_wgt: 12,
      weekly_mvmt: 44.4,
      item_cost: 13.4,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-149-L-2232-2550-84",
      item_no: 935207,
      item_description: "CHICKEN BREAST CITRUS LTO",
      pack: 3,
      size: "5#",
      item_wgt: 15,
      weekly_mvmt: 62.6,
      item_cost: 3.45,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-14-R-2052-714-0",
      item_no: 830024,
      item_description: "BAG 8LB WHITE BRUSTER",
      pack: 4,
      size: "500 CT",
      item_wgt: 47,
      weekly_mvmt: 1.2,
      item_cost: 110.56,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-14-R-2052-714-84",
      item_no: 797903,
      item_description: "PINEAPPLE TIDBITS IN LT SYRUP",
      pack: 6,
      size: "81 OZ",
      item_wgt: 34,
      weekly_mvmt: 2.8,
      item_cost: 29.88,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-153-R-2052-2598-0",
      item_no: 327602,
      item_description: "HUMMUS W/PRETZEL CLASSIC",
      pack: 12,
      size: "4.56 OZ",
      item_wgt: 4.28,
      weekly_mvmt: 190.4,
      item_cost: 13.44,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-153-R-2052-2598-84",
      item_no: 643295,
      item_description: "MAYONNAISE packETS",
      pack: 500,
      size: "12 GRAM",
      item_wgt: 14.75,
      weekly_mvmt: 9.8,
      item_cost: 43.91,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-154-L-2232-2610-0",
      item_no: 895963,
      item_description: "SACKS-HD BUSCHS SUMMER",
      pack: 300,
      size: "1/7-70#",
      item_wgt: 38,
      weekly_mvmt: 192.8,
      item_cost: 27.86,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-154-L-2232-2610-84",
      item_no: 92900,
      item_description: "CHICKEN BREAST BBQ",
      pack: 2,
      size: "4#",
      item_wgt: 8,
      weekly_mvmt: 75.6,
      item_cost: 3.63,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-157-R-2052-2646-0",
      item_no: 559248,
      item_description: "PORK ROAST DELI",
      pack: 2,
      size: "3.5-4#",
      item_wgt: 7.32,
      weekly_mvmt: 25.6,
      item_cost: 3.79,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-157-R-2052-2646-84",
      item_no: 217949,
      item_description: "YOGURT GREEK STRAWBERRY 0%",
      pack: 12,
      size: "5.3 OZ",
      item_wgt: 3.975,
      weekly_mvmt: 453.4,
      item_cost: 11.64,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-159-L-2232-2670-0",
      item_no: 301662,
      item_description: "DIP FRENCH ONION",
      pack: 12,
      size: "8 OZ",
      item_wgt: 6,
      weekly_mvmt: 45.2,
      item_cost: 7.83,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-159-L-2232-2670-84",
      item_no: 358344,
      item_description: "SOUR CREAM SQUEEZE",
      pack: 12,
      size: "15 OZ",
      item_wgt: 11.25,
      weekly_mvmt: 300,
      item_cost: 14.84,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-15-L-2232-726-84",
      item_no: 840566,
      item_description: "TOPPING CARAMEL",
      pack: 6,
      size: "96 OZ",
      item_wgt: 50.86,
      weekly_mvmt: 12.4,
      item_cost: 47.23,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-162-R-2052-2706-0",
      item_no: 362337,
      item_description: "BEEF STICKS HICKORY PROSP CH",
      pack: 3,
      size: "2.5#",
      item_wgt: 7.5,
      weekly_mvmt: 45.8,
      item_cost: 41.97,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-162-R-2052-2706-84",
      item_no: 240300,
      item_description: "TURKEY BREAST HONEY #61802",
      pack: 2,
      size: "7#",
      item_wgt: 14,
      weekly_mvmt: 30.2,
      item_cost: 5.1,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-164-L-2232-2730-0",
      item_no: 272723,
      item_description: "TORTILLAS CORN FAMILY pack",
      pack: 12,
      size: "32 OZ",
      item_wgt: 24,
      weekly_mvmt: 42.4,
      item_cost: 20.64,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-164-L-2232-2730-84",
      item_no: 453538,
      item_description: "PEANUTS HONEY ROASTED",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 18.8,
      item_cost: 32,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-167-R-2052-2766-0",
      item_no: 948479,
      item_description: "DIP ARTICHOKE & ASIAGO",
      pack: 4,
      size: "4.4#",
      item_wgt: 17.6,
      weekly_mvmt: 19,
      item_cost: 2.84,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-167-R-2052-2766-84",
      item_no: 240500,
      item_description: "TURKEY BREAST BLK FORST SMKD",
      pack: 2,
      size: "9.5#",
      item_wgt: 19,
      weekly_mvmt: 79.4,
      item_cost: 5.1,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-172-R-2052-2826-0",
      item_no: 606031,
      item_description: "HAM BLACK FOREST",
      pack: 2,
      size: "9.5#",
      item_wgt: 19,
      weekly_mvmt: 56.8,
      item_cost: 3.47,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-172-R-2052-2826-84",
      item_no: 893994,
      item_description: "CHEESE COLBY JACK SHREDDED",
      pack: 6,
      size: "2#",
      item_wgt: 12,
      weekly_mvmt: 96.2,
      item_cost: 26.46,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-17-R-2052-774-0",
      item_no: 608500,
      item_description: "BOX CAKE WINDOW EXPRESSIONS",
      pack: 50,
      size: "1/2 SHT",
      item_wgt: 29.2,
      weekly_mvmt: 37.2,
      item_cost: 42.49,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-17-R-2052-774-84",
      item_no: 425254,
      item_description: "LEMONADE DIET",
      pack: 8,
      size: "59 OZ",
      item_wgt: 29.5,
      weekly_mvmt: 35.8,
      item_cost: 12.88,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-195-L-2232-3138-0",
      item_no: 661900,
      item_description: "BAGS WICKET CLEAR POLY 1 MIL",
      pack: 1000,
      size: "11X18+4",
      item_wgt: 15.22,
      weekly_mvmt: 22.2,
      item_cost: 24.74,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-199-L-2232-3198-0",
      item_no: 617557,
      item_description: "ICED COFFEE DOUBLE ESPRESSO",
      pack: 6,
      size: "48 OZ",
      item_wgt: 18,
      weekly_mvmt: 56.4,
      item_cost: 21.42,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-1-R-2052-390-0",
      item_no: 174702,
      item_description: "PARTY TRAY-HORMEL SUPREME",
      pack: 8,
      size: "2.48#",
      item_wgt: 19.84,
      weekly_mvmt: 8.2,
      item_cost: 92.78,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-1-R-2052-390-84",
      item_no: 722000,
      item_description: "PIZZA SAUCE SUPER DOLCE SWEET",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 46.3,
      weekly_mvmt: 12,
      item_cost: 28.17,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-202-L-2232-3246-0",
      item_no: 206831,
      item_description: "LICORICE ALL SORTS",
      pack: 4,
      size: "6.6#",
      item_wgt: 26.4,
      weekly_mvmt: 46.8,
      item_cost: 46.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-206-L-2232-3306-0",
      item_no: 126536,
      item_description: "CHEDDAR MILD FEATHER SHREDDED",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 202.2,
      item_cost: 1.9935,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-209-L-2232-3366-0",
      item_no: 824970,
      item_description: "PEPPERONI SLICER REGULAR",
      pack: 12,
      size: "2#",
      item_wgt: 25.93,
      weekly_mvmt: 8.6,
      item_cost: 2.73,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-216-L-2232-3474-0",
      item_no: 953061,
      item_description: "T-SACK HIPPO-THANK YOU",
      pack: 1702,
      size: "12X7X22",
      item_wgt: 21,
      weekly_mvmt: 74,
      item_cost: 37.32,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-219-L-2232-3534-0",
      item_no: 393056,
      item_description: "PUNCH CITRUS",
      pack: 6,
      size: "128 OZ",
      item_wgt: 51,
      weekly_mvmt: 12.4,
      item_cost: 9.12,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-21-L-2232-846-0",
      item_no: 833181,
      item_description: "MIX COOKIE SUGAR",
      pack: 1,
      size: "35#",
      item_wgt: 35,
      weekly_mvmt: 2,
      item_cost: 35.48,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-21-L-2232-846-84",
      item_no: 619648,
      item_description: "WING SAUCE BUFFALO",
      pack: 4,
      size: "GALLON",
      item_wgt: 37.64,
      weekly_mvmt: 7.4,
      item_cost: 41.75,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-23-R-2052-882-0",
      item_no: 509727,
      item_description: "PARMESAN WHEEL",
      pack: 1,
      size: "20#",
      item_wgt: 20,
      weekly_mvmt: 7.4,
      item_cost: 3.11,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-24-L-2232-906-84",
      item_no: 957441,
      item_description: "FILLING APPLE FRUITFUL PASTRY",
      pack: 1,
      size: "40#",
      item_wgt: 40,
      weekly_mvmt: 5.6,
      item_cost: 56.33,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-27-R-2052-942-0",
      item_no: 836765,
      item_description: "PICKLES KOSHER WHOLE",
      pack: 1,
      size: "5 GAL",
      item_wgt: 46,
      weekly_mvmt: 0.8,
      item_cost: 23.89,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-27-R-2052-942-84",
      item_no: 245003,
      item_description: "GLAZE NEUTRAL FRUIT",
      pack: 12,
      size: "2#",
      item_wgt: 25,
      weekly_mvmt: 3,
      item_cost: 14.28,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-28-L-2232-954-0",
      item_no: 880266,
      item_description: "KOMBUCHA CALIFORNIA GRAPE",
      pack: 12,
      size: "16 OZ",
      item_wgt: 22.5,
      weekly_mvmt: 13.2,
      item_cost: 27,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-28-L-2232-954-84",
      item_no: 832733,
      item_description: "ALMONDS DICE BUTTERED W/S",
      pack: 1,
      size: "30#",
      item_wgt: 24,
      weekly_mvmt: 5.2,
      item_cost: 152,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-32-R-2052-1002-84",
      item_no: 149600,
      item_description: "CHEDDAR MEDIUM BLOCK*",
      pack: 1,
      size: "40#",
      item_wgt: 42.9,
      weekly_mvmt: 7.2,
      item_cost: 2.56,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-33-L-2232-1014-0",
      item_no: 510169,
      item_description: "LOAF LIVER",
      pack: 2,
      size: "2-3#",
      item_wgt: 6,
      weekly_mvmt: 38.2,
      item_cost: 2.46,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-33-L-2232-1014-84",
      item_no: 189500,
      item_description: "CREAM CHEESE",
      pack: 1,
      size: "30#",
      item_wgt: 30,
      weekly_mvmt: 58,
      item_cost: 1.8495,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-36-R-2052-1050-0",
      item_no: 535406,
      item_description: "T-SACK-NEIMANS MKTS",
      pack: 1000,
      size: "12X7X22",
      item_wgt: 15,
      weekly_mvmt: 72.2,
      item_cost: 27.08,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-36-R-2052-1050-84",
      item_no: 638600,
      item_description: "PASTRAMI SPICED BEEF",
      pack: 2,
      size: "5#",
      item_wgt: 10,
      weekly_mvmt: 25,
      item_cost: 5.19,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-37-L-2232-1074-0",
      item_no: 300100,
      item_description: "CONT SOUP GARDEN DESGN W/LID",
      pack: 250,
      size: "12 oz",
      item_wgt: 23,
      weekly_mvmt: 1.8,
      item_cost: 57.52,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-37-L-2232-1074-84",
      item_no: 788500,
      item_description: "HAM OLD TYME 10%",
      pack: 2,
      size: "12#",
      item_wgt: 24,
      weekly_mvmt: 89,
      item_cost: 1.59,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-3-L-2232-450-84",
      item_no: 611300,
      item_description: "MAYONNAISE EXTRA HEAVY",
      pack: 4,
      size: "GALLON",
      item_wgt: 33.04,
      weekly_mvmt: 163.2,
      item_cost: 25.97,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-3-R-2052-450-0",
      item_no: 560319,
      item_description: "WAFERS PINK APLINE",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 0,
      item_cost: 40.25,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-40-R-2052-1110-0",
      item_no: 585500,
      item_description: "CONT SOUP GARDEN DESGN W/LID",
      pack: 250,
      size: "16 OZ",
      item_wgt: 23,
      weekly_mvmt: 4.6,
      item_cost: 60.92,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-40-R-2052-1110-84",
      item_no: 119536,
      item_description: "COLBY MINI HORN*",
      pack: 2,
      size: "6#",
      item_wgt: 12,
      weekly_mvmt: 531.4,
      item_cost: 2.1555,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-41-L-2232-1134-0",
      item_no: 431935,
      item_description: "CHEESE SHRED ORGANIC ITALIAN",
      pack: 12,
      size: "6 OZ",
      item_wgt: 4.5,
      weekly_mvmt: 13.4,
      item_cost: 35.88,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-41-L-2232-1134-84",
      item_no: 357648,
      item_description: "POTATO SALAD MUSTARD packAGED",
      pack: 6,
      size: "32 OZ",
      item_wgt: 12,
      weekly_mvmt: 1293.8,
      item_cost: 11.25,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-44-R-2052-1170-0",
      item_no: 655161,
      item_description: "BOX PIZZA JONNAS TAYLOR 14IN",
      pack: 50,
      size: "14X14X2",
      item_wgt: 17,
      weekly_mvmt: 5.4,
      item_cost: 21.58,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-44-R-2052-1170-84",
      item_no: 241600,
      item_description: "ROAST BEEF TOP ROUND",
      pack: 2,
      size: "6#",
      item_wgt: 12,
      weekly_mvmt: 17.6,
      item_cost: 5.88,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-45-L-2232-1182-0",
      item_no: 620700,
      item_description: "CONT CLEAR HINGD LBH523(SL35)",
      pack: 500,
      size: "9X5X3.5",
      item_wgt: 24.1,
      weekly_mvmt: 33,
      item_cost: 52.37,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-45-L-2232-1182-84",
      item_no: 243700,
      item_description: "PEPPERONI SANDWICH STYLE",
      pack: 5,
      size: "4#",
      item_wgt: 20,
      weekly_mvmt: 60,
      item_cost: 2.57,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-49-R-2052-1230-0",
      item_no: 904800,
      item_description: "LID PLASTIC STRAW SLOT #32SL",
      pack: 500,
      size: "32-44OZ",
      item_wgt: 5,
      weekly_mvmt: 886.2,
      item_cost: 19.68,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-49-R-2052-1230-84",
      item_no: 290612,
      item_description: "HAM MAPLE HONEY",
      pack: 3,
      size: "4#",
      item_wgt: 12,
      weekly_mvmt: 69,
      item_cost: 3.41,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-4-L-2232-498-84",
      item_no: 886603,
      item_description: "HAM IMPORTED REDUCED SODIUM",
      pack: 2,
      size: "11#",
      item_wgt: 22,
      weekly_mvmt: 391.8,
      item_cost: 3.18,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-4-R-2052-498-84",
      item_no: 838298,
      item_description: "PEACHES SLICED IN LIGHT SYRUP",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 39.75,
      weekly_mvmt: 27.8,
      item_cost: 24.01,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-50-L-2232-1242-0",
      item_no: 675629,
      item_description: "CUP THORNTON IX OWN THE WAY",
      pack: 1000,
      size: "16 OZ",
      item_wgt: 12.03,
      weekly_mvmt: 40.4,
      item_cost: 52.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-50-L-2232-1242-84",
      item_no: 272876,
      item_description: "SACKS HAND UP-VILLAGE MARKET",
      pack: 300,
      size: "1/6-70#",
      item_wgt: 47,
      weekly_mvmt: 39.2,
      item_cost: 36.76,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-53-R-2052-1278-0",
      item_no: 362274,
      item_description: "TURKEY O/R DELI SHAVED",
      pack: 8,
      size: "9 OZ",
      item_wgt: 4.5,
      weekly_mvmt: 37,
      item_cost: 12,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-53-R-2052-1278-84",
      item_no: 119836,
      item_description: "PEPPER JACK MINI HORN",
      pack: 2,
      size: "6#",
      item_wgt: 12,
      weekly_mvmt: 134.8,
      item_cost: 2.009,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-54-L-2232-1302-0",
      item_no: 614700,
      item_description: "BAGS BREAD CLEAR POLY .75 MIL",
      pack: 1000,
      size: "5X5X19",
      item_wgt: 9.74,
      weekly_mvmt: 38.2,
      item_cost: 14.19,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-54-L-2232-1302-84",
      item_no: 156723,
      item_description: "RELISH CHICAGO STYLE",
      pack: 4,
      size: "GALLON",
      item_wgt: 38,
      weekly_mvmt: 14.6,
      item_cost: 18.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-57-R-2052-1338-0",
      item_no: 389842,
      item_description: "EASTER PASTEL KISSES  BULK",
      pack: 1,
      size: "25#",
      item_wgt: 26.6,
      weekly_mvmt: 0,
      item_cost: 89.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-57-R-2052-1338-84",
      item_no: 407800,
      item_description: "BOLOGNA DELUXE CLUB",
      pack: 2,
      size: "13.4#",
      item_wgt: 26.8,
      weekly_mvmt: 335.2,
      item_cost: 1.58,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-58-L-2232-1362-0",
      item_no: 198960,
      item_description: "PEANUTS BLANCH ROASTED NO SALT",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 10,
      item_cost: 38.61,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-58-L-2232-1362-84",
      item_no: 432938,
      item_description: "WATER IN PAPER CARTON",
      pack: 24,
      size: "16.9 OZ",
      item_wgt: 27.6,
      weekly_mvmt: 78.6,
      item_cost: 16.8,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-61-R-2052-1398-0",
      item_no: 192900,
      item_description: "TURKEY BREAST OVEN PREPARED",
      pack: 2,
      size: "8#",
      item_wgt: 16,
      weekly_mvmt: 41.2,
      item_cost: 2.79,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-61-R-2052-1398-84",
      item_no: 931644,
      item_description: "PUDDING ALMONDMILK DRK CHOC",
      pack: 6,
      size: "4/3.75Z",
      item_wgt: 5.625,
      weekly_mvmt: 38.8,
      item_cost: 11.1186,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-62-L-2232-1410-0",
      item_no: 559180,
      item_description: "CHICKEN BREAST HONEY GRILLED",
      pack: 2,
      size: "6.5#",
      item_wgt: 13,
      weekly_mvmt: 34,
      item_cost: 4.59,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-62-L-2232-1410-84",
      item_no: 735826,
      item_description: "HANK'S VANILLA CREAM",
      pack: 6,
      size: "4 PK",
      item_wgt: 33.25,
      weekly_mvmt: 16.5,
      item_cost: 18,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-66-R-2052-1458-0",
      item_no: 351000,
      item_description: "GLOVES VINYL PF LARGE",
      pack: 10,
      size: "100 CT",
      item_wgt: 14.7,
      weekly_mvmt: 439.2,
      item_cost: 16.8,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-66-R-2052-1458-84",
      item_no: 359049,
      item_description: "KEFIR DRINK LF PLAIN",
      pack: 6,
      size: "32 OZ",
      item_wgt: 12,
      weekly_mvmt: 109.4,
      item_cost: 13.4,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-67-L-2232-1470-0",
      item_no: 902585,
      item_description: "T-SACK MARTINS",
      pack: 1000,
      size: "12X7X22",
      item_wgt: 23,
      weekly_mvmt: 587.6,
      item_cost: 16.75,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-67-L-2232-1470-84",
      item_no: 670300,
      item_description: "BAGS BROWN KRAFT 20# SQUAT HD",
      pack: 500,
      size: "8X6X13",
      item_wgt: 31,
      weekly_mvmt: 100,
      item_cost: 18.98,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-6-L-2232-558-0",
      item_no: 834100,
      item_description: "T-SACK-THANK YOU FLAG LOW-D",
      pack: 1000,
      size: "12X7X22",
      item_wgt: 13,
      weekly_mvmt: 36,
      item_cost: 25.57,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-70-R-2052-1506-0",
      item_no: 820700,
      item_description: "ICING CHOCOLATE DONUT",
      pack: 1,
      size: "38#",
      item_wgt: 40,
      weekly_mvmt: 38.8,
      item_cost: 52.1,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-70-R-2052-1506-84",
      item_no: 277300,
      item_description: "HAM VIRGINIA BRAND",
      pack: 2,
      size: "13#",
      item_wgt: 26,
      weekly_mvmt: 142.8,
      item_cost: 2.39,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-71-L-2232-1530-0",
      item_no: 198994,
      item_description: "PEANUTS BLANCH ROASTED SALTED",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 11.2,
      item_cost: 38.54,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-71-L-2232-1530-84",
      item_no: 145018,
      item_description: "POTATO SALAD DEVILED EGG",
      pack: 2,
      size: "8#",
      item_wgt: 16,
      weekly_mvmt: 476.4,
      item_cost: 1.75,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-74-R-2052-1566-0",
      item_no: 416176,
      item_description: "SALAD COUSCOUS FETA AND MINT",
      pack: 2,
      size: "4#",
      item_wgt: 8,
      weekly_mvmt: 36.8,
      item_cost: 2.82,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-74-R-2052-1566-84",
      item_no: 907711,
      item_description: "DOUGH COOKIE EDIBLE CONFETTI",
      pack: 32,
      size: "3.5 OZ",
      item_wgt: 7,
      weekly_mvmt: 56.4,
      item_cost: 35.2,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-75-L-2232-1590-0",
      item_no: 528818,
      item_description: "GUMMI RATTLESNAKE 27 INCH",
      pack: 1,
      size: "20#",
      item_wgt: 20,
      weekly_mvmt: 0,
      item_cost: 44.51,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-75-L-2232-1590-84",
      item_no: 357459,
      item_description: "POTATO SALAD AMERICAN",
      pack: 2,
      size: "5#",
      item_wgt: 10,
      weekly_mvmt: 489.8,
      item_cost: 0.86,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-78-R-2052-1626-0",
      item_no: 831876,
      item_description: "GUMMI PEACH RINGS",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 2.8,
      item_cost: 30.15,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-78-R-2052-1626-84",
      item_no: 868715,
      item_description: "EGG NOG TRADITIONAL",
      pack: 12,
      size: "32 OZ",
      item_wgt: 24,
      weekly_mvmt: 0,
      item_cost: 27,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-79-L-2232-1638-0",
      item_no: 714283,
      item_description: "CHIPS PLANTAIN SALTED",
      pack: 4,
      size: "5#",
      item_wgt: 20,
      weekly_mvmt: 40.8,
      item_cost: 42,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-79-L-2232-1638-84",
      item_no: 190800,
      item_description: "TURKEY BREAST CRK PEP/SEAS",
      pack: 3,
      size: "4#",
      item_wgt: 12,
      weekly_mvmt: 62,
      item_cost: 3.63,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-83-R-2052-1686-0",
      item_no: 663621,
      item_description: "PEAS FRIED SALTED BULK",
      pack: 2,
      size: "11#",
      item_wgt: 22,
      weekly_mvmt: 39.2,
      item_cost: 23.54,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-83-R-2052-1686-84",
      item_no: 221900,
      item_description: "HAM HONEY CURED #12950",
      pack: 3,
      size: "6.5#",
      item_wgt: 19.5,
      weekly_mvmt: 208.4,
      item_cost: 3.41,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-84-L-2232-1698-0",
      item_no: 762558,
      item_description: "TURKEY BREAST JP MESQUITE",
      pack: 2,
      size: "8#",
      item_wgt: 16,
      weekly_mvmt: 39.4,
      item_cost: 3.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-84-L-2232-1698-84",
      item_no: 273900,
      item_description: "SAUERKRAUT 2# POLY",
      pack: 12,
      size: "2#",
      item_wgt: 27,
      weekly_mvmt: 17.8,
      item_cost: 20.82,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-87-R-2052-1734-0",
      item_no: 643380,
      item_description: "BAG BREAD POLY EVA W",
      pack: 1000,
      size: "11X13X3",
      item_wgt: 9.5,
      weekly_mvmt: 39.8,
      item_cost: 21.18,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-87-R-2052-1734-84",
      item_no: 92800,
      item_description: "CHICKEN BREAST BUFFALO",
      pack: 2,
      size: "4#",
      item_wgt: 8,
      weekly_mvmt: 100.8,
      item_cost: 3.63,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-88-L-2232-1758-0",
      item_no: 670800,
      item_description: "BAGS BROWN KRAFT LIQUOR PINT",
      pack: 500,
      size: "4X2X11",
      item_wgt: 7,
      weekly_mvmt: 40.4,
      item_cost: 7.57,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-88-L-2232-1758-84",
      item_no: 232556,
      item_description: "FILM MEAT DIGI",
      pack: 1,
      size: '16"4500',
      item_wgt: 27,
      weekly_mvmt: 15.8,
      item_cost: 52.17,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-8-R-2052-606-84",
      item_no: 715000,
      item_description: "T-SACK-THANK YOU ENVIRO BEIGE",
      pack: 1000,
      size: "13X8X23",
      item_wgt: 22.08,
      weekly_mvmt: 212,
      item_cost: 26.22,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-91-R-2052-1794-0",
      item_no: 714700,
      item_description: "BAGS POP CAN TOMRA 1.3 MIL",
      pack: 100,
      size: "37X52",
      item_wgt: 30.5,
      weekly_mvmt: 10.2,
      item_cost: 35.14,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-91-R-2052-1794-84",
      item_no: 233000,
      item_description: "CAPICOLA HOT",
      pack: 3,
      size: "5#",
      item_wgt: 15,
      weekly_mvmt: 41,
      item_cost: 3.99,
      cases_damaged: 3,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-92-L-2232-1818-0",
      item_no: 861014,
      item_description: "HONEY CURED DELI HAM",
      pack: 4,
      size: "6#",
      item_wgt: 24,
      weekly_mvmt: 5.6,
      item_cost: 3.06,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-92-L-2232-1818-84",
      item_no: 277700,
      item_description: "BOLOGNA CLEVELAND",
      pack: 3,
      size: "12#",
      item_wgt: 36,
      weekly_mvmt: 48.8,
      item_cost: 1.34,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-95-R-2052-1854-0",
      item_no: 358860,
      item_description: 'PIZZA CRUST 12" THIN & CRISPY',
      pack: 12,
      size: "2/16 OZ",
      item_wgt: 24,
      weekly_mvmt: 11,
      item_cost: 34.8,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-95-R-2052-1854-84",
      item_no: 115600,
      item_description: "MUENSTER SQUARE YELLOW*",
      pack: 6,
      size: "5#",
      item_wgt: 36,
      weekly_mvmt: 239.6,
      item_cost: 2.0335,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-96-L-2232-1866-0",
      item_no: 83900,
      item_description: "JALAPENO LOAF",
      pack: 3,
      size: "3.2#",
      item_wgt: 9.6,
      weekly_mvmt: 41.4,
      item_cost: 3.09,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-96-L-2232-1866-84",
      item_no: 615800,
      item_description: "DRESSING REF SLAW",
      pack: 4,
      size: "GALLON",
      item_wgt: 36,
      weekly_mvmt: 57.6,
      item_cost: 37.64,
      cases_damaged: 6,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A10-9-L-2232-618-0",
      item_no: 736600,
      item_description: "TURKEY BREAST MAPLE GLAZED",
      pack: 2,
      size: "7#",
      item_wgt: 14,
      weekly_mvmt: 39.4,
      item_cost: 5.1,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-101-L-180-1926-0",
      item_no: 925687,
      item_description: "POPCORN DRIZZLE SHIPPER",
      pack: 36,
      size: "13.1 OZ",
      item_wgt: 41,
      weekly_mvmt: 8.5,
      item_cost: 73.8,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-101-L-180-1926-60",
      item_no: 359145,
      item_description: "YOGURT PLAIN 0 %",
      pack: 6,
      size: "32 OZ",
      item_wgt: 12,
      weekly_mvmt: 68.6,
      item_cost: 17.16,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-101-R-0-1926-0",
      item_no: 444345,
      item_description: "PEPPERS RED ROASTED",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 45,
      weekly_mvmt: 16.6,
      item_cost: 28.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-101-R-0-1926-60",
      item_no: 530841,
      item_description: "TUB SM GUMMI BEARS ASSORTED",
      pack: 12,
      size: "13 OZ",
      item_wgt: 9.75,
      weekly_mvmt: 66.4,
      item_cost: 18.69,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-105-L-180-1986-0",
      item_no: 766219,
      item_description: "DRINK EXPOSED ALOE & HONEY",
      pack: 12,
      size: "16.9 OZ",
      item_wgt: 12.68,
      weekly_mvmt: 29.2,
      item_cost: 13.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-105-L-180-1986-60",
      item_no: 838130,
      item_description: "PASTA SAUCE MARINARA FULL RED",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 46,
      weekly_mvmt: 7.8,
      item_cost: 25.07,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-105-R-0-1986-0",
      item_no: 409900,
      item_description: "MILK EVAPORATED",
      pack: 6,
      size: "#10",
      item_wgt: 47,
      weekly_mvmt: 10.2,
      item_cost: 47.25,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-105-R-0-1986-60",
      item_no: 359151,
      item_description: "YOGURT FRENCH VANILLA LOW FAT",
      pack: 6,
      size: "32 OZ",
      item_wgt: 12,
      weekly_mvmt: 68.6,
      item_cost: 17.16,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-109-L-180-2046-0",
      item_no: 836758,
      item_description: "PICKLES SPEARS KOSHER",
      pack: 1,
      size: "5 GAL",
      item_wgt: 46,
      weekly_mvmt: 0.4,
      item_cost: 24.73,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-109-L-180-2046-60",
      item_no: 359073,
      item_description: "KEFIR DRINK FF PLAIN",
      pack: 6,
      size: "32 OZ",
      item_wgt: 12,
      weekly_mvmt: 70.2,
      item_cost: 13.4,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-109-R-0-2046-0",
      item_no: 374703,
      item_description: "TUB LG DRIED CRANBERRIES",
      pack: 12,
      size: "13 OZ",
      item_wgt: 10.75,
      weekly_mvmt: 69.4,
      item_cost: 20.27,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-109-R-0-2046-60",
      item_no: 670700,
      item_description: "SACKS BROWN KRAFT",
      pack: 400,
      size: "1/6-75#",
      item_wgt: 56,
      weekly_mvmt: 72,
      item_cost: 32.41,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-100-R-2280-1914-0",
      item_no: 915649,
      item_description: 'CIABATTA 4.5" HAM & HAVARTI',
      pack: 4,
      size: "5 OZ",
      item_wgt: 1.5,
      weekly_mvmt: 32,
      item_cost: 11.49,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-100-R-2280-1914-48",
      item_no: 507449,
      item_description: "GUMMI BEARS WILD CHERRY",
      pack: 4,
      size: "5#",
      item_wgt: 20,
      weekly_mvmt: 23.6,
      item_cost: 21.66,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-101-L-2460-1926-0",
      item_no: 648038,
      item_description: "ICING COUNTRY WHITE ZTF",
      pack: 1,
      size: "28#",
      item_wgt: 28,
      weekly_mvmt: 255.8,
      item_cost: 44.78,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-101-L-2460-1926-60",
      item_no: 358845,
      item_description: 'PIZZA CRUST 12" TRADITIONAL',
      pack: 12,
      size: "2/24 OZ",
      item_wgt: 36,
      weekly_mvmt: 13.6,
      item_cost: 34.8,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-104-R-2280-1962-0",
      item_no: 620005,
      item_description: "CONT CLEAR HINGED PET2OUT1",
      pack: 500,
      size: "5X5X2.7",
      item_wgt: 20.3,
      weekly_mvmt: 10.4,
      item_cost: 42.14,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-104-R-2280-1962-48",
      item_no: 166703,
      item_description: "CHICKEN BREAST RED SODIUM O/R",
      pack: 2,
      size: "4#",
      item_wgt: 8,
      weekly_mvmt: 43.8,
      item_cost: 3.63,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-105-L-2460-1986-60",
      item_no: 188000,
      item_description: "GELATIN STRAWBERRY PARFAIT",
      pack: 2,
      size: "4#",
      item_wgt: 8,
      weekly_mvmt: 57.4,
      item_cost: 0.965,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-107-R-2280-2010-48",
      item_no: 530433,
      item_description: "FILBERTS NATURAL TURKISH",
      pack: 1,
      size: "55#",
      item_wgt: 55,
      weekly_mvmt: 13.8,
      item_cost: 217.33,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-108-R-2280-2022-0",
      item_no: 666100,
      item_description: "BAGS BAKERY ITALIAN DESIGN",
      pack: 1000,
      size: "6X3X18",
      item_wgt: 26.5,
      weekly_mvmt: 4.6,
      item_cost: 49.53,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-108-R-2280-2022-48",
      item_no: 232076,
      item_description: "TOMATO SAUCE",
      pack: 12,
      size: "29 OZ",
      item_wgt: 21.75,
      weekly_mvmt: 36,
      item_cost: 9.73,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-109-L-2460-2046-0",
      item_no: 560336,
      item_description: "WAFERS YELLOW ALPINE",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 0,
      item_cost: 40.25,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-109-L-2460-2046-60",
      item_no: 428926,
      item_description: "CHEESE BLEND DOLLY'S",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 27.2,
      item_cost: 2.067,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-10-R-2280-654-48",
      item_no: 654600,
      item_description: "MALT BALLS JUMBO CHOC COVERED",
      pack: 1,
      size: "20#",
      item_wgt: 20,
      weekly_mvmt: 49,
      item_cost: 35.63,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-111-R-2280-2070-48",
      item_no: 533187,
      item_description: "THIN MINTS DARK CHOCOLATE",
      pack: 36,
      size: "3.5 OZ",
      item_wgt: 10,
      weekly_mvmt: 0,
      item_cost: 27.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-112-R-2280-2082-0",
      item_no: 933051,
      item_description: "JUICE ORANGE 50% LESS SUGAR",
      pack: 6,
      size: "59 OZ",
      item_wgt: 25.75,
      weekly_mvmt: 11.8,
      item_cost: 8.7,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-112-R-2280-2082-48",
      item_no: 251214,
      item_description: "HAM BLACK FOREST W/NAT JUICES",
      pack: 2,
      size: "4.5#",
      item_wgt: 9,
      weekly_mvmt: 75.4,
      item_cost: 4.6,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-113-L-2460-2094-0",
      item_no: 425152,
      item_description: "LEMONADE ORIGINAL",
      pack: 8,
      size: "59 OZ",
      item_wgt: 29.5,
      weekly_mvmt: 166.6,
      item_cost: 12.88,
      cases_damaged: 4,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-113-L-2460-2094-60",
      item_no: 292975,
      item_description: "T-SACK-VALLI PRODUCE",
      pack: 1000,
      size: "11X6X21",
      item_wgt: 17,
      weekly_mvmt: 324.8,
      item_cost: 13.42,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-116-R-2280-2130-48",
      item_no: 205300,
      item_description: "CORNED BEEF RND CAP-OFF#46802",
      pack: 2,
      size: "6#",
      item_wgt: 12,
      weekly_mvmt: 39.4,
      item_cost: 5.88,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-117-R-2280-2142-0",
      item_no: 694533,
      item_description: "DATES PITTED DEGLET NOOR",
      pack: 1,
      size: "20#",
      item_wgt: 20,
      weekly_mvmt: 121.8,
      item_cost: 31,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-117-R-2280-2142-48",
      item_no: 126036,
      item_description: "MOZZARELLA /PROV 50/50 SHRED*",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 251.8,
      item_cost: 2.0235,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-118-L-2460-2154-60",
      item_no: 570417,
      item_description: "ROAST BEEF TOP ROUND MEDIUM",
      pack: 2,
      size: "7-9#",
      item_wgt: 16.82,
      weekly_mvmt: 31.6,
      item_cost: 4.07,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-121-R-2280-2190-0",
      item_no: 201102,
      item_description: "DRESSING REF BLUE CHS SUPREME",
      pack: 4,
      size: "GALLON",
      item_wgt: 31.01,
      weekly_mvmt: 3.8,
      item_cost: 47.86,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-121-R-2280-2190-48",
      item_no: 424400,
      item_description: "SWISS BABY",
      pack: 2,
      size: "5#",
      item_wgt: 10.5,
      weekly_mvmt: 24.2,
      item_cost: 4.06,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-122-L-2460-2214-0",
      item_no: 702700,
      item_description: "CASHEWS 320 RST W/S ALL NATRL",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 20.6,
      item_cost: 145,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-122-L-2460-2214-60",
      item_no: 200000,
      item_description: "TURKEY BREAST OVEN ROASTED",
      pack: 2,
      size: "8#",
      item_wgt: 16,
      weekly_mvmt: 193.4,
      item_cost: 3.63,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-124-R-2280-2238-48",
      item_no: 215892,
      item_description: "CRUMBS GRAHAM CRACKER",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 26.2,
      item_cost: 32.94,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-125-R-2280-2250-0",
      item_no: 943691,
      item_description: "KOMBUCHA HOPPED GRAPEFRUIT OG",
      pack: 12,
      size: "14 OZ",
      item_wgt: 19,
      weekly_mvmt: 34.4,
      item_cost: 21.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-125-R-2280-2250-48",
      item_no: 461685,
      item_description: "WAFERS DARK CHOC FLVD ALPINE",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 15.2,
      item_cost: 34,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-126-L-2460-2274-0",
      item_no: 419423,
      item_description: "CHEESE PIZZA DERBY*",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 8.2,
      item_cost: 2.087,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-126-L-2460-2274-60",
      item_no: 369200,
      item_description: "TURKEY BREAST SUNDRIED TOMATO",
      pack: 3,
      size: "3.5#",
      item_wgt: 10.5,
      weekly_mvmt: 22.8,
      item_cost: 3.6,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-128-R-2280-2298-48",
      item_no: 566864,
      item_description: "TEA FLAVOR PEACH",
      pack: 36,
      size: "8 OZ",
      item_wgt: 31,
      weekly_mvmt: 6.8,
      item_cost: 31.1,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-129-R-2280-2310-0",
      item_no: 957941,
      item_description: "T-SACK-SHOP&SAVE CHICAGO",
      pack: 1000,
      size: "11X6X21",
      item_wgt: 12.92,
      weekly_mvmt: 238,
      item_cost: 13.57,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-129-R-2280-2310-48",
      item_no: 840195,
      item_description: "HOT PEPPER CHEESE LOAF",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 60.8,
      item_cost: 1.7,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-12-L-2460-678-0",
      item_no: 636500,
      item_description: "HAM HONEY TAVERN",
      pack: 1,
      size: "6#",
      item_wgt: 7,
      weekly_mvmt: 82.6,
      item_cost: 4.6,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-12-L-2460-678-60",
      item_no: 389942,
      item_description: "EASTER PASTEL HERSHEY'S MINI",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 0,
      item_cost: 85.25,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-130-L-2460-2322-0",
      item_no: 241000,
      item_description: "HAM DEEP SMOKED BLACK FOREST",
      pack: 1,
      size: "9#",
      item_wgt: 9,
      weekly_mvmt: 114.2,
      item_cost: 4.6,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-130-L-2460-2322-60",
      item_no: 100500,
      item_description: "AMERICAN CHEESE YELLOW",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 1062,
      item_cost: 2.555,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-133-R-2280-2358-48",
      item_no: 218606,
      item_description: "TURKEY BREAST BACON LOVER",
      pack: 1,
      size: "5#",
      item_wgt: 5,
      weekly_mvmt: 46.8,
      item_cost: 5.3,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-134-R-2280-2370-0",
      item_no: 244814,
      item_description: "SALAMI HARD",
      pack: 6,
      size: "4.16#",
      item_wgt: 25,
      weekly_mvmt: 5.4,
      item_cost: 3.41,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-134-R-2280-2370-48",
      item_no: 307500,
      item_description: "T-SACK-GT PIE ENVIRO",
      pack: 1000,
      size: "12X7X22",
      item_wgt: 23,
      weekly_mvmt: 4,
      item_cost: 26.9,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-135-L-2460-2382-60",
      item_no: 926233,
      item_description: "COOKIE DARK MILK CHOC SHP",
      pack: 48,
      size: "4.4 OZ",
      item_wgt: 13.2,
      weekly_mvmt: 7,
      item_cost: 85,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-138-R-2280-2418-0",
      item_no: 267500,
      item_description: "RING MOLD DESSERT PINEAPPL CRM",
      pack: 6,
      size: "19 OZ",
      item_wgt: 8.5,
      weekly_mvmt: 57.8,
      item_cost: 7.2,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-138-R-2280-2418-48",
      item_no: 443308,
      item_description: "BEANS CANNELINNI WHITE KIDNEY",
      pack: 1,
      size: "55#",
      item_wgt: 55,
      weekly_mvmt: 5.6,
      item_cost: 33,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-113-L-180-2094-60",
      item_no: 722200,
      item_description: "PIZZA SAUCE SUPER HVY W BASIL",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 45.9,
      weekly_mvmt: 10.6,
      item_cost: 19.68,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-113-R-0-2094-0",
      item_no: 601645,
      item_description: "BEANS GREEN CUT 4 SV",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 39,
      weekly_mvmt: 89.4,
      item_cost: 19.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-113-R-0-2094-60",
      item_no: 828813,
      item_description: "COLBY MINI HORN*",
      pack: 2,
      size: "6#",
      item_wgt: 12.06,
      weekly_mvmt: 73,
      item_cost: 2.1475,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-140-L-2460-2442-0",
      item_no: 394960,
      item_description: "TOFFEE ASSORTED FOIL WRAPPED",
      pack: 1,
      size: "30#",
      item_wgt: 30,
      weekly_mvmt: 5.6,
      item_cost: 47.33,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-140-L-2460-2442-60",
      item_no: 764553,
      item_description: "KOMBUCHA LEMONGRASS GINGER",
      pack: 12,
      size: "16 OZ",
      item_wgt: 12,
      weekly_mvmt: 21.6,
      item_cost: 26.45,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-142-R-2280-2466-48",
      item_no: 827826,
      item_description: "PEPPERONI SLICED BULK",
      pack: 2,
      size: "12.5#",
      item_wgt: 25,
      weekly_mvmt: 56,
      item_cost: 3.1075,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-143-R-2280-2478-0",
      item_no: 531249,
      item_description: "WAFER DARK GREEN",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 0,
      item_cost: 40.25,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-143-R-2280-2478-48",
      item_no: 375580,
      item_description: "JELLY BEANS",
      pack: 1,
      size: "31#",
      item_wgt: 31,
      weekly_mvmt: 0,
      item_cost: 28.71,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-145-L-2460-2502-0",
      item_no: 840244,
      item_description: "CHEDDAR PURE SHREDDED*",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 19,
      item_cost: 1.8181,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-145-L-2460-2502-60",
      item_no: 110500,
      item_description: "MOZZARELLA WHOLE MILK SHRED",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 18.8,
      item_cost: 2.608,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-147-R-2280-2526-48",
      item_no: 437834,
      item_description: "T-SACK-WEBSTERS PNS",
      pack: 1000,
      size: "12X7X21",
      item_wgt: 17.2,
      weekly_mvmt: 36,
      item_cost: 19.77,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-148-R-2280-2538-0",
      item_no: 667302,
      item_description: "SACKS HAND UP-STOCK PRNT PLAIN",
      pack: 300,
      size: "1/6-70#",
      item_wgt: 47,
      weekly_mvmt: 16.2,
      item_cost: 34.03,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-148-R-2280-2538-48",
      item_no: 681443,
      item_description: "HAM WHOLE CHERRY WOOD",
      pack: 4,
      size: "6 #",
      item_wgt: 24,
      weekly_mvmt: 0,
      item_cost: 3.19,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-149-L-2460-2550-0",
      item_no: 291734,
      item_description: "BUTTER UNSALTED QUARTERS*",
      pack: 36,
      size: "1#",
      item_wgt: 36,
      weekly_mvmt: 23.2,
      item_cost: 2.8225,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-149-L-2460-2550-60",
      item_no: 443563,
      item_description: "SAUSAGE RSTD GARLIC & GRUYERE",
      pack: 8,
      size: "12 OZ",
      item_wgt: 6,
      weekly_mvmt: 34,
      item_cost: 28.8,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-14-R-2280-714-0",
      item_no: 828029,
      item_description: "ICE CREAM MIX VAN BRUSTERS",
      pack: 2,
      size: "2.5 GAL",
      item_wgt: 46,
      weekly_mvmt: 767,
      item_cost: 43.59,
      cases_damaged: 4,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-14-R-2280-714-48",
      item_no: 825200,
      item_description: "BAGS WIND BROWN ROUND BREAD",
      pack: 1000,
      size: "9X3X14",
      item_wgt: 23,
      weekly_mvmt: 1.6,
      item_cost: 56.1,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-152-R-2280-2586-48",
      item_no: 632517,
      item_description: "SACKS HAND DN-VALLI",
      pack: 300,
      size: "6-Jan",
      item_wgt: 43,
      weekly_mvmt: 90,
      item_cost: 31,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-153-R-2280-2598-0",
      item_no: 281000,
      item_description: "FOOTBALL LOAF",
      pack: 1,
      size: "8#",
      item_wgt: 8,
      weekly_mvmt: 77.6,
      item_cost: 3.09,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-153-R-2280-2598-48",
      item_no: 771600,
      item_description: "MARGARINE/BUTTER LIQUID NH",
      pack: 2,
      size: "17.5#",
      item_wgt: 35,
      weekly_mvmt: 25.6,
      item_cost: 26.26,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-154-L-2460-2610-0",
      item_no: 607015,
      item_description: "HALLOWEEN GUMMI WORMS",
      pack: 4,
      size: "5#",
      item_wgt: 22,
      weekly_mvmt: 17,
      item_cost: 22.51,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-154-L-2460-2610-60",
      item_no: 291751,
      item_description: "BUTTER SALTED QUARTERS*",
      pack: 36,
      size: "1#",
      item_wgt: 36,
      weekly_mvmt: 83.4,
      item_cost: 2.8025,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-157-R-2280-2646-0",
      item_no: 358539,
      item_description: "NOODLES EGG MEDIUM",
      pack: 12,
      size: "16 OZ",
      item_wgt: 12,
      weekly_mvmt: 58.2,
      item_cost: 20.27,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-157-R-2280-2646-48",
      item_no: 831927,
      item_description: "GUMMI BEARS SOUR NEON",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 10,
      item_cost: 30,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-159-L-2460-2670-0",
      item_no: 980741,
      item_description: "GOUDA SMOKED KOSHER BAR NY",
      pack: 12,
      size: "8 OZ",
      item_wgt: 6,
      weekly_mvmt: 20.2,
      item_cost: 27.9,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-15-L-2460-726-0",
      item_no: 125636,
      item_description: "MOZZARELLA PART SKIM LOAF*",
      pack: 8,
      size: "6#",
      item_wgt: 48,
      weekly_mvmt: 153.6,
      item_cost: 1.8535,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-15-L-2460-726-60",
      item_no: 582878,
      item_description: "TURKEY BREAST HONEY ROASTED",
      pack: 2,
      size: "8-10#",
      item_wgt: 19.3,
      weekly_mvmt: 72.8,
      item_cost: 2.7,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-161-R-2280-2694-48",
      item_no: 495532,
      item_description: "GUMMI BEARS",
      pack: 1,
      size: "30#",
      item_wgt: 30,
      weekly_mvmt: 7.8,
      item_cost: 29.55,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-162-R-2280-2706-0",
      item_no: 216400,
      item_description: "PARMESAN SHREDDED",
      pack: 4,
      size: "5#",
      item_wgt: 20,
      weekly_mvmt: 92.2,
      item_cost: 3.4,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-162-R-2280-2706-48",
      item_no: 531317,
      item_description: "WAFER WHITE PEPPERMINT BURST",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 0,
      item_cost: 37.75,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-164-L-2460-2730-0",
      item_no: 841728,
      item_description: "MOZZARELLA PART SKIM CHSE*",
      pack: 8,
      size: "6#",
      item_wgt: 50.04,
      weekly_mvmt: 20.2,
      item_cost: 1.8405,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-164-L-2460-2730-60",
      item_no: 961761,
      item_description: "CUP BUDDY SLEEVE SOHO RSK20",
      pack: 1200,
      size: "12-20OZ",
      item_wgt: 24,
      weekly_mvmt: 5.2,
      item_cost: 62.23,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-166-R-2280-2754-48",
      item_no: 433403,
      item_description: "JUICE LEMON FROM CONCENTRATE",
      pack: 12,
      size: "32 OZ.",
      item_wgt: 26,
      weekly_mvmt: 38.8,
      item_cost: 12.11,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-167-R-2280-2766-0",
      item_no: 620029,
      item_description: "CONT CLEAR HINGED TAMP CH8DEF",
      pack: 200,
      size: "8 OZ",
      item_wgt: 8.4,
      weekly_mvmt: 31.6,
      item_cost: 18.4,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-167-R-2280-2766-48",
      item_no: 617591,
      item_description: "ICED COFFEE COLD BREW MOCHA",
      pack: 6,
      size: "48 OZ",
      item_wgt: 18,
      weekly_mvmt: 0,
      item_cost: 21.42,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-168-L-2460-2778-0",
      item_no: 582600,
      item_description: "SUPER HOT PEPPER CHEESE WISC",
      pack: 2,
      size: "5#",
      item_wgt: 10,
      weekly_mvmt: 59.2,
      item_cost: 2.925,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-168-L-2460-2778-60",
      item_no: 115000,
      item_description: "MOZZARELLA PART SKIM DICED",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 12.8,
      item_cost: 2.608,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-16-R-2280-762-48",
      item_no: 370025,
      item_description: "COTTAGE CHEESE LOW FAT",
      pack: 6,
      size: "24 OZ",
      item_wgt: 9,
      weekly_mvmt: 341.2,
      item_cost: 12.5812,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-171-R-2280-2814-48",
      item_no: 200802,
      item_description: "SAUCE HONEY MUSTARD DIP CUP",
      pack: 100,
      size: "1.5 OZ",
      item_wgt: 9.37,
      weekly_mvmt: 24.8,
      item_cost: 16.89,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-172-R-2280-2826-48",
      item_no: 101468,
      item_description: "T-SACK-ENVIRO RAINBOW ECONO",
      pack: 1000,
      size: "12X7X21",
      item_wgt: 12,
      weekly_mvmt: 102,
      item_cost: 14.78,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-173-L-2460-2838-60",
      item_no: 479900,
      item_description: "BAGS BAKERY-FRENCH EXPRESSION",
      pack: 500,
      size: "4X3X28",
      item_wgt: 30,
      weekly_mvmt: 4.2,
      item_cost: 32.09,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-176-R-2280-2874-36",
      item_no: 681460,
      item_description: "HAM HALF CHERRY WOOD",
      pack: 8,
      size: "3 #",
      item_wgt: 24,
      weekly_mvmt: 0,
      item_cost: 3.19,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-176-R-2280-2874-48",
      item_no: 153021,
      item_description: "MOZZARELLA FRESH MARINATED CUP",
      pack: 6,
      size: "12 OZ",
      item_wgt: 10.75,
      weekly_mvmt: 64.2,
      item_cost: 17.79,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-17-R-2280-774-0",
      item_no: 629627,
      item_description: "PASTA CHICKPEA ROTINI",
      pack: 6,
      size: "8 OZ",
      item_wgt: 3,
      weekly_mvmt: 51.6,
      item_cost: 13.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-17-R-2280-774-48",
      item_no: 533136,
      item_description: "HOT DOGS VALUE pack 8 LINKS",
      pack: 32,
      size: "12 OZ",
      item_wgt: 24,
      weekly_mvmt: 27.6,
      item_cost: 22.32,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-181-R-2280-2934-36",
      item_no: 828022,
      item_description: "ICE CREAM MIX CHOC BRUSTERS",
      pack: 2,
      size: "2.5 GAL",
      item_wgt: 46,
      weekly_mvmt: 210.4,
      item_cost: 46.51,
      cases_damaged: 2,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-18-L-2460-786-0",
      item_no: 839594,
      item_description: "PUMPKIN SPICE CARAMELS",
      pack: 1,
      size: "23#",
      item_wgt: 21.62,
      weekly_mvmt: 0,
      item_cost: 33.95,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-18-L-2460-786-60",
      item_no: 256902,
      item_description: "MELLO CREME MIX FALL FESTIVAL",
      pack: 1,
      size: "30#",
      item_wgt: 31,
      weekly_mvmt: 19,
      item_cost: 30.5,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-118-L-180-2154-0",
      item_no: 730100,
      item_description: "BEANS BAKED ORIGINAL 117 OZ",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 43.875,
      weekly_mvmt: 77.6,
      item_cost: 31.15,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-118-L-180-2154-60",
      item_no: 937923,
      item_description: "BASE NY CHEESECAKE",
      pack: 1,
      size: "50#",
      item_wgt: 50,
      weekly_mvmt: 2.3,
      item_cost: 72,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-118-R-0-2154-0",
      item_no: 602953,
      item_description: "BREADING CRUNCHY MIX",
      pack: 1,
      size: "25#",
      item_wgt: 26,
      weekly_mvmt: 75.2,
      item_cost: 27.83,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-118-R-0-2154-60",
      item_no: 308041,
      item_description: "OIL CORN 100%  ZTF",
      pack: 1,
      size: "35#",
      item_wgt: 35,
      weekly_mvmt: 67.6,
      item_cost: 23.86,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-1-L-2460-390-0",
      item_no: 916700,
      item_description: "T-SACK-OLESONS MKTS",
      pack: 1000,
      size: "12X7X22",
      item_wgt: 16.32,
      weekly_mvmt: 63,
      item_cost: 24.94,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-1-L-2460-390-60",
      item_no: 293805,
      item_description: "TURKEY BREAST EXTREME CAJUN",
      pack: 3,
      size: "4.5#",
      item_wgt: 12,
      weekly_mvmt: 78.4,
      item_cost: 3.63,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-1-R-2280-390-0",
      item_no: 616500,
      item_description: "PAN LINER NAT QUILON 1-2 BAKE",
      pack: 1000,
      size: "16X24",
      item_wgt: 23.6,
      weekly_mvmt: 18,
      item_cost: 30.95,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-1-R-2280-390-48",
      item_no: 919709,
      item_description: "ICING BASE SMOOTH 'N LIGHT ZTF",
      pack: 1,
      size: "45#",
      item_wgt: 45,
      weekly_mvmt: 34.4,
      item_cost: 52.37,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-122-L-180-2214-60",
      item_no: 879056,
      item_description: "PANINO PEPPERONI 2PK",
      pack: 16,
      size: "1.5 OZ",
      item_wgt: 1.5,
      weekly_mvmt: 80.4,
      item_cost: 16.48,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-22-R-2280-870-48",
      item_no: 119002,
      item_description: "PEANUTS DD DARK CHOC",
      pack: 1,
      size: "30#",
      item_wgt: 30,
      weekly_mvmt: 19,
      item_cost: 68,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-122-R-0-2214-0",
      item_no: 603815,
      item_description: "GUMMI PEACHES BULK",
      pack: 6,
      size: "5#",
      item_wgt: 30,
      weekly_mvmt: 6.5,
      item_cost: 56.06,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-122-R-0-2214-60",
      item_no: 608700,
      item_description: "BOX HOT FOOD-EXPRESSIONS",
      pack: 250,
      size: "7X4X2.7",
      item_wgt: 17.7,
      weekly_mvmt: 79.8,
      item_cost: 37.49,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-23-R-2280-882-0",
      item_no: 831186,
      item_description: "COCONUT MEDIUM UNSWEETNED",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 7,
      item_cost: 36.644,
      cases_damaged: 1,
      color_cases_damaged: "red",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-23-R-2280-882-48",
      item_no: 595400,
      item_description: "BAGS HOT TO GO TIN TIE LARGE",
      pack: 250,
      size: "8X5X12",
      item_wgt: 20.5,
      weekly_mvmt: 4.8,
      item_cost: 79.35,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-24-L-2460-906-60",
      item_no: 449316,
      item_description: "PUMPKINS SOUR JELLY",
      pack: 1,
      size: "30#",
      item_wgt: 32,
      weekly_mvmt: 0,
      item_cost: 37.4,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-126-L-180-2274-0",
      item_no: 201300,
      item_description: "MOZZARELLA FRESH BOCCONCINI",
      pack: 6,
      size: "7 OZ",
      item_wgt: 2.625,
      weekly_mvmt: 85,
      item_cost: 9.7387,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-126-L-180-2274-60",
      item_no: 596018,
      item_description: "FETA CHEESE IN BRINE",
      pack: 1,
      size: "27#",
      item_wgt: 27,
      weekly_mvmt: 46.2,
      item_cost: 1.8005,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-26-R-2280-930-48",
      item_no: 598953,
      item_description: "RAISIN JUMBO CHOCOLATE MILK",
      pack: 1,
      size: "25#",
      item_wgt: 25,
      weekly_mvmt: 9.4,
      item_cost: 71.33,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-126-R-0-2274-0",
      item_no: 691711,
      item_description: "CHEESE SINGLES AMERICAN",
      pack: 48,
      size: "12 OZ",
      item_wgt: 36,
      weekly_mvmt: 22.6,
      item_cost: 64.13,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-126-R-0-2274-60",
      item_no: 357542,
      item_description: "TUB LG POWER MIX WITH M&M",
      pack: 12,
      size: "15 OZ",
      item_wgt: 12.25,
      weekly_mvmt: 83.2,
      item_cost: 35.36,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-27-R-2280-942-0",
      item_no: 831354,
      item_description: "BAG BRUSTERS WHITE SHOPPING",
      pack: 1,
      size: "250 CT",
      item_wgt: 26,
      weekly_mvmt: 1.2,
      item_cost: 85.19,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-27-R-2280-942-48",
      item_no: 719132,
      item_description: "TACO SEASON POUCH SHIPPER",
      pack: 54,
      size: "SHIPPER",
      item_wgt: 27,
      weekly_mvmt: 0,
      item_cost: 79.83,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A1-12-L-180-678-60",
      item_no: 731500,
      item_description: "BEANS & PORK 112 OZ",
      pack: 6,
      size: "#10 CAN",
      item_wgt: 42,
      weekly_mvmt: 22.4,
      item_cost: 21.35,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
    {
      location: "A11-2-R-2280-438-48",
      item_no: 881938,
      item_description: "PROSCIUTTO BONELESS GOLD",
      pack: 2,
      size: "12#",
      item_wgt: 12,
      weekly_mvmt: 22.4,
      item_cost: 5.38,
      cases_damaged: 0,
      color_cases_damaged: "green",
      link_: "http://yourURL?location=",
    },
  ]);

  await vnistDB.close();

  console.log("End init inventory warehouse database!");
};

initInventoryWarehouseData().catch((err) => {
  console.log(err);
  process.exit(0);
});
