export const manufacturingRoutingConstants = {
    GET_ALL_MANUFACTURING_ROUTINGS_REQUEST: 'GET_ALL_MANUFACTURING_ROUTINGS_REQUEST',
    GET_ALL_MANUFACTURING_ROUTINGS_SUCCESS: 'GET_ALL_MANUFACTURING_ROUTINGS_SUCCESS',
    GET_ALL_MANUFACTURING_ROUTINGS_FAILURE: 'GET_ALL_MANUFACTURING_ROUTINGS_FAILURE',

    GET_DETAIL_MANUFACTURING_ROUTING_REQUEST: 'GET_DETAIL_MANUFACTURING_ROUTING_REQUEST',
    GET_DETAIL_MANUFACTURING_ROUTING_SUCCESS: 'GET_DETAIL_MANUFACTURING_ROUTING_SUCCESS',
    GET_DETAIL_MANUFACTURING_ROUTING_FAILURE: 'GET_DETAIL_MANUFACTURING_ROUTING_FAILURE',    

    CREATE_MANUFACTURING_ROUTING_REQUEST: 'CREATE_MANUFACTURING_ROUTING_REQUEST',
    CREATE_MANUFACTURING_ROUTING_SUCCESS: 'CREATE_MANUFACTURING_ROUTING_SUCCESS',
    CREATE_MANUFACTURING_ROUTING_FAILURE: 'CREATE_MANUFACTURING_ROUTING_FAILURE',

    GET_ALL_MANUFACTURING_ROUTINGS_BY_GOOD_REQUEST: 'GET_ALL_MANUFACTURING_ROUTINGS_BY_GOOD_REQUEST',
    GET_ALL_MANUFACTURING_ROUTINGS_BY_GOOD_SUCCESS: 'GET_ALL_MANUFACTURING_ROUTINGS_BY_GOOD_SUCCESS',
    GET_ALL_MANUFACTURING_ROUTINGS_BY_GOOD_FAILURE: 'GET_ALL_MANUFACTURING_ROUTINGS_BY_GOOD_FAILURE',

}
