export const AssetLotConstants = {
    GETALL_REQUEST: 'ASSET_LOT_GETALL_REQUEST',
    GETALL_SUCCESS: 'ASSET_LOT_GETALL_SUCCESS',
    GETALL_FAILURE: 'ASSET_LOT_GETALL_FAILURE',

    CREATE_ASSETLOT_REQUEST: 'CREATE_ASSETLOT_REQUEST',
    CREATE_ASSETLOT_SUCCESS: 'CREATE_ASSETLOT_SUCCESS',
    CREATE_ASSETLOT_FAILURE: 'CREATE_ASSETLOT_FAILURE',

    UPDATE_ASSETLOT_REQUEST: 'UPDATE_ASSETLOT_REQUEST',
    UPDATE_ASSETLOT_SUCCESS: 'UPDATE_ASSETLOT_SUCCESS',
    UPDATE_ASSETLOT_FAILURE: 'UPDATE_ASSETLOT_FAILURE',

    DELETE_ASSETLOT_REQUEST: 'DELETE_ASSETLOT_REQUEST',
    DELETE_ASSETLOT_SUCCESS: 'DELETE_ASSETLOT_SUCCESS',
    DELETE_ASSETLOT_FAILURE: 'DELETE_ASSETLOT_FAILURE',

    TEST_ACTION : "TEST_ACTION"
};