export const policyConstants = {
  GET_ALL_DELEGATION_POLICIES_REQUEST: 'GET_ALL_DELEGATION_POLICIES_REQUEST',
  GET_ALL_DELEGATION_POLICIES_SUCCESS: 'GET_ALL_DELEGATION_POLICIES_SUCCESS',
  GET_ALL_DELEGATION_POLICIES_FAILURE: 'GET_ALL_DELEGATION_POLICIES_FAILURE',

  DELETE_DELEGATION_POLICY_REQUEST: 'DELETE_DELETE_DELEGATION_POLICY_REQUEST',
  DELETE_DELEGATION_POLICY_SUCCESS: 'DELETE_DELEGATION_POLICY_SUCCESS',
  DELETE_DELEGATION_POLICY_FAILURE: 'DELETE_DELEGATION_POLICY_FAILURE',

  CREATE_DELEGATION_POLICY_REQUEST: 'CREATE_DELEGATION_POLICY_REQUEST',
  CREATE_DELEGATION_POLICY_SUCCESS: 'CREATE_DELEGATION_POLICY_SUCCESS',
  CREATE_DELEGATION_POLICY_FAILURE: 'CREATE_DELEGATION_POLICY_FAILURE',

  EDIT_DELEGATION_POLICY_REQUEST: 'EDIT_DELEGATION_POLICY_REQUEST',
  EDIT_DELEGATION_POLICY_SUCCESS: 'EDIT_DELEGATION_POLICY_SUCCESS',
  EDIT_DELEGATION_POLICY_FAILURE: 'EDIT_DELEGATION_POLICY_FAILURE',

  GET_DETAILED_DELEGATION_POLICY_BY_ID_REQUEST: 'GET_DETAILED_DELEGATION_POLICY_BY_ID_REQUEST',
  GET_DETAILED_DELEGATION_POLICY_BY_ID_SUCCESS: 'GET_DETAILED_DELEGATION_POLICY_BY_ID_SUCCESS',
  GET_DETAILED_DELEGATION_POLICY_BY_ID_FAILURE: 'GET_DETAILED_DELEGATION_POLICY_BY_ID_FAILURE',

  GET_DELEGATION_POLICY_BY_ID_REQUEST: 'GET_DELEGATION_POLICY_BY_ID_REQUEST',
  GET_DELEGATION_POLICY_BY_ID_SUCCESS: 'GET_DELEGATION_POLICY_BY_ID_SUCCESS',
  GET_DELEGATION_POLICY_BY_ID_FAILURE: 'GET_DELEGATION_POLICY_BY_ID_FAILURE'
}
