export const purchasingRequestConstants = {
    GET_ALL_PURCHASING_REQUEST_REQUEST: 'GET_ALL_PURCHASING_REQUEST_REQUEST',
    GET_ALL_PURCHASING_REQUEST_SUCCESS: 'GET_ALL_PURCHASING_REQUEST_SUCCESS',
    GET_ALL_PURCHASING_REQUEST_FAILURE: 'GET_ALL_PURCHASING_REQUEST_FAILURE'
}