export const EmployeeConstants = {
  GET_ALL_EMPLOYEE_REQUEST: 'GET_ALL_EMPLOYEE_REQUEST',
  GET_ALL_EMPLOYEE_SUCCESS: 'GET_ALL_EMPLOYEE_SUCCESS',
  GET_ALL_EMPLOYEE_FAILURE: 'GET_ALL_EMPLOYEE_FAILURE',
  CONFIRM_EMPLOYEE_REQUEST: 'CONFIRM_EMPLOYEE_REQUEST',
  CONFIRM_EMPLOYEE_SUCCESS: 'CONFIRM_EMPLOYEE_SUCCESS',
  CONFIRM_EMPLOYEE_FAILURE: 'CONFIRM_EMPLOYEE_FAILURE',
  REMOVE_EMPLOYEE_REQUEST: 'REMOVE_EMPLOYEE_REQUEST',
  REMOVE_EMPLOYEE_SUCCESS: 'REMOVE_EMPLOYEE_SUCCESS',
  REMOVE_EMPLOYEE_FAILURE: 'REMOVE_EMPLOYEE_FAILURE'
}
