services:
  init-db:
    image: node:alpine
    depends_on:
      - database
    env_file:
      - ./${DATABASE_SERVICE_DIR}/.env
    volumes:
      - ./${DATABASE_SERVICE_DIR}:/app
      - ./${DATABASE_SERVICE_DIR}/node_modules:/app/node_modules
    command: sh -c "cd /app && npm install -f && npm run init"
    networks:
      - vnist-network
