export const DiscountConstants = {
    GET_ALL_DISCOUNTS_REQUEST: 'GET_ALL_DISCOUNTS_REQUEST',
    GET_ALL_DISCOUNTS_SUCCESS: 'GET_ALL_DISCOUNTS_SUCCESS',
    GET_ALL_DISCOUNTS_FAILURE: 'GET_ALL_DISCOUNTS_FAILURE',

    CREATE_DISCOUNT_REQUEST: 'CREATE_DISCOUNT_REQUEST',
    CREATE_DISCOUNT_SUCCESS: 'CREATE_DISCOUNT_SUCCESS',
    CREATE_DISCOUNT_FAILURE: 'CREATE_DISCOUNT_FAILURE',

    GET_DETAIL_DISCOUNT_REQUEST: 'GET_DETAIL_DISCOUNT_REQUEST',
    GET_DETAIL_DISCOUNT_FAILURE: 'GET_DETAIL_DISCOUNT_FAILURE',
    GET_DETAIL_DISCOUNT_SUCCESS: 'GET_DETAIL_DISCOUNT_SUCCESS',

    UPDATE_DISCOUNT_REQUEST: 'UPDATE_DISCOUNT_REQUEST',
    UPDATE_DISCOUNT_SUCCESS: 'UPDATE_DISCOUNT_SUCCESS',
    UPDATE_DISCOUNT_FAILURE: 'UPDATE_DISCOUNT_FAILURE',

    DISABLE_DISCOUNT_REQUEST: 'DISABLE_DISCOUNT_REQUEST',
    DISABLE_DISCOUNT_SUCCESS: 'DISABLE_DISCOUNT_SUCCESS',
    DISABLE_DISCOUNT_FAILURE: 'DISABLE_DISCOUNT_FAILURE',

    CHECK_DISCOUNT_CODE_REQUEST: 'CHECK_DISCOUNT_CODE_REQUEST',
    CHECK_DISCOUNT_CODE_SUCCESS: 'CHECK_DISCOUNT_CODE_SUCCESS',
    CHECK_DISCOUNT_CODE_FAILURE: 'CHECK_DISCOUNT_CODE_FAILURE',

    GET_DISCOUNT_BY_CODE_REQUEST: 'GET_DISCOUNT_BY_CODE_REQUEST',
    GET_DISCOUNT_BY_CODE_SUCCESS: 'GET_DISCOUNT_BY_CODE_SUCCESS',
    GET_DISCOUNT_BY_CODE_FAILURE: 'GET_DISCOUNT_BY_CODE_FAILURE',
}