export const BiddingPackageConstant  = {
    GET_BIDDING_PACKAGE_REQUEST: 'GET_BIDDING_PACKAGE_REQUEST',
    GET_BIDDING_PACKAGE_SUCCESS: 'GET_BIDDING_PACKAGE_SUCCESS',
    GET_BIDDING_PACKAGE_FAILURE: 'GET_BIDDING_PACKAGE_FAILURE',

    CREATE_BIDDING_PACKAGE_REQUEST: 'CREATE_NEW_BIDDING_PACKAGE_REQUEST',
    CREATE_BIDDING_PACKAGE_SUCCESS: 'CREATE_NEW_BIDDING_PACKAGE_SUCCESS',
    CREATE_BIDDING_PACKAGE_FAILURE: 'CREATE_NEW_BIDDING_PACKAGE_FAILURE',

    DELETE_BIDDING_PACKAGE_REQUEST: 'DELETE_BIDDING_PACKAGE_REQUEST',
    DELETE_BIDDING_PACKAGE_SUCCESS:  'DELETE_BIDDING_PACKAGE_SUCCESS',
    DELETE_BIDDING_PACKAGE_FAILURE:  'DELETE_BIDDING_PACKAGE_FAILURE',

    UPDATE_BIDDING_PACKAGE_REQUEST: 'UPDATE_BIDDING_PACKAGE_REQUEST',
    UPDATE_BIDDING_PACKAGE_SUCCESS: 'UPDATE_BIDDING_PACKAGE_SUCCESS',
    UPDATE_BIDDING_PACKAGE_FAILURE: 'UPDATE_BIDDING_PACKAGE_FAILURE',
};