export const ProjectConstants = {
    GET_PROJECTS_REQUEST: 'GET_PROJECTS_REQUEST',
    GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
    GET_PROJECTS_FAILE: 'GET_PROJECTS_FAILE',

    CREATE_PROJECTS_REQUEST: 'CREATE_PROJECTS_REQUEST',
    CREATE_PROJECTS_SUCCESS: 'CREATE_PROJECTS_SUCCESS',
    CREATE_PROJECTS_FAILE: 'CREATE_PROJECTS_FAILE',

    EDIT_PROJECTS_REQUEST: 'EDIT_PROJECTS_REQUEST',
    EDIT_PROJECTS_SUCCESS: 'EDIT_PROJECTS_SUCCESS',
    EDIT_PROJECTS_FAILE: 'EDIT_PROJECTS_FAILE',


    DELETE_PROJECTS_REQUEST: 'DELETE_PROJECTS_REQUEST',
    DELETE_PROJECTS_SUCCESS: 'DELETE_PROJECTS_SUCCESS',
    DELETE_PROJECTS_FAILE: 'DELETE_PROJECTS_FAILE',

    GET_UNITS_REQUEST: 'GET_UNITS_REQUEST',
    GET_UNITS_SUCCESS: 'GET_UNITS_SUCCESS',
    GET_UNITS_FAILE: 'GET_UNITS_FAILE',

    GET_LIST_TASKS_EVAL: 'GET_LIST_TASKS_EVAL',
    GET_LIST_TASKS_EVAL_SUCCESS: 'GET_LIST_TASKS_EVAL_SUCCESS',
    GET_LIST_TASKS_EVAL_FAILE: 'GET_LIST_TASKS_EVAL_FAILE',

    ADD_PROJECT_TASKS_CPM: 'ADD_PROJECT_TASKS_CPM',
    ADD_PROJECT_TASKS_CPM_SUCCESS: 'ADD_PROJECT_TASKS_CPM_SUCCESS',
    ADD_PROJECT_TASKS_CPM_FAILE: 'ADD_PROJECT_TASKS_CPM_FAILE',

    GET_SALARY_MEMBER: 'GET_SALARY_MEMBER',
    GET_SALARY_MEMBER_SUCCESS: 'GET_SALARY_MEMBER_SUCCESS',
    GET_SALARY_MEMBER_FAILE: 'GET_SALARY_MEMBER_FAILE',

    GET_CHANGE_REQUESTS_LIST: 'GET_CHANGE_REQUESTS_LIST',
    GET_CHANGE_REQUESTS_LIST_SUCCESS: 'GET_CHANGE_REQUESTS_LIST_SUCCESS',
    GET_CHANGE_REQUESTS_LIST_FAILE: 'GET_CHANGE_REQUESTS_LIST_FAILE',

    CREATE_PROJECT_CHANGE_REQUEST: 'CREATE_PROJECT_CHANGE_REQUEST',
    CREATE_PROJECT_CHANGE_REQUEST_SUCCESS: 'CREATE_PROJECT_CHANGE_REQUEST_SUCCESS',
    CREATE_PROJECT_CHANGE_REQUEST_FAILE: 'CREATE_PROJECT_CHANGE_REQUEST_FAILE',

    UPDATE_STATUS_PROJECT_CHANGE_REQUEST: 'UPDATE_STATUS_PROJECT_CHANGE_REQUEST',
    UPDATE_STATUS_PROJECT_CHANGE_REQUEST_SUCCESS: 'UPDATE_STATUS_PROJECT_CHANGE_REQUEST_SUCCESS',
    UPDATE_STATUS_PROJECT_CHANGE_REQUEST_FAILE: 'UPDATE_STATUS_PROJECT_CHANGE_REQUEST_FAILE',
    
    GET_LIST_PROJECT_CHANGE_REQUESTS: 'GET_LIST_PROJECT_CHANGE_REQUESTS',
    GET_LIST_PROJECT_CHANGE_REQUESTS_SUCCESS: 'GET_LIST_PROJECT_CHANGE_REQUESTS_SUCCESS',
    GET_LIST_PROJECT_CHANGE_REQUESTS_FAILE: 'GET_LIST_PROJECT_CHANGE_REQUESTS_FAILE',
}