const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const generator = require('generate-password');
const Models = require('../models');
const { Privilege, Role, User, Company, Employee, UserRole, Delegation } = Models;
const fs = require('fs');
const { connect, initModels } = require('../helpers/dbHelper');
const { sendEmail } = require('../helpers/emailHelper');
const { validateEmailValid } = require('../helpers/validationHelper');
const DelegationService = require('../services/delegation');
const { getDbConnection } = require('../database')
