export const CareerPositionConstant  = {
    GET_CAREER_POSITION_REQUEST: 'GET_CAREER_POSITION_REQUEST',
    GET_CAREER_POSITION_SUCCESS: 'GET_CAREER_POSITION_SUCCESS',
    GET_CAREER_POSITION_FAILURE: 'GET_CAREER_POSITION_FAILURE',

    CREATE_CAREER_POSITION_REQUEST: 'CREATE_NEW_CAREER_POSITION_REQUEST',
    CREATE_CAREER_POSITION_SUCCESS: 'CREATE_NEW_CAREER_POSITION_SUCCESS',
    CREATE_CAREER_POSITION_FAILURE: 'CREATE_NEW_CAREER_POSITION_FAILURE',

    DELETE_CAREER_POSITION_REQUEST: 'DELETE_CAREER_POSITION_REQUEST',
    DELETE_CAREER_POSITION_SUCCESS:  'DELETE_CAREER_POSITION_SUCCESS',
    DELETE_CAREER_POSITION_FAILURE:  'DELETE_CAREER_POSITION_FAILURE',

    UPDATE_CAREER_POSITION_REQUEST: 'UPDATE_CAREER_POSITION_REQUEST',
    UPDATE_CAREER_POSITION_SUCCESS: 'UPDATE_CAREER_POSITION_SUCCESS',
    UPDATE_CAREER_POSITION_FAILURE: 'UPDATE_CAREER_POSITION_FAILURE',


    GET_CAREER_FIELD_REQUEST: 'GET_CAREER_FIELD_REQUEST',
    GET_CAREER_FIELD_SUCCESS: 'GET_CAREER_FIELD_SUCCESS',
    GET_CAREER_FIELD_FAILURE: 'GET_CAREER_FIELD_FAILURE',

    CREATE_CAREER_FIELD_REQUEST: 'CREATE_NEW_CAREER_FIELD_REQUEST',
    CREATE_CAREER_FIELD_SUCCESS: 'CREATE_NEW_CAREER_FIELD_SUCCESS',
    CREATE_CAREER_FIELD_FAILURE: 'CREATE_NEW_CAREER_FIELD_FAILURE',

    DELETE_CAREER_FIELD_REQUEST: 'DELETE_CAREER_FIELD_REQUEST',
    DELETE_CAREER_FIELD_SUCCESS:  'DELETE_CAREER_FIELD_SUCCESS',
    DELETE_CAREER_FIELD_FAILURE:  'DELETE_CAREER_FIELD_FAILURE',

    UPDATE_CAREER_FIELD_REQUEST: 'UPDATE_CAREER_FIELD_REQUEST',
    UPDATE_CAREER_FIELD_SUCCESS: 'UPDATE_CAREER_FIELD_SUCCESS',
    UPDATE_CAREER_FIELD_FAILURE: 'UPDATE_CAREER_FIELD_FAILURE',


    GET_CAREER_ACTION_REQUEST: 'GET_CAREER_ACTION_REQUEST',
    GET_CAREER_ACTION_SUCCESS: 'GET_CAREER_ACTION_SUCCESS',
    GET_CAREER_ACTION_FAILURE: 'GET_CAREER_ACTION_FAILURE',

    CREATE_CAREER_ACTION_REQUEST: 'CREATE_NEW_CAREER_ACTION_REQUEST',
    CREATE_CAREER_ACTION_SUCCESS: 'CREATE_NEW_CAREER_ACTION_SUCCESS',
    CREATE_CAREER_ACTION_FAILURE: 'CREATE_NEW_CAREER_ACTION_FAILURE',

    DELETE_CAREER_ACTION_REQUEST: 'DELETE_CAREER_ACTION_REQUEST',
    DELETE_CAREER_ACTION_SUCCESS:  'DELETE_CAREER_ACTION_SUCCESS',
    DELETE_CAREER_ACTION_FAILURE:  'DELETE_CAREER_ACTION_FAILURE',

    UPDATE_CAREER_ACTION_REQUEST: 'UPDATE_CAREER_ACTION_REQUEST',
    UPDATE_CAREER_ACTION_SUCCESS: 'UPDATE_CAREER_ACTION_SUCCESS',
    UPDATE_CAREER_ACTION_FAILURE: 'UPDATE_CAREER_ACTION_FAILURE',

    

};