export const companyConstants = {
    GET_COMPANIES_REQUEST: 'GET_COMPANIES_REQUEST',
    GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
    GET_COMPANIES_FAILE: 'GET_COMPANIES_FAILE',

    CREATE_COMPANY_REQUEST: 'CREATE_COMPANY_REQUEST',
    CREATE_COMPANY_SUCCESS: 'CREATE_COMPANY_SUCCESS',
    CREATE_COMPANY_FAILE: 'CREATE_COMPANY_FAILE',
    
}