export const IssueConstants = {
  GET_ALL_ISSUE_REQUEST: 'GET_ALL_ISSUE_REQUEST',
  GET_ALL_ISSUE_SUCCESS: 'GET_ALL_ISSUE_SUCCESS',
  GET_ALL_ISSUE_FAILURE: 'GET_ALL_ISSUE_FAILURE',
  ADD_TO_3RD_PARTY_REQUEST: 'ADD_TO_3RD_PARTY_REQUEST',
  ADD_TO_3RD_PARTY_SUCCESS: 'ADD_TO_3RD_PARTY_SUCCESS',
  ADD_TO_3RD_PARTY_FAILURE: 'ADD_TO_3RD_PARTY_FAILURE'
}
