export const AuthConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILE: 'LOGIN_FAILE',
    LOGOUT: 'LOGOUT',

    EDIT_PROFILE_REQUEST: 'EDIT_PROFILE_REQUEST',
    EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_FAILE: 'EDIT_PROFILE_FAILE',

    CHANGE_USER_INFORMATION_REQUEST: 'CHANGE_USER_INFORMATION_REQUEST',
    CHANGE_USER_INFORMATION_SUCCESS: 'CHANGE_USER_INFORMATION_SUCCESS',
    CHANGE_USER_INFORMATION_FAILE: 'CHANGE_USER_INFORMATION_FAILE',

    CHANGE_USER_PASSWORD_REQUEST: 'CHANGE_USER_PASSWORD_REQUEST',
    CHANGE_USER_PASSWORD_SUCCESS: 'CHANGE_USER_PASSWORD_SUCCESS',
    CHANGE_USER_PASSWORD_FAILE: 'CHANGE_USER_PASSWORD_FAILE',

    GET_LINKS_OF_ROLE_REQUEST: 'GET_LINKS_OF_ROLE_REQUEST',
    GET_LINKS_OF_ROLE_SUCCESS: 'GET_LINKS_OF_ROLE_SUCCESS',
    GET_LINKS_OF_ROLE_FAILE: 'GET_LINKS_OF_ROLE_FAILE',

    REFRESH_DATA_USER_REQUEST: 'REFRESH_DATA_USER_REQUEST',
    REFRESH_DATA_USER_SUCCESS: 'REFRESH_DATA_USER_SUCCESS',
    REFRESH_DATA_USER_FAILE: 'REFRESH_DATA_USER_FAILE',

    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILE: 'FORGOT_PASSWORD_FAILE',

    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILE: 'RESET_PASSWORD_FAILE',

    GET_COMPONENTS_OF_USER_IN_LINK_REQUEST: 'GET_COMPONENTS_OF_USER_IN_LINK_REQUEST',
    GET_COMPONENTS_OF_USER_IN_LINK_SUCCESS: 'GET_COMPONENTS_OF_USER_IN_LINK_SUCCESS',
    GET_COMPONENTS_OF_USER_IN_LINK_FAILE: 'GET_COMPONENTS_OF_USER_IN_LINK_FAILE',
}