export const AuthConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILE: 'LOGIN_FAILE',
    LOGOUT: 'LOGOUT',

    EDIT_PROFILE_REQUEST: 'EDIT_PROFILE_REQUEST',
    EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_FAILE: 'EDIT_PROFILE_FAILE',
    
    GET_LINKS_OF_ROLE_REQUEST: 'GET_LINKS_OF_ROLE_REQUEST',
    GET_LINKS_OF_ROLE_SUCCESS: 'GET_LINKS_OF_ROLE_SUCCESS',
    GET_LINKS_OF_ROLE_FAILE: 'GET_LINKS_OF_ROLE_FAILE',

    REFRESH_DATA_USER_REQUEST: 'REFRESH_DATA_USER_REQUEST',
    REFRESH_DATA_USER_SUCCESS: 'REFRESH_DATA_USER_SUCCESS',
    REFRESH_DATA_USER_FAILE: 'REFRESH_DATA_ROLE_FAILE',
}