export * from './generalTab'
export * from './maintainanceLogTab'
export * from './usageLogTab'
export * from './depreciationTab'
export * from './incidentLogTab'
export * from './disposalTab'
export * from './attachmentTab'
