export const InternalServiceIdentityConstants = {
    CREATE_INTERNAL_SERVICE_IDENTITY_REQUEST: 'CREATE_INTERNAL_SERVICE_IDENTITY_REQUEST',
    CREATE_INTERNAL_SERVICE_IDENTITY_SUCCESS: 'CREATE_INTERNAL_SERVICE_IDENTITY_SUCCESS',
    CREATE_INTERNAL_SERVICE_IDENTITY_FAILURE: 'CREATE_INTERNAL_SERVICE_IDENTITY_FAILURE',
    
    GET_INTERNAL_SERVICE_IDENTITY_REQUEST: 'GET_INTERNAL_SERVICE_IDENTITY_REQUEST',
    GET_INTERNAL_SERVICE_IDENTITY_SUCCESS: 'GET_INTERNAL_SERVICE_IDENTITY_SUCCESS',
    GET_INTERNAL_SERVICE_IDENTITY_FAILURE: 'GET_INTERNAL_SERVICE_IDENTITY_FAILURE',

    UPDATE_AUTO_INTERNAL_SERVICE_IDENTITY_REQUEST: 'UPDATE_AUTO_INTERNAL_SERVICE_IDENTITY_REQUEST',
    UPDATE_AUTO_INTERNAL_SERVICE_IDENTITY_SUCCESS: 'UPDATE_AUTO_INTERNAL_SERVICE_IDENTITY_SUCCESS',
    UPDATE_AUTO_INTERNAL_SERVICE_IDENTITY_FAILURE: 'UPDATE_AUTO_INTERNAL_SERVICE_IDENTITY_FAILURE',

    EDIT_INTERNAL_SERVICE_IDENTITY_REQUEST: 'EDIT_INTERNAL_SERVICE_IDENTITY_REQUEST',
    EDIT_INTERNAL_SERVICE_IDENTITY_SUCCESS: 'EDIT_INTERNAL_SERVICE_IDENTITY_SUCCESS',
    EDIT_INTERNAL_SERVICE_IDENTITY_FAILURE: 'EDIT_INTERNAL_SERVICE_IDENTITY_FAILURE',

    DELETE_INTERNAL_SERVICE_IDENTITY_REQUEST: 'DELETE_INTERNAL_SERVICE_IDENTITY_REQUEST',
    DELETE_INTERNAL_SERVICE_IDENTITY_SUCCESS: 'DELETE_INTERNAL_SERVICE_IDENTITY_SUCCESS',
    DELETE_INTERNAL_SERVICE_IDENTITY_FAILURE: 'DELETE_INTERNAL_SERVICE_IDENTITY_FAILURE',

}