export const CustomerConstants = {
    // Customer
    GET_CUSTOMERS_REQUEST: 'GET_CUSTOMERS_REQUEST',
    GET_CUSTOMERS_SUCCESS: 'GET_CUSTOMERS_SUCCESS',
    GET_CUSTOMERS_FAILE: 'GET_CUSTOMERS_FAILE',

    PAGINATE_CUSTOMERS_REQUEST: 'PAGINATE_CUSTOMERS_REQUEST',
    PAGINATE_CUSTOMERS_SUCCESS: 'PAGINATE_CUSTOMERS_SUCCESS',
    PAGINATE_CUSTOMERS_FAILE: 'PAGINATE_CUSTOMERS_FAILE',

    // Customer group
    GET_CUSTOMER_GROUPS_REQUEST: 'GET_CUSTOMER_GROUPS_REQUEST',
    GET_CUSTOMER_GROUPS_SUCCESS: 'GET_CUSTOMER_GROUPS_SUCCESS',
    GET_CUSTOMER_GROUPS_FAILE: 'GET_CUSTOMER_GROUPS_FAILE',

    PAGINATE_CUSTOMER_GROUPS_REQUEST: 'PAGINATE_CUSTOMER_GROUPS_REQUEST',
    PAGINATE_CUSTOMER_GROUPS_SUCCESS: 'PAGINATE_CUSTOMER_GROUPS_SUCCESS',
    PAGINATE_CUSTOMER_GROUPS_FAILE: 'PAGINATE_CUSTOMER_GROUPS_FAILE',
}