export const salesOrderConstants = {
    GET_ALL_SALES_ORDERS_REQUEST: 'GET_ALL_SALES_ORDERS_REQUEST',
    GET_ALL_SALES_ORDERS_SUCCESS: 'GET_ALL_SALES_ORDERS_SUCCESS',
    GET_ALL_SALES_ORDERS_FAILURE: 'GET_ALL_SALES_ORDERS_FAILURE',
}