export const DepartmentConstants = {
    GET_DEPARTMENTS_REQUEST: 'GET_DEPARTMENTS_REQUEST',
    GET_DEPARTMENTS_SUCCESS: 'GET_DEPARTMENTS_SUCCESS',
    GET_DEPARTMENTS_FAILE: 'GET_DEPARTMENTS_FAILE',

    CREATE_DEPARTMENT_REQUEST: 'CREATE_DEPARTMENT_REQUEST',
    CREATE_DEPARTMENT_SUCCESS: 'CREATE_DEPARTMENT_SUCCESS',
    CREATE_DEPARTMENT_FAILE: 'CREATE_DEPARTMENT_FAILE',

    EDIT_DEPARTMENT_REQUEST: 'EDIT_DEPARTMENT_REQUEST',
    EDIT_DEPARTMENT_SUCCESS: 'EDIT_DEPARTMENT_SUCCESS',
    EDIT_DEPARTMENT_FAILE: 'EDIT_DEPARTMENT_FAILE',

    DELETE_DEPARTMENT_REQUEST: 'DELETE_DEPARTMENT_REQUEST',
    DELETE_DEPARTMENT_SUCCESS: 'DELETE_DEPARTMENT_SUCCESS',
    DELETE_DEPARTMENT_FAILE: 'DELETE_DEPARTMENT_FAILE',

    GETALL_REQUEST: 'DEPARTMENT_GETALL_REQUEST',
    GETALL_SUCCESS: 'DEPARTMENT_GETALL_SUCCESS',
    GETALL_FAILURE: 'DEPARTMENT_GETALL_FAILURE',

    GETDEPARTMENT_OFUSER_REQUEST: 'GETDEPARTMENT_OFUSER_REQUEST',
    GETDEPARTMENT_OFUSER_SUCCESS: 'GETDEPARTMENT_OFUSER_SUCCESS',
    GETDEPARTMENT_OFUSER_FAILURE: 'GETDEPARTMENT_OFUSER_FAILURE',

    GETROLE_DEAN_OFUSER_REQUEST: 'GETROLE_DEAN_OFUSER_REQUEST',
    GETROLE_DEAN_OFUSER_SUCCESS: 'GETROLE_DEAN_OFUSER_SUCCESS',
    GETROLE_DEAN_OFUSER_FAILURE: 'GETROLE_DEAN_OFUSER_FAILURE'
}