export const DeliveryConstants = {
    GET_ALL_DELIVERY_REQUEST: "GET_ALL_DELIVERY_REQUEST",
    GET_ALL_DELIVERY_SUCCESS: "GET_ALL_DELIVERY_SUCCESS",
    GET_ALL_DELIVERY_FAILURE: "GET_ALL_DELIVERY_FAILURE",
    SAVE_SOLUTION_REQUEST: "SAVE_SOLUTION_REQUEST",
    SAVE_SOLUTION_SUCCESS: "SAVE_SOLUTION_SUCCESS",
    SAVE_SOLUTION_FAILURE: "SAVE_SOLUTION_FAILURE",
    CHANGE_ORDER_POSITION_REQUEST: "CHANGE_ORDER_POSITION_REQUEST",
    CHANGE_ORDER_POSITION_SUCCESS: "CHANGE_ORDER_POSITION_SUCCESS",
    CHANGE_ORDER_POSITION_FAILURE: "CHANGE_ORDER_POSITION_FAILURE",

    CREATE_DELIVERY_PLAN_REQUEST: "CREATE_DELIVERY_PLAN_REQUEST",
    CREATE_DELIVERY_PLAN_SUCCESS: "CREATE_DELIVERY_PLAN_SUCCESS",
    CREATE_DELIVERY_PLAN_FAILURE: "CREATE_DELIVERY_PLAN_FAILURE",

    GET_ALL_JOURNEY_REQUEST: "GET_ALL_JOURNEY_REQUEST",
    GET_ALL_JOURNEY_SUCCESS: "GET_ALL_JOURNEY_SUCCESS",
    GET_ALL_JOURNEY_FAILURE: "GET_ALL_JOURNEY_FAILURE",
}