export const ServiceLoggingConstants = {
  GET_SERVICE_LOGGING_REQUEST: 'GET_SERVICE_LOGGING_REQUEST',
  GET_SERVICE_LOGGING_SUCCESS: 'GET_SERVICE_LOGGING_SUCCESS',
  GET_SERVICE_LOGGING_FAILURE: 'GET_SERVICE_LOGGING_FAILURE'
}
