version: "3.8"
services:
  asset-service:
    container_name: asset-service
    image: node:alpine
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - ./node_modules:/app/node_modules
      - ./:/app
    command: sh -c "cd /app && npm install && npm start"
