export const TaskPertConstants ={
    
    CHANGE_TIME_REQUEST: 'CHANGE_TIME_REQUEST',
    CHANGE_TIME_SUCCESS: 'CHANGE_TIME_SUCCESS',
    CHANGE_TIME_FAILURE: 'CHANGE_TIME_FAILURE',

    COUNT_TASK_REQUEST: 'COUNT_TASK_REQUEST',
    COUNT_TASK_SUCCESS: 'COUNT_TASK_SUCCESS',
    COUNT_TASK_FAILURE: 'COUNT_TASK_FAILURE',

    UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_FAILURE: 'UPDATE_TASK_FAILURE',
    
    UPDATE_PROCESS_LIST_REQUEST: 'UPDATE_PROCESS_LIST_REQUEST',
    UPDATE_PROCESS_LIST_SUCCESS: 'UPDATE_PROCESS_LIST_SUCCESS',
    UPDATE_PROCESS_LIST_FAILURE: 'UPDATE_PROCESS_LIST_FAILURE',

    CLOSE_PROCESS_REQUEST: 'CLOSE_PROCESS_REQUEST',
    CLOSE_PROCESS_SUCCESS: 'CLOSE_PROCESS_SUCCESS',
    CLOSE_PROCESS_FAILURE: 'CLOSE_PROCESS_FAILURE',

    


}