
export const workScheduleConstants = {
    GET_ALL_WORK_SCHEDULE_REQUEST: 'GET_ALL_WORK_SCHEDULE_REQUEST',
    GET_ALL_WORK_SCHEDULE_FAILURE: 'GET_ALL_WORK_SCHEDULE_FAILURE',
    GET_ALL_WORK_SCHEDULE_SUCCESS: 'GET_ALL_WORK_SCHEDULE_SUCCESS',

    CREATE_WORK_SCHEDULE_REQUEST: 'CREATE_WORK_SCHEDULE_REQUEST',
    CREATE_WORK_SCHEDULE_FAILURE: 'CREATE_WORK_SCHEDULE_FAILURE',
    CREATE_WORK_SCHEDULE_SUCCESS: 'CREATE_WORK_SCHEDULE_SUCCESS',

    SET_CURRENT_MONTH: 'SET_CURRENT_MONTH',

    GET_ALL_WORK_SCHEDULE_WORKER_REQUEST: 'GET_ALL_WORK_SCHEDULE_WORKER_REQUEST',
    GET_ALL_WORK_SCHEDULE_WORKER_FAILURE: 'GET_ALL_WORK_SCHEDULE_WORKER_FAILURE',
    GET_ALL_WORK_SCHEDULE_WORKER_SUCCESS: 'GET_ALL_WORK_SCHEDULE_WORKER_SUCCESS',

    GET_ALL_WORK_SCHEDULE_BY_MILL_ID_REQUEST: 'GET_ALL_WORK_SCHEDULE_BY_MILL_ID_REQUEST',
    GET_ALL_WORK_SCHEDULE_BY_MILL_ID_FAILURE: 'GET_ALL_WORK_SCHEDULE_BY_MILL_ID_FAILURE',
    GET_ALL_WORK_SCHEDULE_BY_MILL_ID_SUCCESS: 'GET_ALL_WORK_SCHEDULE_BY_MILL_ID_SUCCESS',

}