export const transportProcessConstants = {
    START_LOCATE_REQUEST: "START_LOCATE_REQUEST",
    START_LOCATE_SUCCESS: "START_LOCATE_SUCCESS",
    START_LOCATE_FAILURE: "START_LOCATE_FAILURE",

    CREATE_TRANSPORT_REQUIREMENT_REQUEST: "CREATE_TRANSPORT_REQUIREMENT_REQUEST",
    CREATE_TRANSPORT_REQUIREMENT_SUCCESS: "CREATE_TRANSPORT_REQUIREMENT_SUCCESS",
    CREATE_TRANSPORT_REQUIREMENT_FAILURE: "CREATE_TRANSPORT_REQUIREMENT_FAILURE",

    GET_DETAIL_TRANSPORT_REQUIREMENT_REQUEST: "GET_DETAIL_TRANSPORT_REQUIREMENT_REQUEST",
    GET_DETAIL_TRANSPORT_REQUIREMENT_SUCCESS: "GET_DETAIL_TRANSPORT_REQUIREMENT_SUCCESS",
    GET_DETAIL_TRANSPORT_REQUIREMENT_FAILURE: "GET_DETAIL_TRANSPORT_REQUIREMENT_FAILURE",

    EDIT_TRANSPORT_REQUIREMENT_REQUEST: "EDIT_TRANSPORT_REQUIREMENT_REQUEST",
    EDIT_TRANSPORT_REQUIREMENT_SUCCESS: "EDIT_TRANSPORT_REQUIREMENT_SUCCESS",
    EDIT_TRANSPORT_REQUIREMENT_FAILURE: "EDIT_TRANSPORT_REQUIREMENT_FAILURE",

    DELETE_TRANSPORT_REQUIREMENT_REQUEST: "DELETE_TRANSPORT_REQUIREMENT_REQUEST",
    DELETE_TRANSPORT_REQUIREMENT_SUCCESS: "DELETE_TRANSPORT_REQUIREMENT_SUCCESS",
    DELETE_TRANSPORT_REQUIREMENT_FAILURE: "DELETE_TRANSPORT_REQUIREMENT_FAILURE",
}
