export const transportProcessConstants = {
    START_LOCATE_REQUEST: "START_LOCATE_REQUEST",
    START_LOCATE_SUCCESS: "START_LOCATE_SUCCESS",
    START_LOCATE_FAILURE: "START_LOCATE_FAILURE",

    SEND_CURRENT_LOCATE_REQUEST: "SEND_CURRENT_LOCATE_REQUEST",
    SEND_CURRENT_LOCATE_SUCCESS: "SEND_CURRENT_LOCATE_SUCCESS",
    SEND_CURRENT_LOCATE_FAILURE: "SEND_CURRENT_LOCATE_FAILURE",

    STOP_LOCATE_REQUEST: "STOP_LOCATE_REQUEST",
    STOP_LOCATE_SUCCESS: "STOP_LOCATE_SUCCESS",
    STOP_LOCATE_FAILURE: "STOP_LOCATE_FAILURE",

    EDIT_TRANSPORT_REQUIREMENT_REQUEST: "EDIT_TRANSPORT_REQUIREMENT_REQUEST",
    EDIT_TRANSPORT_REQUIREMENT_SUCCESS: "EDIT_TRANSPORT_REQUIREMENT_SUCCESS",
    EDIT_TRANSPORT_REQUIREMENT_FAILURE: "EDIT_TRANSPORT_REQUIREMENT_FAILURE",

    DELETE_TRANSPORT_REQUIREMENT_REQUEST: "DELETE_TRANSPORT_REQUIREMENT_REQUEST",
    DELETE_TRANSPORT_REQUIREMENT_SUCCESS: "DELETE_TRANSPORT_REQUIREMENT_SUCCESS",
    DELETE_TRANSPORT_REQUIREMENT_FAILURE: "DELETE_TRANSPORT_REQUIREMENT_FAILURE",
}
