export const RequesterConstants = {
  GET_REQUESTERS_REQUEST: 'GET_REQUESTERS_REQUEST',
  GET_REQUESTERS_SUCCESS: 'GET_REQUESTERS_SUCCESS',
  GET_REQUESTERS_FAILE: 'GET_REQUESTERS_FAILE',

  GET_REQUESTERS_PAGINATE_REQUEST: 'GET_REQUESTERS_PAGINATE_REQUEST',
  GET_REQUESTERS_PAGINATE_SUCCESS: 'GET_REQUESTERS_PAGINATE_SUCCESS',
  GET_REQUESTERS_PAGINATE_FAILE: 'GET_REQUESTERS_PAGINATE_FAILE',

  SHOW_REQUESTER_REQUEST: 'SHOW_REQUESTER_REQUEST',
  SHOW_REQUESTER_SUCCESS: 'SHOW_REQUESTER_SUCCESS',
  SHOW_REQUESTER_FAILE: 'SHOW_REQUESTER_FAILE',

  CREATE_REQUESTER_REQUEST: 'CREATE_REQUESTER_REQUEST',
  CREATE_REQUESTER_SUCCESS: 'CREATE_REQUESTER_SUCCESS',
  CREATE_REQUESTER_FAILE: 'CREATE_REQUESTER_FAILE',

  EDIT_REQUESTER_REQUEST: 'EDIT_REQUESTER_REQUEST',
  EDIT_REQUESTER_SUCCESS: 'EDIT_REQUESTER_SUCCESS',
  EDIT_REQUESTER_FAILE: 'EDIT_REQUESTER_FAILE'
}
