export const configTaskTempalte= {
    rowHeader : 1,
    sheets : ["Sheet 1", "Sheet 2"],
    unit : "Đơn vị",
    viewerPeople : "Người được xem",
    name: "Tên mẫu",
    priority: "Độ ưu tiên",
    description : "Mô tả",
    responsibleEmployees : "Người thực hiện",
    accountableEmployees: "Người phê duyệt",
    consultedEmployees: "Người hỗ trợ",
    informedEmployees :"Người quan sát",
    formula: "Công thức tinh điểm",
    taskActions: "Danh sách hoạt động",
    nameTaskActions: "Tên hoạt động",
    descriptionTaskAction: "Mô tả",
    mandatory : "Bắt buộc",
    taskInformation: "Danh sách thông tin",
    nameTaskInformation : "Tên thông tin",
    descriptionTaskInformation: "Mô tả thông tin",
    typeTaskInformation: "Kiểu dữ liệu",
    onlyManager: "Chỉ quản lý được điền"
}