export const OrderConstants = {
  GET_ADDRESS_FROM_LAT_LNG_REQUEST: 'GET_ADDRESS_FROM_LAT_LNG_REQUEST',
  GET_ADDRESS_FROM_LAT_LNG_SUCCESS: 'GET_ADDRESS_FROM_LAT_LNG_SUCCESS',
  GET_ADDRESS_FROM_LAT_LNG_FAILURE: 'GET_ADDRESS_FROM_LAT_LNG_FAILURE',
  CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',
  GET_ALL_ORDER_REQUEST: 'GET_ALL_ORDER_REQUEST',
  GET_ALL_ORDER_SUCCESS: 'GET_ALL_ORDER_SUCCESS',
  GET_ALL_ORDER_FAILURE: 'GET_ALL_ORDER_FAILURE',
  RETRAINING_MODEL_REQUEST: 'RETRAINING_MODEL_REQUEST',
  RETRAINING_MODEL_SUCCESS: 'RETRAINING_MODEL_SUCCESS',
  RETRAINING_MODEL_FAILURE: 'RETRAINING_MODEL_FAILURE'
}
