export const ExternalPolicyConstants = {
    GET_EXTERNAL_POLICY_REQUEST: 'GET_EXTERNAL_POLICY_REQUEST',
    GET_EXTERNAL_POLICY_SUCCESS: 'GET_EXTERNAL_POLICY_SUCCESS',
    GET_EXTERNAL_POLICY_FAILURE: 'GET_EXTERNAL_POLICY_FAILURE',

}