export const RoleConstants = {
    GET_ROLES_REQUEST: 'GET_ROLES_REQUEST',
    GET_ROLES_SUCCESS: 'GET_ROLES_SUCCESS',
    GET_ROLES_FAILE: 'GET_ROLES_FAILE',

    SHOW_ROLE_REQUEST: 'SHOW_ROLE_REQUEST',
    SHOW_ROLE_SUCCESS: 'SHOW_ROLE_SUCCESS',
    SHOW_ROLE_FAILE: 'SHOW_ROLE_FAILE',

    CREATE_ROLE_REQUEST: 'CREATE_ROLE_REQUEST',
    CREATE_ROLE_SUCCESS: 'CREATE_ROLE_SUCCESS',
    CREATE_ROLE_FAILE: 'CREATE_ROLE_FAILE',
}