export const SabbaticalConstants = {
    GET_SABBATICAL_REQUEST: 'GET_SABBATICAL_REQUEST',
    GET_SABBATICAL_SUCCESS: 'GET_SABBATICAL_SUCCESS',
    GET_SABBATICAL_FAILURE: 'GET_SABBATICAL_FAILURE',

    CREATE_SABBATICAL_REQUEST: 'CREATE_NEW_SABBATICAL_REQUEST',
    CREATE_SABBATICAL_SUCCESS: 'CREATE_NEW_SABBATICAL_SUCCESS',
    CREATE_SABBATICAL_FAILURE: 'CREATE_NEW_SABBATICAL_FAILURE',

    DELETE_SABBATICAL_REQUEST: 'DELETE_SABBATICAL_REQUEST',
    DELETE_SABBATICAL_SUCCESS:  'DELETE_SABBATICAL_SUCCESS',
    DELETE_SABBATICAL_FAILURE:  'DELETE_SABBATICAL_FAILURE',

    UPDATE_SABBATICAL_REQUEST: 'UPDATE_SABBATICAL_REQUEST',
    UPDATE_SABBATICAL_SUCCESS: 'UPDATE_SABBATICAL_SUCCESS',
    UPDATE_SABBATICAL_FAILURE: 'UPDATE_SABBATICAL_FAILURE',
};