export const AssetConstants = {
    GETALL_REQUEST: 'ASSET_GETALL_REQUEST',
    GETALL_SUCCESS: 'ASSET_GETALL_SUCCESS',
    GETALL_FAILURE: 'ASSET_GETALL_FAILURE',

    ADDASSET_REQUEST: 'ASSET_ADDASSET_REQUEST',
    ADDASSET_SUCCESS: 'ASSET_ADDASSET_SUCCESS',
    ADDASSET_FAILURE: 'ASSET_ADDASSET_FAILURE',

    UPDATE_INFOR_ASSET_REQUEST: 'ASSET_UPDATE_INFOR_ASSET_REQUEST',
    UPDATE_INFOR_ASSET_SUCCESS: 'ASSET_UPDATE_INFOR_ASSET_SUCCESS',
    UPDATE_INFOR_ASSET_FAILURE: 'ASSET_UPDATE_INFOR_ASSET_FAILURE',

    UPLOAD_AVATAR_REQUEST: "ULOAD_AVATAR_ASSET_REQUEST",
    UPLOAD_AVATAR_SUCCESS: "ULOAD_AVATAR_ASSET_SUCCESS",
    UPLOAD_AVATAR_FAILURE: "ULOAD_AVATAR_ASSET_FAILURE",

    UPDATE_FILE_REQUEST: "UPDATE_FILE_ASSET_REQUEST",
    UPDATE_FILE_SUCCESS: "UPDATE_FILE_ASSET_SUCCESS",
    UPDATE_FILE_FAILURE: "UPDATE_FILE_ASSET_FAILURE",

    CHECK_ASSETNUMBER_REQUEST: "CHECK_ASSETNUMBER_ASSET_REQUEST",
    CHECK_ASSETNUMBER_SUCCESS: "CHECK_ASSETNUMBER_ASSET_SUCCESS",
    CHECK_ASSETNUMBER_FAILURE: "CHECK_ASSETNUMBER_ASSET_FAILURE",

    DELETE_ASSET_REQUEST: 'DELETE_ASSET_REQUEST',
    DELETE_ASSET_SUCCESS: 'DELETE_ASSET_SUCCESS',
    DELETE_ASSET_FAILURE: 'DELETE_ASSET_FAILURE',

};