export const AssetConstants = {
    GET_ASSET_REQUEST: 'GET_ASSET_REQUEST',
    GET_ASSET_SUCCESS: 'GET_ASSET_SUCCESS',
    GET_ASSET_FAILURE: 'GET_ASSET_FAILURE',

    CREATE_ASSET_REQUEST: 'CREATE_NEW_ASSET_REQUEST',
    CREATE_ASSET_SUCCESS: 'CREATE_NEW_ASSET_SUCCESS',
    CREATE_ASSET_FAILURE: 'CREATE_NEW_ASSET_FAILURE',

    DELETE_ASSET_REQUEST: 'DELETE_ASSET_REQUEST',
    DELETE_ASSET_SUCCESS:  'DELETE_ASSET_SUCCESS',
    DELETE_ASSET_FAILURE:  'DELETE_ASSET_FAILURE',

    UPDATE_ASSET_REQUEST: 'UPDATE_ASSET_REQUEST',
    UPDATE_ASSET_SUCCESS: 'UPDATE_ASSET_SUCCESS',
    UPDATE_ASSET_FAILURE: 'UPDATE_ASSET_FAILURE',
};