export const getEmployeeDashboardDataConstant = {
    GET_EMPLOYEE_DASHBOARD_DATA_REQUEST: "GET_EMPLOYEE_DASHBOARD_DATA_REQUEST",
    GET_EMPLOYEE_DASHBOARD_DATA_SUCCESS: "GET_EMPLOYEE_DASHBOARD_DATA_SUCCESS",
    GET_EMPLOYEE_DASHBOARD_DATA_FAILURE: "GET_EMPLOYEE_DASHBOARD_DATA_FAILURE",
}