export const routeConstants = {
  GET_ALL_VEHICLE_TRANSPORTING_REQUEST: 'GET_ALL_VEHICLE_TRANSPORTING_REQUEST',
  GET_ALL_VEHICLE_TRANSPORTING_SUCCESS: 'GET_ALL_VEHICLE_TRANSPORTING_SUCCESS',
  GET_ALL_VEHICLE_TRANSPORTING_FAILURE: 'GET_ALL_VEHICLE_TRANSPORTING_FAILURE',
  GET_ALL_ORDER_TRANSPORTING_REQUEST: 'GET_ALL_ORDER_TRANSPORTING_REQUEST',
  GET_ALL_ORDER_TRANSPORTING_SUCCESS: 'GET_ALL_ORDER_TRANSPORTING_SUCCESS',
  GET_ALL_ORDER_TRANSPORTING_FAILURE: 'GET_ALL_ORDER_TRANSPORTING_FAILURE'
}
