export const LinkConstants = {
    GET_LINKS_DEFAULT_REQUEST: 'GET_LINKS_DEFAULT_REQUEST',
    GET_LINKS_DEFAULT_SUCCESS: 'GET_LINKS_DEFAULT_SUCCESS',
    GET_LINKS_DEFAULT_FAILE: 'GET_LINKS_DEFAULT_FAILE',

    GET_LINKS_DEFAULT_PAGINATE_REQUEST: 'GET_LINKS_DEFAULT_PAGINATE_REQUEST',
    GET_LINKS_DEFAULT_PAGINATE_SUCCESS: 'GET_LINKS_DEFAULT_PAGINATE_SUCCESS',
    GET_LINKS_DEFAULT_PAGINATE_FAILE: 'GET_LINKS_DEFAULT_PAGINATE_FAILE',

    SHOW_LINK_DEFAULT_REQUEST: 'SHOW_LINK_DEFAULT_REQUEST',
    SHOW_LINK_DEFAULT_SUCCESS: 'SHOW_LINK_DEFAULT_SUCCESS',
    SHOW_LINK_DEFAULT_FAILE: 'SHOW_LINK_DEFAULT_FAILE',

    CREATE_LINK_DEFAULT_REQUEST: 'CREATE_LINK_DEFAULT_REQUEST',
    CREATE_LINK_DEFAULT_SUCCESS: 'CREATE_LINK_DEFAULT_SUCCESS',
    CREATE_LINK_DEFAULT_FAILE: 'CREATE_LINK_DEFAULT_FAILE',

    EDIT_LINK_DEFAULT_REQUEST: 'EDIT_LINK_DEFAULT_REQUEST',
    EDIT_LINK_DEFAULT_SUCCESS: 'EDIT_LINK_DEFAULT_SUCCESS',
    EDIT_LINK_DEFAULT_FAILE: 'EDIT_LINK_DEFAULT_FAILE',

    DELETE_LINK_DEFAULT_REQUEST: 'DELETE_LINK_DEFAULT_REQUEST',
    DELETE_LINK_DEFAULT_SUCCESS: 'DELETE_LINK_DEFAULT_SUCCESS',
    DELETE_LINK_DEFAULT_FAILE: 'DELETE_LINK_DEFAULT_FAILE',
}