export const ProjectProposalConstants = {
  PROPOSAL_PROJECT_REQUEST: 'PROPOSAL_PROJECT_REQUEST',
  PROPOSAL_PROJECT_SUCCESS: 'PROPOSAL_PROJECT_SUCCESS',
  PROPOSAL_PROJECT_FAIL: 'PROPOSAL_PROJECT_FAIL',
  ASSIGN_PROPOSAL_PROJECT_REQUEST: 'ASSIGN_PROPOSAL_PROJECT_REQUEST',
  ASSIGN_PROPOSAL_PROJECT_SUCCESS: 'ASSIGN_PROPOSAL_PROJECT_SUCCESS',
  ASSIGN_PROPOSAL_PROJECT_FAIL: 'ASSIGN_PROPOSAL_PROJECT_FAIL',
}
