export const ProjectProposalConstants = {
  PROPOSAL_PROJECT_REQUEST: 'PROPOSAL_PROJECT_REQUEST',
  PROPOSAL_PROJECT_SUCCESS: 'PROPOSAL_PROJECT_SUCCESS',
  PROPOSAL_PROJECT_FAIL: 'PROPOSAL_PROJECT_FAIL',
}
