export const CareerConstant = {
  GET_CAREER_POSITION_REQUEST: 'GET_CAREER_POSITION_REQUEST',
  GET_CAREER_POSITION_SUCCESS: 'GET_CAREER_POSITION_SUCCESS',
  GET_CAREER_POSITION_FAILURE: 'GET_CAREER_POSITION_FAILURE',

  CREATE_CAREER_POSITION_REQUEST: 'CREATE_NEW_CAREER_POSITION_REQUEST',
  CREATE_CAREER_POSITION_SUCCESS: 'CREATE_NEW_CAREER_POSITION_SUCCESS',
  CREATE_CAREER_POSITION_FAILURE: 'CREATE_NEW_CAREER_POSITION_FAILURE',

  DELETE_CAREER_POSITION_REQUEST: 'DELETE_CAREER_POSITION_REQUEST',
  DELETE_CAREER_POSITION_SUCCESS: 'DELETE_CAREER_POSITION_SUCCESS',
  DELETE_CAREER_POSITION_FAILURE: 'DELETE_CAREER_POSITION_FAILURE',

  UPDATE_CAREER_POSITION_REQUEST: 'UPDATE_CAREER_POSITION_REQUEST',
  UPDATE_CAREER_POSITION_SUCCESS: 'UPDATE_CAREER_POSITION_SUCCESS',
  UPDATE_CAREER_POSITION_FAILURE: 'UPDATE_CAREER_POSITION_FAILURE'
}
