export const ResourceConstants = {
  GET_RESOURCES_REQUEST: 'GET_RESOURCES_REQUEST',
  GET_RESOURCES_SUCCESS: 'GET_RESOURCES_SUCCESS',
  GET_RESOURCES_FAILE: 'GET_RESOURCES_FAILE',

  GET_RESOURCES_PAGINATE_REQUEST: 'GET_RESOURCES_PAGINATE_REQUEST',
  GET_RESOURCES_PAGINATE_SUCCESS: 'GET_RESOURCES_PAGINATE_SUCCESS',
  GET_RESOURCES_PAGINATE_FAILE: 'GET_RESOURCES_PAGINATE_FAILE',

  SHOW_RESOURCE_REQUEST: 'SHOW_RESOURCE_REQUEST',
  SHOW_RESOURCE_SUCCESS: 'SHOW_RESOURCE_SUCCESS',
  SHOW_RESOURCE_FAILE: 'SHOW_RESOURCE_FAILE',

  CREATE_RESOURCE_REQUEST: 'CREATE_RESOURCE_REQUEST',
  CREATE_RESOURCE_SUCCESS: 'CREATE_RESOURCE_SUCCESS',
  CREATE_RESOURCE_FAILE: 'CREATE_RESOURCE_FAILE',

  EDIT_RESOURCE_REQUEST: 'EDIT_RESOURCE_REQUEST',
  EDIT_RESOURCE_SUCCESS: 'EDIT_RESOURCE_SUCCESS',
  EDIT_RESOURCE_FAILE: 'EDIT_RESOURCE_FAILE'
}
