export const AssetCrashConstants = {
    GET_ASSET_CRASH_REQUEST: 'GET_ASSET_CRASH_REQUEST',
    GET_ASSET_CRASH_SUCCESS: 'GET_ASSET_CRASH_SUCCESS',
    GET_ASSET_CRASH_FAILURE: 'GET_ASSET_CRASH_FAILURE',

    CREATE_ASSET_CRASH_REQUEST: 'CREATE_ASSET_CRASH_REQUEST',
    CREATE_ASSET_CRASH_SUCCESS: 'CREATE_ASSET_CRASH_SUCCESS',
    CREATE_ASSET_CRASH_FAILURE: 'CREATE_ASSET_CRASH_FAILURE',

    DELETE_ASSET_CRASH_REQUEST: 'DELETE_ASSET_CRASH_REQUEST',
    DELETE_ASSET_CRASH_SUCCESS: 'DELETE_ASSET_CRASH_SUCCESS',
    DELETE_ASSET_CRASH_FAILURE: 'DELETE_ASSET_CRASH_FAILURE',

    UPDATE_ASSET_CRASH_REQUEST: 'UPDATE_ASSET_CRASH_REQUEST',
    UPDATE_ASSET_CRASH_SUCCESS: 'UPDATE_ASSET_CRASH_SUCCESS',
    UPDATE_ASSET_CRASH_FAILURE: 'UPDATE_ASSET_CRASH_FAILURE',
};