export const SuppliesDashboardConstants = {
    GET_SUPPLIES_DASHBOARD_REQUEST: 'GET_SUPPLIES_DASHBOARD_REQUEST',
    GET_SUPPLIES_DASHBOARD_SUCCESS: 'GET_SUPPLIES_DASHBOARD_SUCCESS',
    GET_SUPPLIES_DASHBOARD_FAILURE: 'GET_SUPPLIES_DASHBOARD_FAILURE',

    GET_SUPPLIES_ORGANIZATION_DASHBOARD_REQUEST: 'GET_SUPPLIES_ORGANIZATION_DASHBOARD_REQUEST',
    GET_SUPPLIES_ORGANIZATION_DASHBOARD_SUCCESS: 'GET_SUPPLIES_ORGANIZATION_DASHBOARD_SUCCESS',
    GET_SUPPLIES_ORGANIZATION_DASHBOARD_FAILURE: 'GET_SUPPLIES_ORGANIZATION_DASHBOARD_FAILURE',
}