export const ServiceConstants = {
  GET_SERVICES_REQUEST: 'GET_SERVICES_REQUEST',
  GET_SERVICES_SUCCESS: 'GET_SERVICES_SUCCESS',
  GET_SERVICES_FAILE: 'GET_SERVICES_FAILE',

  GET_SERVICES_PAGINATE_REQUEST: 'GET_SERVICES_PAGINATE_REQUEST',
  GET_SERVICES_PAGINATE_SUCCESS: 'GET_SERVICES_PAGINATE_SUCCESS',
  GET_SERVICES_PAGINATE_FAILE: 'GET_SERVICES_PAGINATE_FAILE',

  EDIT_SERVICE_REQUEST: 'EDIT_SERVICE_REQUEST',
  EDIT_SERVICE_SUCCESS: 'EDIT_SERVICE_SUCCESS',
  EDIT_SERVICE_FAILE: 'EDIT_SERVICE_FAILE',

  CREATE_SERVICE_REQUEST: 'CREATE_SERVICE_REQUEST',
  CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
  CREATE_SERVICE_FAILE: 'CREATE_SERVICE_FAILE',

  DELETE_SERVICE_REQUEST: 'DELETE_SERVICE_REQUEST',
  DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
  DELETE_SERVICE_FAILE: 'DELETE_SERVICE_FAILE',

  IMPORT_SERVICES_REQUEST: 'IMPORT_SERVICES_REQUEST',
  IMPORT_SERVICES_SUCCESS: 'IMPORT_SERVICES_SUCCESS',
  IMPORT_SERVICES_FAILE: 'IMPORT_SERVICES_FAILE',

  SEND_EMAIL_RESET_PASSWORD_SERVICE_REQUEST: 'SEND_EMAIL_RESET_PASSWORD_SERVICE_REQUEST',
  SEND_EMAIL_RESET_PASSWORD_SERVICE_SUCCESS: 'SEND_EMAIL_RESET_PASSWORD_SERVICE_SUCCESS',
  SEND_EMAIL_RESET_PASSWORD_SERVICE_FAILE: 'SEND_EMAIL_RESET_PASSWORD_SERVICE_FAILE'
}
