export const ConfigManagementConstant = {
  GET_CONFIG_SETTING_DATA_REQUEST: 'GET_CONFIG_SETTING_DATA_REQUEST',
  GET_CONFIG_SETTING_DATA_REQUEST_SUCCESS: 'GET_CONFIG_SETTING_DATA_REQUEST_SUCCESS',
  GET_CONFIG_SETTING_DATA_REQUEST_FAILED: 'GET_CONFIG_SETTING_DATA_REQUEST_FAILED',

  UPDATE_CONFIG_SETTING_DATA_REQUEST: 'UPDATE_CONFIG_SETTING_DATA_REQUEST',
  UPDATE_CONFIG_SETTING_DATA_REQUEST_SUCCESS: 'UPDATE_CONFIG_SETTING_DATA_REQUEST_SUCCESS',
  UPDATE_CONFIG_SETTING_DATA_REQUEST_FAILED: 'UPDATE_CONFIG_SETTING_DATA_REQUEST_FAILED',

  UPDATE_CONFIG_SETTING: 'UPDATE_CONFIG_SETTING',

  HANDLE_START_ALLOCATION_REQUEST: 'HANDLE_START_ALLOCATION_REQUEST',
  HANDLE_START_ALLOCATION_REQUEST_SUCCESS: 'HANDLE_START_ALLOCATION_REQUEST_SUCCESS',
  HANDLE_START_ALLOCATION_REQUEST_FAILED: 'HANDLE_START_ALLOCATION_REQUEST_FAILED'
}
