export const CustomerConstants = {
    // Customer
    GET_CUSTOMERS_REQUEST: 'GET_CUSTOMERS_REQUEST',
    GET_CUSTOMERS_SUCCESS: 'GET_CUSTOMERS_SUCCESS',
    GET_CUSTOMERS_FAILE: 'GET_CUSTOMERS_FAILE',

    PAGINATE_CUSTOMERS_REQUEST: 'PAGINATE_CUSTOMERS_REQUEST',
    PAGINATE_CUSTOMERS_SUCCESS: 'PAGINATE_CUSTOMERS_SUCCESS',
    PAGINATE_CUSTOMERS_FAILE: 'PAGINATE_CUSTOMERS_FAILE',

    CREATE_CUSTOMER_REQUEST: 'CREATE_CUSTOMER_REQUEST',
    CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_FAILE: 'CREATE_CUSTOMER_FAILE',

    EDIT_CUSTOMER_REQUEST: 'EDIT_CUSTOMER_REQUEST',
    EDIT_CUSTOMER_SUCCESS: 'EDIT_CUSTOMER_SUCCESS',
    EDIT_CUSTOMER_FAILE: 'EDIT_CUSTOMER_FAILE',

    DELETE_CUSTOMER_REQUEST: 'DELETE_CUSTOMER_REQUEST',
    DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
    DELETE_CUSTOMER_FAILE: 'DELETE_CUSTOMER_FAILE',
}