export const RoutePickingConstants = {
  GET_ALL_ROUTES_REQUEST: 'GET_ALL_ROUTES_REQUEST',
  GET_ALL_ROUTES_SUCCESS: 'GET_ALL_ROUTES_SUCCESS',
  GET_ALL_ROUTES_FAILURE: 'GET_ALL_ROUTES_FAILURE',

  DELETE_ROUTE_REQUEST: 'DELETE_DELETE_ROUTE_REQUEST',
  DELETE_ROUTE_SUCCESS: 'DELETE_ROUTE_SUCCESS',
  DELETE_ROUTE_FAILURE: 'DELETE_ROUTE_FAILURE',

  CREATE_ROUTE_REQUEST: 'CREATE_ROUTE_REQUEST',
  CREATE_ROUTE_SUCCESS: 'CREATE_ROUTE_SUCCESS',
  CREATE_ROUTE_FAILURE: 'CREATE_ROUTE_FAILURE',

  EDIT_ROUTE_REQUEST: 'EDIT_ROUTE_REQUEST',
  EDIT_ROUTE_SUCCESS: 'EDIT_ROUTE_SUCCESS',
  EDIT_ROUTE_FAILURE: 'EDIT_ROUTE_FAILURE',

  GET_DETAIL_ROUTE_REQUEST: 'GET_DETAIL_ROUTE_REQUEST',
  GET_DETAIL_ROUTE_SUCCESS: 'GET_DETAIL_ROUTE_SUCCESS',
  GET_DETAIL_ROUTE_FAILURE: 'GET_DETAIL_ROUTE_FAILURE'
}
