export const UserConstants = {
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILE: 'GET_USERS_FAILE',

    GET_USERS_PAGINATE_REQUEST: 'GET_USERS_PAGINATE_REQUEST',
    GET_USERS_PAGINATE_SUCCESS: 'GET_USERS_PAGINATE_SUCCESS',
    GET_USERS_PAGINATE_FAILE: 'GET_USERS_PAGINATE_FAILE',

    EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILE: 'EDIT_USER_FAILE',

    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILE: 'CREATE_USER_FAILE',

    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILE: 'DELETE_USER_FAILE',

    SEARCH_USER_BY_NAME_REQUEST: 'SEARCH_USER_BY_NAME_REQUEST',
    SEARCH_USER_BY_NAME_SUCCESS: 'SEARCH_USER_BY_NAME_SUCCESS',
    SEARCH_USER_BY_NAME_FAILE: 'SEARCH_USER_BY_NAME_FAILE',
}