export const BuyRequestConstants = {
    GET_BUYREQUEST_REQUEST: 'GET_BUYREQUEST_REQUEST',
    GET_BUYREQUEST_SUCCESS: 'GET_BUYREQUEST_SUCCESS',
    GET_BUYREQUEST_FAILURE: 'GET_BUYREQUEST_FAILURE',

    CREATE_BUYREQUEST_REQUEST: 'CREATE_NEW_BUYREQUEST_REQUEST',
    CREATE_BUYREQUEST_SUCCESS: 'CREATE_NEW_BUYREQUEST_SUCCESS',
    CREATE_BUYREQUEST_FAILURE: 'CREATE_NEW_BUYREQUEST_FAILURE',

    DELETE_BUYREQUEST_REQUEST: 'DELETE_BUYREQUEST_REQUEST',
    DELETE_BUYREQUEST_SUCCESS:  'DELETE_BUYREQUEST_SUCCESS',
    DELETE_BUYREQUEST_FAILURE:  'DELETE_BUYREQUEST_FAILURE',

    UPDATE_BUYREQUEST_REQUEST: 'UPDATE_BUYREQUEST_REQUEST',
    UPDATE_BUYREQUEST_SUCCESS: 'UPDATE_BUYREQUEST_SUCCESS',
    UPDATE_BUYREQUEST_FAILURE: 'UPDATE_BUYREQUEST_FAILURE',
};