export const Constants = {
    GET_PERSONAL_INFOR_REQUEST: 'EMPLOYEE_GET_PERSONAL_INFOR_REQUEST',
    GET_PERSONAL_INFOR_SUCCESS: 'EMPLOYEE_GET_PERSONAL_INFOR_SUCCESS',
    GET_PERSONAL_INFOR_FAILURE: 'EMPLOYEE_GET_PERSONAL_INFOR_FAILURE',

    UPDATE_PERSONAL_INFOR_REQUEST: 'EMPLOYEE_UPDATE_PERSONAL_INFOR_REQUEST',
    UPDATE_PERSONAL_INFOR_SUCCESS: 'EMPLOYEE_UPDATE_PERSONAL_INFOR_SUCCESS',
    UPDATE_PERSONAL_INFOR_FAILURE: 'EMPLOYEE_UPDATE_PERSONAL_INFOR_FAILURE',
};