export const riskResponsePlanRequestConstants ={
    
    GET_RISK_RESPONSE_PLAN_REQUEST_REQUEST: 'GET_RISK_RESPONSE_PLAN_REQUEST_REQUEST',
    GET_RISK_RESPONSE_PLAN_REQUEST_SUCCESS: 'GET_RISK_RESPONSE_PLAN_REQUEST_SUCCESS',
    GET_RISK_RESPONSE_PLAN_REQUEST_FAILURE: 'GET_RISK_RESPONSE_PLAN_REQUEST_FAILURE',

    EDIT_RISK_RESPONSE_PLAN_REQUEST_REQUEST: 'EDIT_RISK_RESPONSE_PLAN_REQUEST_REQUEST',
    EDIT_RISK_RESPONSE_PLAN_REQUEST_SUCCESS: 'EDIT_RISK_RESPONSE_PLAN_REQUEST_SUCCESS',
    EDIT_RISK_RESPONSE_PLAN_REQUEST_FAILURE: 'EDIT_RISK_RESPONSE_PLAN_REQUEST_FAILURE',

    CREATE_RISK_RESPONSE_PLAN_REQUEST_REQUEST: 'CREATE_RISK_RESPONSE_PLAN_REQUEST_REQUEST',
    CREATE_RISK_RESPONSE_PLAN_REQUEST_SUCCESS: 'CREATE_RISK_RESPONSE_PLAN_REQUEST_SUCCESS',
    CREATE_RISK_RESPONSE_PLAN_REQUEST_FAILURE: 'CREATE_RISK_RESPONSE_PLAN_REQUEST_FAILURE',

    DELETE_RISK_RESPONSE_PLAN_REQUEST_REQUEST: 'DELETE_RISK_RESPONSE_PLAN_REQUEST_REQUEST',
    DELETE_RISK_RESPONSE_PLAN_REQUEST_SUCCESS: 'DELETE_RISK_RESPONSE_PLAN_REQUEST_SUCCESS',
    DELETE_RISK_RESPONSE_PLAN_REQUEST_FAILURE: 'DELETE_RISK_RESPONSE_PLAN_REQUEST_FAILURE',

    GET_RISK_RESPONSE_PLAN_REQUEST_BY_ID_REQUEST: 'GET_RISK_RESPONSE_PLAN_REQUEST_BY_ID_REQUEST',
    GET_RISK_RESPONSE_PLAN_REQUEST_BY_ID_SUCCESS: 'GET_RISK_RESPONSE_PLAN_REQUEST_BY_ID_SUCCESS',
    GET_RISK_RESPONSE_PLAN_REQUEST_BY_ID_FAILURE: 'GET_RISK_RESPONSE_PLAN_BY_ID_FAILURE',
    
}