services:
  security-control-service:
    container_name: security-control-service
    image: node:alpine
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./node_modules:/app/node_modules
      - ./:/app
    command: sh -c "cd /app && npm install && npm start"
