export const forecastConstants = {
    CREATE_FORECAST_REQUEST: 'CREATE_FORECAST_REQUEST',
    CREATE_FORECAST_SUCCESS: 'CREATE_FORECAST_SUCCESS',
    CREATE_FORECAST_FAILURE: 'CREATE_FORECAST_FAILURE'
};
