export const forecastConstants = {
    CREATE_FORECAST_REQUEST: 'CREATE_FORECAST_REQUEST',
    CREATE_FORECAST_SUCCESS: 'CREATE_FORECAST_SUCCESS',
    CREATE_FORECAST_FAILURE: 'CREATE_FORECAST_FAILURE',
    GET_ALL_FORECASTS_REQUEST: 'GET_ALL_FORECASTS_REQUEST',
    GET_ALL_FORECASTS_SUCCESS: 'GET_ALL_FORECASTS_SUCCESS',
    GET_ALL_FORECASTS_FAILURE: 'GET_ALL_FORECASTS_FAILURE'
};
