export const LotConstants = {

    GET_LOT_REQUEST: 'GET_LOT_REQUEST',
    GET_LOT_SUCCESS: 'GET_LOT_SUCCESS',
    GET_LOT_FAILURE: 'GET_LOT_FAILURE',

    GET_PAGINATE_LOT_REQUEST: 'GET_PAGINATE_LOT_REQUEST',
    GET_PAGINATE_LOT_SUCCESS: 'GET_PAGINATE_LOT_SUCCESS',
    GET_PAGINATE_LOT_FAILURE: 'GET_PAGINATE_LOT_FAILURE',
}