export const LotConstants = {

    GET_LOT_REQUEST: 'GET_LOT_REQUEST',
    GET_LOT_SUCCESS: 'GET_LOT_SUCCESS',
    GET_LOT_FAILURE: 'GET_LOT_FAILURE',

    GET_LOT_PAGINATE_REQUEST: 'GET_LOT_PAGINATE_REQUEST',
    GET_LOT_PAGINATE_SUCCESS: 'GET_LOT_PAGINATE_SUCCESS',
    GET_LOT_PAGINATE_FAILURE: 'GET_LOT_PAGINATE_FAILURE',

    GET_LOT_DETAIL_REQUEST: 'GET_LOT_DETAIL_REQUEST',
    GET_LOT_DETAIL_SUCCESS: 'GET_LOT_DETAIL_SUCCESS',
    GET_LOT_DETAIL_FAILURE: 'GET_LOT_DETAIL_FAILURE',

    GET_LOT_BY_GOOD_REQUEST: 'GET_LOT_BY_GOOD_REQUEST',
    GET_LOT_BY_GOOD_SUCCESS: 'GET_LOT_BY_GOOD_SUCCESS',
    GET_LOT_BY_GOOD_FAILURE: 'GET_LOT_BY_GOOD_FAILURE',

    EDIT_LOT_REQUEST: 'EDIT_LOT_REQUEST',
    EDIT_LOT_SUCCESS: 'EDIT_LOT_SUCCESS',
    EDIT_LOT_FAILURE: 'EDIT_LOT_FAILURE',
}