export const createKpiSetConstants  = {
    GET_EMPLOYEE_KPI_SET_REQUEST: 'GET_EMPLOYEE_KPI_SET_REQUEST',
    DELETE_EMPLOYEE_KPI_SUCCESS: 'GET_EMPLOYEE_KPI_SET_SUCCESS',
    GET_EMPLOYEE_KPI_SET_FAILURE: 'GET_EMPLOYEE_KPI_SET_FAILURE',

    DELETE_EMPLOYEE_KPI_REQUEST: 'DELETE_EMPLOYEE_KPI_REQUEST',
    DELETE_EMPLOYEE_KPI_SUCCESS: 'DELETE_EMPLOYEE_KPI_SUCCESS',
    DELETE_EMPLOYEE_KPI_FAILURE: 'DELETE_EMPLOYEE_KPI_FAILURE',

    EDIT_EMPLOYEE_KPI_SET_REQUEST: 'EDIT_EMPLOYEE_KPI_SET_REQUEST',
    EDIT_EMPLOYEE_KPI_SET_SUCCESS: 'EDIT_EMPLOYEE_KPI_SET_SUCCESS',
    EDIT_EMPLOYEE_KPI_SET_FAILURE: 'EDIT_EMPLOYEE_KPI_SET_FAILURE',

    DELETE_EMPLOYEE_KPI_SET_REQUEST: 'DELETE_EMPLOYEE_KPI_SET_REQUEST',
    DELETE_EMPLOYEE_KPI_SET_SUCCESS: 'DELETE_EMPLOYEE_KPI_SET_SUCCESS',
    DELETE_EMPLOYEE_KPI_SET_FAILURE: 'DELETE_EMPLOYEE_KPI_SET_FAILURE',

    UPDATE_EMPLOYEE_KPI_SET_STATUS_REQUEST: 'UPDATE_EMPLOYEE_KPI_SET_STATUS_REQUEST',
    UPDATE_EMPLOYEE_KPI_SET_STATUS_SUCCESS: 'UPDATE_EMPLOYEE_KPI_SET_STATUS_SUCCESS',
    UPDATE_EMPLOYEE_KPI_SET_STATUS_FAILURE: 'UPDATE_EMPLOYEE_KPI_SET_STATUS_FAILURE',
    
    CREATE_EMPLOYEE_KPI_REQUEST: 'CREATE_EMPLOYEE_KPI_REQUEST',
    CREATE_EMPLOYEE_KPI_SUCCESS: 'CREATE_EMPLOYEE_KPI_SUCCESS',
    CREATE_EMPLOYEE_KPI_FAILURE: 'CREATE_EMPLOYEE_KPI_FAILURE',
    
    EDIT_EMPLOYEE_KPI_REQUEST: 'EDIT_EMPLOYEE_KPI_REQUEST',
    EDIT_EMPLOYEE_KPI_SUCCESS: 'EDIT_EMPLOYEE_KPI_SUCCESS',
    EDIT_EMPLOYEE_KPI_FAILURE: 'EDIT_EMPLOYEE_KPI_FAILURE',

    CREATE_EMPLOYEE_KPI_SET_REQUEST: 'CREATE_EMPLOYEE_KPI_SET_REQUEST',
    CREATE_EMPLOYEE_KPI_SET_SUCCESS: 'CREATE_EMPLOYEE_KPI_SET_SUCCESS',
    CREATE_EMPLOYEE_KPI_SET_FAILURE: 'CREATE_EMPLOYEE_KPI_SET_FAILURE',

    APPROVE_EMPLOYEE_KPI_SET_REQUEST: 'APPROVE_EMPLOYEE_KPI_SET_REQUEST',
    APPROVE_EMPLOYEE_KPI_SET_SUCCESS: 'APPROVE_EMPLOYEE_KPI_SET_SUCCESS',
    APPROVE_EMPLOYEE_KPI_SET_FAILURE: 'APPROVE_EMPLOYEE_KPI_SET_FAILURE',

}