export const createKpiConstants  = {
    GETCURRENT_KPIPERSONAL_REQUEST: 'GETCURRENT_KPIPERSONAL_REQUEST',
    GETCURRENT_KPIPERSONAL_SUCCESS: 'GETCURRENT_KPIPERSONAL_SUCCESS',
    GETCURRENT_KPIPERSONAL_FAILURE: 'GETCURRENT_KPIPERSONAL_FAILURE',

    DELETETARGET_KPIPERSONAL_REQUEST: 'DELETETARGET_KPIPERSONAL_REQUEST',
    DELETETARGET_KPIPERSONAL_SUCCESS: 'DELETETARGET_KPIPERSONAL_SUCCESS',
    DELETETARGET_KPIPERSONAL_FAILURE: 'DELETETARGET_KPIPERSONAL_FAILURE',

    EDIT_KPIPERSONAL_REQUEST: 'EDIT_KPIPERSONAL_REQUEST',
    EDIT_KPIPERSONAL_SUCCESS: 'EDIT_KPIPERSONAL_SUCCESS',
    EDIT_KPIPERSONAL_FAILURE: 'EDIT_KPIPERSONAL_FAILURE',

    DELETE_KPIPERSONAL_REQUEST: 'DELETE_KPIPERSONAL_REQUEST',
    DELETE_KPIPERSONAL_SUCCESS: 'DELETE_KPIPERSONAL_SUCCESS',
    DELETE_KPIPERSONAL_FAILURE: 'DELETE_KPIPERSONAL_FAILURE',

    EDITSTATUS_KPIPERSONAL_REQUEST: 'EDITSTATUS_KPIPERSONAL_REQUEST',
    EDITSTATUS_KPIPERSONAL_SUCCESS: 'EDITSTATUS_KPIPERSONAL_SUCCESS',
    EDITSTATUS_KPIPERSONAL_FAILURE: 'EDITSTATUS_KPIPERSONAL_FAILURE',
    
    ADDTARGET_KPIPERSONAL_REQUEST: 'ADDTARGET_KPIPERSONAL_REQUEST',
    ADDTARGET_KPIPERSONAL_SUCCESS: 'ADDTARGET_KPIPERSONAL_SUCCESS',
    ADDTARGET_KPIPERSONAL_FAILURE: 'ADDTARGET_KPIPERSONAL_FAILURE',
    
    EDITTARGET_KPIPERSONAL_REQUEST: 'EDITTARGET_KPIPERSONAL_REQUEST',
    EDITTARGET_KPIPERSONAL_SUCCESS: 'EDITTARGET_KPIPERSONAL_SUCCESS',
    EDITTARGET_KPIPERSONAL_FAILURE: 'EDITTARGET_KPIPERSONAL_FAILURE',

    ADD_KPIPERSONAL_REQUEST: 'ADD_KPIPERSONAL_REQUEST',
    ADD_KPIPERSONAL_SUCCESS: 'ADD_KPIPERSONAL_SUCCESS',
    ADD_KPIPERSONAL_FAILURE: 'ADD_KPIPERSONAL_FAILURE',

    APPROVE_KPIPERSONAL_REQUEST: 'APPROVE_KPIPERSONAL_REQUEST',
    APPROVE_KPIPERSONAL_SUCCESS: 'APPROVE_KPIPERSONAL_SUCCESS',
    APPROVE_KPIPERSONAL_FAILURE: 'APPROVE_KPIPERSONAL_FAILURE',

}