export const RiskConstants ={
    GET_RISK_PLAN_REQUEST: 'GET_RISK_PLAN_REQUEST',
    GET_RISK_PLAN_SUCCESS: 'GET_RISK_PLAN_SUCCESS',
    GET_RISK_PLAN_FAILURE: 'GET_RISK_PLAN_FAILURE',

    GET_RISK_REQUEST: 'GET_RISK_REQUEST',
    GET_RISK_SUCCESS: 'GET_RISK_SUCCESS',
    GET_RISK_FAILURE: 'GET_RISK_FAILURE',

    EDIT_RISK_REQUEST: 'EDIT_RISK_REQUEST',
    EDIT_RISK_SUCCESS: 'EDIT_RISK_SUCCESS',
    EDIT_RISK_FAILURE: 'EDIT_RISK_FAILURE',

    CREATE_RISK_REQUEST: 'CREATE_RISK_REQUEST',
    CREATE_RISK_SUCCESS: 'CREATE_RISK_SUCCESS',
    CREATE_RISK_FAILURE: 'CREATE_RISK_FAILURE',

    DELETE_RISK_REQUEST: 'DELETE_RISK_REQUEST',
    DELETE_RISK_SUCCESS: 'DELETE_RISK_SUCCESS',
    DELETE_RISK_FAILURE: 'DELETE_RISK_FAILURE',

    GET_RISK_BY_ID_REQUEST: 'GET_RISK_BY_ID_REQUEST',
    GET_RISK_BY_ID_SUCCESS: 'GET_RISK_BY_ID_SUCCESS',
    GET_RISK_BY_ID_FAILURE: 'GET_RISK_BY_ID_FAILURE',

    GET_TASK_BY_RISK_REQUEST: 'GET_TASK_BY_RISK_REQUEST',
    GET_TASK_BY_RISK_SUCCESS: 'GET_TASK_BY_RISK_SUCCESS',
    GET_TASK_BY_RISK_FAILURE: 'GET_TASK_BY_RISK_FAILURE',

    REQUEST_CLOSE_RISK_REQUEST: 'REQUEST_CLOSE_RISK_REQUEST',
    REQUEST_CLOSE_RISK_SUCCESS: 'REQUEST_CLOSE_RISK_SUCCESS',
    REQUEST_CLOSE_RISK_FAILURE: 'REQUEST_CLOSE_RISK_FAILURE',
}