export const managerChainConstants = {
    GET_ALL_CHAINS_REQUEST: "GET_ALL_CHAINS_REQUEST",
    GET_ALL_CHAINS_SUCCESS: "GET_ALL_CHAINS_SUCCESS",
    GET_ALL_CHAINS_FAILURE: "GET_ALL_CHAINS_FAILURE",

    GET_CHAIN_BY_ID_REQUEST: "GET_CHAIN_BY_ID_REQUEST",
    GET_CHAIN_BY_ID_SUCCESS: "GET_CHAIN_BY_ID_SUCCESS",
    GET_CHAIN_BY_ID_FAILURE: "GET_CHAIN_BY_ID_FAILURE",

    CREATE_CHAIN_TEMPLATE_REQUEST: "CREATE_CHAIN_TEMPLATE_REQUEST",
    CREATE_CHAIN_TEMPLATE_SUCCESS: "CREATE_CHAIN_TEMPLATE_SUCCESS",
    CREATE_CHAIN_TEMPLATE_FAILURE: "CREATE_CHAIN_TEMPLATE_FAILURE",

    EDIT_CHAIN_TEMPLATE_REQUEST: "EDIT_CHAIN_TEMPLATE_REQUEST",
    EDIT_CHAIN_TEMPLATE_SUCCESS: "EDIT_CHAIN_TEMPLATE_SUCCESS",
    EDIT_CHAIN_TEMPLATE_FAILURE: "EDIT_CHAIN_TEMPLATE_FAILURE",

    DELETE_CHAIN_TEMPLATE_REQUEST: "DELETE_CHAIN_TEMPLATE_REQUEST",
    DELETE_CHAIN_TEMPLATE_SUCCESS: "DELETE_CHAIN_TEMPLATE_SUCCESS",
    DELETE_CHAIN_TEMPLATE_FAILURE: "DELETE_CHAIN_TEMPLATE_FAILURE",

    GET_ASSET_TEMPLATE_REQUEST: "GET_ASSET_TEMPLATE_REQUEST",
    GET_ASSET_TEMPLATE_SUCCESS: "GET_ASSET_TEMPLATE_SUCCESS",
    GET_ASSET_TEMPLATE_FAILURE: "GET_ASSET_TEMPLATE_FAILURE",

    GET_ASSET_TEMPLATE_BY_ID_REQUEST: "GET_ASSET_TEMPLATE_BY_ID_REQUEST",
    GET_ASSET_TEMPLATE_BY_ID_SUCCESS: "GET_ASSET_TEMPLATE_BY_ID_SUCCESS",
    GET_ASSET_TEMPLATE_BY_ID_FAILURE: "GET_ASSET_TEMPLATE_BY_ID_FAILURE",

    CREATE_ASSET_TEMPLATE_REQUEST: "CREATE_ASSET_TEMPLATE_REQUEST",
    CREATE_ASSET_TEMPLATE_SUCCESS: "CREATE_ASSET_TEMPLATE_SUCCESS",
    CREATE_ASSET_TEMPLATE_FAILURE: "CREATE_ASSET_TEMPLATE_FAILURE",
}