export const commandConstants = {
    GET_ALL_MANUFACTURING_COMMAND_REQUEST: 'GET_ALL_MANUFACTURING_COMMAND_REQUEST',
    GET_ALL_MANUFACTURING_COMMAND_SUCCESS: 'GET_ALL_MANUFACTURING_COMMAND_SUCCESS',
    GET_ALL_MANUFACTURING_COMMAND_FAILURE: 'GET_ALL_MANUFACTURING_COMMAND_FAILURE'
}