export const UsageConstants = {
    
    CREATE_USAGE_REQUEST: 'CREATE_NEW_USAGE_REQUEST',
    CREATE_USAGE_SUCCESS: 'CREATE_NEW_USAGE_SUCCESS',
    CREATE_USAGE_FAILURE: 'CREATE_NEW_USAGE_FAILURE',

    UPDATE_USAGE_REQUEST: 'UPDATE_USAGE_REQUEST',
    UPDATE_USAGE_SUCCESS: 'UPDATE_USAGE_SUCCESS',
    UPDATE_USAGE_FAILURE: 'UPDATE_USAGE_FAILURE',

    DELETE_USAGE_REQUEST: 'DELETE_USAGE_REQUEST',
    DELETE_USAGE_SUCCESS: 'DELETE_USAGE_SUCCESS',
    DELETE_USAGE_FAILURE: 'DELETE_USAGE_FAILURE',

};
