export const HolidayConstants = {
    GET_HOLIDAY_REQUEST: 'GET_HOLIDAY_REQUEST',
    GET_HOLIDAY_SUCCESS: 'GET_HOLIDAY_SUCCESS',
    GET_HOLIDAY_FAILURE: 'GET_HOLIDAY_FAILURE',

    CREATE_HOLIDAY_REQUEST: 'CREATE_NEW_HOLIDAY_REQUEST',
    CREATE_HOLIDAY_SUCCESS: 'CREATE_NEW_HOLIDAY_SUCCESS',
    CREATE_HOLIDAY_FAILURE: 'CREATE_NEW_HOLIDAY_FAILURE',

    DELETE_HOLIDAY_REQUEST: 'DELETE_HOLIDAY_REQUEST',
    DELETE_HOLIDAY_SUCCESS: 'DELETE_HOLIDAY_SUCCESS',
    DELETE_HOLIDAY_FAILURE: 'DELETE_HOLIDAY_FAILURE',

    UPDATE_HOLIDAY_REQUEST: 'UPDATE_HOLIDAY_REQUEST',
    UPDATE_HOLIDAY_SUCCESS: 'UPDATE_HOLIDAY_SUCCESS',
    UPDATE_HOLIDAY_FAILURE: 'UPDATE_HOLIDAY_FAILURE',

    IMPORT_HOLIDAY_REQUEST: "IMPORT_HOLIDAY_EMPLOYEE_REQUEST",
    IMPORT_HOLIDAY_SUCCESS: "IMPORT_HOLIDAY_EMPLOYEE_SUCCESS",
    IMPORT_HOLIDAY_FAILURE: "IMPORT_HOLIDAY_EMPLOYEE_FAILURE",
};