export const TaskProcessConstants = {

  GET_ALL_XML_DIAGRAM_REQUEST: "GET_ALL_XML_DIAGRAM_REQUEST",
  GET_ALL_XML_DIAGRAM_SUCCESS: "GET_ALL_XML_DIAGRAM_SUCCESS",
  GET_ALL_XML_DIAGRAM_FAIL: "GET_ALL_XML_DIAGRAM_FAIL",

  GET_XML_DIAGRAM_BY_ID_REQUEST: "GET_XML_DIAGRAM_BY_ID_REQUEST",
  GET_XML_DIAGRAM_BY_ID_SUCCESS: "GET_XML_DIAGRAM_BY_ID_SUCCESS",
  GET_XML_DIAGRAM_BY_ID_FAIL: "GET_XML_DIAGRAM_BY_ID_FAIL",

  CREATE_XML_DIAGRAM_REQUEST: "CREATE_XML_DIAGRAM_REQUEST",
  CREATE_XML_DIAGRAM_SUCCESS: "CREATE_XML_DIAGRAM_SUCCESS",
  CREATE_XML_DIAGRAM_FAIL: "CREATE_XML_DIAGRAM_FAIL",

  EDIT_XML_DIAGRAM_REQUEST: "EDIT_XML_DIAGRAM_REQUEST",
  EDIT_XML_DIAGRAM_SUCCESS: "EDIT_XML_DIAGRAM_SUCCESS",
  EDIT_XML_DIAGRAM_FAIL: "EDIT_XML_DIAGRAM_FAIL",

  DELETE_XML_DIAGRAM_REQUEST: "DELETE_XML_DIAGRAM_REQUEST",
  DELETE_XML_DIAGRAM_SUCCESS: "DELETE_XML_DIAGRAM_SUCCESS",
  DELETE_XML_DIAGRAM_FAIL: "DELETE_XML_DIAGRAM_FAIL",


}