export const TaskProcessConstants = {
  EXPORT_XML_DIAGRAM_REQUEST: "EXPORT_XML_DIAGRAM_REQUEST",
  EXPORT_XML_DIAGRAM_SUCCESS: "EXPORT_XML_DIAGRAM_SUCCESS",
  EXPORT_XML_DIAGRAM_FAIL: "EXPORT_XML_DIAGRAM_FAIL"


}