export const Constants = {
    GETINFORMATIONEMPLOYEE_REQUEST: 'EMPLOYEE_GET_INFORMATION_EMPLOYEE_REQUEST',
    GETINFORMATIONEMPLOYEE_SUCCESS: 'EMPLOYEE_GET_INFORMATION_EMPLOYEE_SUCCESS',
    GETINFORMATIONEMPLOYEE_FAILURE: 'EMPLOYEE_GET_INFORMATION_EMPLOYEE_FAILURE',

    ADDEMPLOYEE_REQUEST: 'EMPLOYEE_ADDEMPLOYEE_REQUEST',
    ADDEMPLOYEE_SUCCESS: 'EMPLOYEE_ADDEMPLOYEE_SUCCESS',
    ADDEMPLOYEE_FAILURE: 'EMPLOYEE_ADDEMPLOYEE_FAILURE',

    UPDATE_INFORMATION_REQUEST: 'EMPLOYEE_UPDATE_INFORMATION_REQUEST',
    UPDATE_INFORMATION_SUCCESS: 'EMPLOYEE_UPDATE_INFORMATION_SUCCESS',
    UPDATE_INFORMATION_FAILURE: 'EMPLOYEE_UPDATE_INFORMATION_FAILURE',

    UPLOAD_AVATAR_REQUEST: "ULOAD_AVATAR_EMPLOYEE_REQUEST",
    UPLOAD_AVATAR_SUCCESS: "ULOAD_AVATAR_EMPLOYEE_SUCCESS",
    UPLOAD_AVATAR_FAILURE: "ULOAD_AVATAR_EMPLOYEE_FAILURE",

    UPDATE_CONTRACT_REQUEST: "UPDATE_CONTRACT_EMPLOYEE_REQUEST",
    UPDATE_CONTRACT_SUCCESS: "UPDATE_CONTRACT_EMPLOYEE_SUCCESS",
    UPDATE_CONTRACT_FAILURE: "UPDATE_CONTRACT_EMPLOYEE_FAILURE",

    UPDATE_CERTIFICATESHORT_REQUEST: "UPDATE_CERTIFICATESHORT_EMPLOYEE_REQUEST",
    UPDATE_CERTIFICATESHORT_SUCCESS: "UPDATE_CERTIFICATESHORT_EMPLOYEE_SUCCESS",
    UPDATE_CERTIFICATESHORT_FAILURE: "UPDATE_CERTIFICATESHORT_EMPLOYEE_FAILURE",

    UPDATE_CERTIFICATE_REQUEST: "UPDATE_CERTIFICATE_EMPLOYEE_REQUEST",
    UPDATE_CERTIFICATE_SUCCESS: "UPDATE_CERTIFICATE_EMPLOYEE_SUCCESS",
    UPDATE_CERTIFICATE_FAILURE: "UPDATE_CERTIFICATE_EMPLOYEE_FAILURE",

    UPDATE_FILE_REQUEST: "UPDATE_FILE_EMPLOYEE_REQUEST",
    UPDATE_FILE_SUCCESS: "UPDATE_FILE_EMPLOYEE_SUCCESS",
    UPDATE_FILE_FAILURE: "UPDATE_FILE_EMPLOYEE_FAILURE",

};