export const constants = {
    GETINFORMATIONEMPLOYEE_REQUEST: 'EMPLOYEE_GET_INFORMATION_EMPLOYEE_REQUEST',
    GETINFORMATIONEMPLOYEE_SUCCESS: 'EMPLOYEE_GET_INFORMATION_EMPLOYEE_SUCCESS',
    GETINFORMATIONEMPLOYEE_FAILURE: 'EMPLOYEE_GET_INFORMATION_EMPLOYEE_FAILURE',

    ADDEMPLOYEE_REQUEST: 'EMPLOYEE_ADDEMPLOYEE_REQUEST',
    ADDEMPLOYEE_SUCCESS: 'EMPLOYEE_ADDEMPLOYEE_SUCCESS',
    ADDEMPLOYEE_FAILURE: 'EMPLOYEE_ADDEMPLOYEE_FAILURE',

    UPDATE_INFORMATION_REQUEST: 'EMPLOYEE_UPDATE_INFORMATION_REQUEST',
    UPDATE_INFORMATION_SUCCESS: 'EMPLOYEE_UPDATE_INFORMATION_SUCCESS',
    UPDATE_INFORMATION_FAILURE: 'EMPLOYEE_UPDATE_INFORMATION_FAILURE',



};