name: Deploy to VPS

on:
  #  pull_request:
  #    branches: [ "dev" ]
  #    types:
  #      - closed
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 2221
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd root/
            if [ ! -d "qlcv-refactor" ]; then
              git clone -b dev https://github.com/VNISTResearch/qlcv-refactor.git
            fi
            cd qlcv-refactor
            git pull
            cp server/.env.example server/.env
            cp client-vite/.env.example client-vite/.env
            docker-compose -f docker-compose.yml up -d --build
