export const delegationConstants = {
    GET_ALL_DELEGATIONS_REQUEST: "GET_ALL_DELEGATIONS_REQUEST",
    GET_ALL_DELEGATIONS_SUCCESS: "GET_ALL_DELEGATIONS_SUCCESS",
    GET_ALL_DELEGATIONS_FAILURE: "GET_ALL_DELEGATIONS_FAILURE",

    REPLY_DELEGATION_REQUEST: "REPLY_DELEGATION_REQUEST",
    REPLY_DELEGATION_SUCCESS: "REPLY_DELEGATION_SUCCESS",
    REPLY_DELEGATION_FAILURE: "REPLY_DELEGATION_FAILURE",



}