export const transportPlanConstants = {
    GET_ALL_TRANSPORT_PLANS_REQUEST: "GET_ALL_TRANSPORT_PLANS_REQUEST",
    GET_ALL_TRANSPORT_PLANS_SUCCESS: "GET_ALL_TRANSPORT_PLANS_SUCCESS",
    GET_ALL_TRANSPORT_PLANS_FAILURE: "GET_ALL_TRANSPORT_PLANS_FAILURE",

    CREATE_TRANSPORT_PLAN_REQUEST: "CREATE_TRANSPORT_PLAN_REQUEST",
    CREATE_TRANSPORT_PLAN_SUCCESS: "CREATE_TRANSPORT_PLAN_SUCCESS",
    CREATE_TRANSPORT_PLAN_FAILURE: "CREATE_TRANSPORT_PLAN_FAILURE",
}
