export const transportScheduleConstants = {
    GET_ALL_TRANSPORT_SCHEDULES_REQUEST: "GET_ALL_TRANSPORT_SCHEDULES_REQUEST",
    GET_ALL_TRANSPORT_SCHEDULES_SUCCESS: "GET_ALL_TRANSPORT_SCHEDULES_SUCCESS",
    GET_ALL_TRANSPORT_SCHEDULES_FAILURE: "GET_ALL_TRANSPORT_SCHEDULES_FAILURE",

    CREATE_TRANSPORT_SCHEDULE_REQUEST: "CREATE_TRANSPORT_SCHEDULE_REQUEST",
    CREATE_TRANSPORT_SCHEDULE_SUCCESS: "CREATE_TRANSPORT_SCHEDULE_SUCCESS",
    CREATE_TRANSPORT_SCHEDULE_FAILURE: "CREATE_TRANSPORT_SCHEDULE_FAILURE",
}
