export const CompanyConstants = {
    GET_COMPANIES_REQUEST: 'GET_COMPANIES_REQUEST',
    GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
    GET_COMPANIES_FAILE: 'GET_COMPANIES_FAILE',

    GET_COMPANIES_PAGINATE_REQUEST: 'GET_COMPANIES_PAGINATE_REQUEST',
    GET_COMPANIES_PAGINATE_SUCCESS: 'GET_COMPANIES_PAGINATE_SUCCESS',
    GET_COMPANIES_PAGINATE_FAILE: 'GET_COMPANIES_PAGINATE_FAILE',

    CREATE_COMPANY_REQUEST: 'CREATE_COMPANY_REQUEST',
    CREATE_COMPANY_SUCCESS: 'CREATE_COMPANY_SUCCESS',
    CREATE_COMPANY_FAILE: 'CREATE_COMPANY_FAILE',
    
    EDIT_COMPANY_REQUEST: 'EDIT_COMPANY_REQUEST',
    EDIT_COMPANY_SUCCESS: 'EDIT_COMPANY_SUCCESS',
    EDIT_COMPANY_FAILE: 'EDIT_COMPANY_FAILE',   

    ADD_NEW_LINK_FOR_COMPANY_REQUEST: 'ADD_NEW_LINK_FOR_COMPANY_REQUEST',
    ADD_NEW_LINK_FOR_COMPANY_SUCCESS: 'ADD_NEW_LINK_FOR_COMPANY_SUCCESS',
    ADD_NEW_LINK_FOR_COMPANY_FAILE: 'ADD_NEW_LINK_FOR_COMPANY_FAILE',
    
    DELETE_LINK_FOR_COMPANY_REQUEST: 'DELETE_LINK_FOR_COMPANY_REQUEST',
    DELETE_LINK_FOR_COMPANY_SUCCESS: 'DELETE_LINK_FOR_COMPANY_SUCCESS',
    DELETE_LINK_FOR_COMPANY_FAILE: 'DELETE_LINK_FOR_COMPANY_FAILE',
}