const TaskProjectConstant = {
    GET_TASK_PROJECT_REQUEST: 'GET_TASK_PROJECT_REQUEST',
    GET_TASK_PROJECT_SUCCESS: 'GET_TASK_PROJECT_SUCCESS',
    GET_TASK_PROJECT_FAILE: 'GET_TASK_PROJECT_FAILE',

    SHOW_TASK_PROJECT_REQUEST: 'SHOW_TASK_PROJECT_REQUEST',
    SHOW_TASK_PROJECT_SUCCESS: 'SHOW_TASK_PROJECT_SUCCESS',
    SHOW_TASK_PROJECT_FAILE: 'SHOW_TASK_PROJECT_FAILE',

    CREATE_TASK_PROJECT_REQUEST: 'CREATE_TASK_PROJECT_REQUEST',
    CREATE_TASK_PROJECT_SUCCESS: 'CREATE_TASK_PROJECT_SUCCESS',
    CREATE_TASK_PROJECT_FAILE: 'CREATE_TASK_PROJECT_FAILE',

    EDIT_TASK_PROJECT_REQUEST: 'EDIT_TASK_PROJECT_REQUEST',
    EDIT_TASK_PROJECT_SUCCESS: 'EDIT_TASK_PROJECT_SUCCESS',
    EDIT_TASK_PROJECT_FAILE: 'EDIT_TASK_PROJECT_FAILE',

    DELETE_TASK_PROJECT_REQUEST: 'DELETE_TASK_PROJECT_REQUEST',
    DELETE_TASK_PROJECT_SUCCESS: 'DELETE_TASK_PROJECT_SUCCESS',
    DELETE_TASK_PROJECT_FAILE: 'DELETE_TASK_PROJECT_FAILE',
}

export default TaskProjectConstant;